### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by 1nj0k** [gojue/ecapture#253]
**Describe the bug**

>tls_2022/10/30 21:49:06 ECAPTURE :: ecapture Version : linux_x86_64:0.4.7-20221030-c0e990f:[CORE]
tls_2022/10/30 21:49:06 ECAPTURE :: Pid Info : 6196
tls_2022/10/30 21:49:06 ECAPTURE :: Kernel Info : 6.0.6
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        module initialization
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        master key keylogger: ecapture_masterkey.log
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        Module.Run()
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        UPROBE MODEL
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        OpenSSL/BoringSSL version not found from shared library file, used default version:linux_default_1_1_1
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/lib64/libssl.so.1.1
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        libPthread so Path:/lib64/libc.so.6
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        target all process. 
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        target all users. 
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/openssl_1_1_1r_kern.o
tls_2022/10/30 21:49:06 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't init manager error:program probe_ssl_master_key: apply CO-RE relocations: can't read types: type id 6813: unknown kind: Unknown (19) , couldn't load eBPF programs, cs:&{map[.rodata:Array(keySize=4, valueSize=32, maxEntries=1, flags=128) active_ssl_read_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) bpf_context:LRUHash(keySize=8, valueSize=408, maxEntries=2048, flags=0) bpf_context_gen:Array(keySize=4, valueSize=408, maxEntries=1, flags=0) connect_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4152, maxEntries=1, flags=0) mastersecret_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) skb_data_buffer_heap:PerCPUArray(keySize=4, valueSize=40, maxEntries=1, flags=0) skb_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=8, flags=0) tls_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[egress_cls_func:0xc0005e4780 ingress_cls_func:0xc0005e4a00 probe_connect:0xc0005e4960 probe_entry_SSL_read:0xc0005e4820 probe_entry_SSL_write:0xc0005e4aa0 probe_ret_SSL_read:0xc0005e48c0 probe_ret_SSL_write:0xc0005e4b40 probe_ssl_master_key:0xc0005e4be0] 0xc0008ec6c0 LittleEndian}
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS module initialization
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS Module.Run()
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS HOOK type:2, binrayPath:/lib64/libgnutls.so.30
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS target all process. 
tls_2022/10/30 21:49:06 EBPFProbeGNUTLS module run failed, [skip it]. error:couldn't init manager error:program probe_entry_SSL_write: apply CO-RE relocations: can't read types: type id 6813: unknown kind: Unknown (19) , couldn't load eBPF programs, cs:&{map[.rodata:Array(keySize=4, valueSize=28, maxEntries=1, flags=128) active_ssl_read_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4144, maxEntries=1, flags=0) gnutls_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[probe_entry_SSL_read:0xc0005e5b80 probe_entry_SSL_write:0xc0005e5cc0 probe_ret_SSL_read:0xc0005e5c20 probe_ret_SSL_write:0xc0005e5720] 0xc000209500 LittleEndian}
tls_2022/10/30 21:49:06 EBPFProbeNSPR   module initialization
tls_2022/10/30 21:49:06 EBPFProbeNSPR   Module.Run()
tls_2022/10/30 21:49:06 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2022/10/30 21:49:06 EBPFProbeNSPR   HOOK type:2, binrayPath:/usr/lib/libnspr4.so
tls_2022/10/30 21:49:06 EBPFProbeNSPR   target all process. 
tls_2022/10/30 21:49:06 EBPFProbeNSPR   module run failed, [skip it]. error:couldn't init manager error:program probe_ret_SSL_write: apply CO-RE relocations: can't read types: type id 6813: unknown kind: Unknown (19) , couldn't load eBPF programs, cs:&{map[.rodata:Array(keySize=4, valueSize=28, maxEntries=1, flags=128) active_ssl_read_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4144, maxEntries=1, flags=0) nspr_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[probe_entry_SSL_read:0xc0005e4280 probe_entry_SSL_write:0xc0005e4d20 probe_ret_SSL_read:0xc0005e4c80 probe_ret_SSL_write:0xc0005e41e0] 0xc0008ec1e0 LittleEndian} 
tls_2022/10/30 21:49:06 EBPFProbeGoSSL  module [disabled].
tls_2022/10/30 21:49:06 ECAPTURE ::     No runnable modules, Exit(1)

运行时报错

**To Reproduce**
1. 下载或者编译好程序后
2. 执行 `sudo ./ecapture tls`

**Expected behavior**
可以正常运行

**Linux Server/Android (please complete the following information):**

- Env: 

```
---------------------------------------
eCapture Makefile Environment:
---------------------------------------
PARALLEL                 8
---------------------------------------
CLANG_VERSION            14
GO_VERSION               1.19
---------------------------------------
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
VERSION                  0.4.7-20221030-c0e990f
LAST_GIT_TAG             0.4.7-20221030-c0e990f
BPF_NOCORE_TAG           6_0_6-zen1-1-zen.0_4_7-20221030-c0e990f
---------------------------------------
UNAME_M                  x86_64
UNAME_R                  6.0.6-zen1-1-zen
ARCH                     x86_64
LINUX_ARCH               x86
---------------------------------------
KERN_RELEASE             6.0.6-zen1-1-zen
KERN_BUILD_PATH          /lib/modules/6.0.6-zen1-1-zen/build
KERN_SRC_PATH            /lib/modules/6.0.6-zen1-1-zen/build
---------------------------------------
GO_ARCH                  amd64
ANDROID                  
AUTOGENCMD               bpftool btf dump file /sys/kernel/btf/vmlinux format c > kern/bpf/x86/vmlinux.h
---------------------------------------
```

- OS: [Arch Linux x86_64]
- Arch: [amd64]
- Kernel Version: [6.0.6-zen1-1-zen]

**Additional context**

**Comment by cfc4n** [comment]
6.0的内核？没在这么新的内核上测试过。

**Comment by cfc4n** [comment]
你的内核是6.0的，6.0新增了一个BTF类型`kindEnum64 // Enum64`，ID为19。eCapture使用0.9.0的cilium/ebpf包。0.9.3的cilium/ebpf包里，BTF类型只有下面这些。
```go
// Equivalents of the BTF_KIND_* constants.
const (
	kindUnknown  btfKind = iota // Unknown
	kindInt                     // Int
	kindPointer                 // Pointer
	kindArray                   // Array
	kindStruct                  // Struct
	kindUnion                   // Union
	kindEnum                    // Enum
	kindForward                 // Forward
	kindTypedef                 // Typedef
	kindVolatile                // Volatile
	kindConst                   // Const
	kindRestrict                // Restrict
	// Added ~4.20
	kindFunc      // Func
	kindFuncProto // FuncProto
	// Added ~5.1
	kindVar     // Var
	kindDatasec // Datasec
	// Added ~5.13
	kindFloat // Float
	// Added 5.16
	kindDeclTag // DeclTag
	kindTypeTag // TypeTag
)
```
现在cilium的master分支上，已经有了这个BTF 类型，需要等cilium发布新版ebpf类库，eCapture才能修复这个问题。 或者你用5.x的内核。
