### ISSUE TITLE
About judging whether golang abi is register-based

### ISSUE THREAD

**Issue by Hackerl** [gojue/ecapture#262]
https://github.com/ehids/ecapture/blob/4c74089056dd2ec65b05665d021f6ba68055588a/user/module/probe_gossl.go#L43

golang uses register-based abi since 1.17(x64), minimum versions for other architectures require further confirmation.
Also, to read the version of golang binary, you can use [debug/buildinfo](https://github.com/golang/go/tree/master/src/debug/buildinfo).

**Comment by cfc4n** [comment]
Does it still exist while use `-ldflags "-s"` ?

**Comment by Hackerl** [comment]
".go.buildinfo" section exists in every golang binary above 1.13。

**Comment by cfc4n** [comment]
in golang 1.18 , `buildinfo.ReadFile` can get go Version. but eCapture used golang 1.17 now .  I'm still hesitating that keep use `elf.File.DWARF()` or update to 1.18 to use `buildinfo.ReadFile`. 
perhaps we can wating for new `Cilium/ebpf` version about #253  , then I will update golang new version for them.

```go 
bi, e := buildinfo.ReadFile(path)
if e != nil {
return nil, ErrVersionNotFound
}
fmt.Println(bi.GoVersion)
```

**Comment by cfc4n** [comment]
thanks for @Hackerl , It's fixed.

**Comment by cfc4n** [comment]
@Hackerl  可以加个VX技术交流一下吗？辛苦在「榫卯江湖」公众号里发个消息，我加你哈。
