### ISSUE TITLE
安卓adb连接并执行后报错

### ISSUE THREAD

**Issue by francisLee777** [gojue/ecapture#270]
![image](https://user-images.githubusercontent.com/30818378/202909975-78a684dd-86fc-44ba-9ef9-402a3175538f.png)

安卓模拟器版本 Linux localhost 4.19.195-android-x86_64-ga185d4b62926 #1 SMP PREEMPT Fri Nov 18 18:51:37 HKT 2022 x86_64

**Comment by cfc4n** [comment]
看着不像是eCapture的报错？   @jr981008 可以帮他看下吗？

**Comment by SeeFlowerX** [comment]
好像是在命令前面加了个`sh`，直接`./ecapture tls`这样执行试试

**Comment by cfc4n** [comment]
> 

细心，发现问题了。

**Comment by francisLee777** [comment]
> 

直接  ./ecapture tls 会显示权限不够，虽然 whoami 显示已经是 root 了， 所以我才用了 sh

**Comment by francisLee777** [comment]
换了一个模拟器也是一样的
![image](https://user-images.githubusercontent.com/30818378/203337901-d912641c-fc66-4a08-8c0e-6e9fcde5b529.png)


> 权限不够 chmod +x ecapture

**Comment by SeeFlowerX** [comment]
绝了，/sdcard下面不能执行任何bin文件

你最好在 /data/local/tmp 下面操作。。

**Comment by francisLee777** [comment]
> 绝了，/sdcard下面不能执行任何bin文件
> 
> 你最好在 /data/local/tmp 下面操作。。

这下...   我没有安卓手机，用的模拟器， MuMu 模拟器和夜神模拟器
![image](https://user-images.githubusercontent.com/30818378/203351963-50fda2f3-f4c8-4e4a-8a4b-537f5e9bdfbc.png)

**Comment by SeeFlowerX** [comment]
至少现在是可以正常执行了，至于失败，得请作者本人看看了

不过安卓内核4.19上应该也是没法读取用户内存数据的，所以只能pcapng抓数据，获取不到master key的

可以找找官方模拟器，应该有内核比较新的

**Comment by francisLee777** [comment]
> 

4.19 已经是最新的了， 模拟器不像真机一样版本那么高。 作者已经说大于 4.15 就可以运行。 另外感谢你的指导[送♥]

**Comment by francisLee777** [comment]
> 至少现在是可以正常执行了，至于失败，得请作者本人看看了
> 
> 不过安卓内核4.19上应该也是没法读取用户内存数据的，所以只能pcapng抓数据，获取不到master key的
> 
> 可以找找官方模拟器，应该有内核比较新的

4.19 已经是最新的了， 模拟器不像真机一样版本那么高。 作者已经说大于 4.15 就可以运行。 另外感谢你的指导[送♥]

**Comment by SeeFlowerX** [comment]
- https://github.com/newbit1/rootAVD

- https://forum.xda-developers.com/t/guide-build-mod-update-kernel-ranchu-goldfish-5-4-5-10-gki-ramdisk-img-modules-rootavd-android-11-r-12-s-avd-google-play-store-api.4220697/

![image](https://user-images.githubusercontent.com/70688581/203514982-e5afc681-7978-43a3-812b-b7c70dcc1241.png)

**Comment by francisLee777** [comment]
> 

奇怪，我这里是 x86_64 的安卓，不知道为什么文件格式不对。
![image](https://user-images.githubusercontent.com/30818378/203802057-27a24953-8842-4dc1-8ddd-5bfcbe7a51ef.png)

**Comment by cfc4n** [comment]
你的类库是32位的。不匹配

**Comment by francisLee777** [comment]
> 你的类库是32位的。不匹配

可是找不到其他 64 位的类库呀... 系统是 64 位的

**Comment by cfc4n** [comment]
> > 你的类库是32位的。不匹配
> 
> 可是找不到其他 64 位的类库呀... 系统是 64 位的

之前在B站发布过几篇使用方法视频，可以认真看下。  如果APP用的类库不是64位的，那确实不支持。
