### ISSUE TITLE
Pixel 5 caputre SSL result all be 0

### ISSUE THREAD

**Issue by BigChickenLegs** [gojue/ecapture#273]
**Describe the bug**
Pixel 5 caputre SSL result all be 0
Use ecapture-android-aarch64_nocore-v0.4.9

**To Reproduce**
./ecapture tls

**Expected behavior**

**Screenshots**
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/95196792/203680222-c574fce9-3ef7-4d32-93d9-39838cc7e10a.png">
<img width="825" alt="image" src="https://user-images.githubusercontent.com/95196792/203680299-6cbcad0e-97c8-45ed-9ff2-24ce2b2352d5.png">

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: 4.19
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**
check lib hook is right :
lsof -p 28690 | grep ssl 
/apex/com.android.conscrypt/lib64/libssl.so

**Comment by cfc4n** [comment]
minimal kernel version is 5.4 on ARM64 arch due  https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=6ae08ae3dea2cfa03dd3665a3c8475c2d429ef47

and 4.18 on X86_64

**Comment by BigChickenLegs** [comment]
I retest it on Android studio virtual Devices.
The Kernel version is 5.15 and BFT enable
use  ecapture-v0.4.9-android_core-aarch64
Nothing is output, chrome browses the web normally, and ecapture has no output.
<img width="878" alt="image" src="https://user-images.githubusercontent.com/95196792/203910945-eb387e7a-7853-4ee2-a287-c507838cf23e.png">

**Comment by cfc4n** [comment]
please check that which libssl.so the app used.  

```shell
lsof -p $PID |grep libssl.so
```

**Comment by BigChickenLegs** [comment]
> libssl

I have check it 
/apex/com.android.conscrypt/lib64/libssl.so
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/95196792/203960422-7b9a6396-fec8-4068-be44-705cf6431867.png">

or should not I capture the chrome?

**Comment by cfc4n** [comment]
I'm not sure.  maybe chrome have many ssl libraries. it is static build another one .

could you test it use other app ?

**Comment by Odinbk** [comment]
我也遇到了同样的情况，环境是Pixel6。 其他应用比如知乎是可以抓到数据的，但是Chrome不行。  @cfc4n 能否指导一下？

**Comment by cfc4n** [comment]
看公众号的视频吧。 都讲过原理的，照着做就行。 笔者太忙了。

**Comment by Odinbk** [comment]
> 看公众号的视频吧。 都讲过原理的，照着做就行。 笔者太忙了。

好的，我先看文档试试。
