### ISSUE TITLE
扩展时运行时报错

### ISSUE THREAD

**Issue by CSecurityZhongYuan** [gojue/ecapture#278]
当我尝试对ecapture进行扩展的时候遇到了一些问题。

编译过之后加载ebpf的.o文件时校验出错。是莫名其妙的错，我在bcc里面测试过没问题的一段代码，放到这里总会出错。
我怀疑是编译选项的问题，这个问题能解决吗，感谢

**Comment by cfc4n** [comment]
建议你多学一些ebpf知识，借助BCC迁移到eCapture扩展的实现，可以加强一些知识的理解。 更好的掌握技术。
