### ISSUE TITLE
-w保存为pcapng格式文件时显示 save 0 packets into pcapng file.

### ISSUE THREAD

**Issue by 2962816128** [gojue/ecapture#280]
当我使用AVD模拟器的时候，使用最新的x86-64的ecapture，使用./ecapture tls能够很明显的看见抓的到包，但是当我./ecapture tls -w test.pcapng的时候，最后的输出是这样的：
tls_2022/12/08 10:00:48 TLS1_2_VERSION: save CLIENT_RANDOM 786cc517da567e2c224345d34cde9b1eff101a0b62a03784664a4efe0ef4479a to file success, 176 bytes
tls_2022/12/08 10:00:51 TLS1_2_VERSION: save CLIENT_RANDOM 42627d4f1ef118f4b3b471975f4f6f76d6545d137ffc39f1c741547f9e8ad6ef to file success, 176 bytes

^Ctls_2022/12/08 10:00:53 EBPFProbeOPENSSL      saving pcapng file /data/local/tmp/aito.pcapng
tls_2022/12/08 10:00:53 EBPFProbeOPENSSL         **save 0 packets into pcapng file.**关键就是这里，然后pcapng文件中什么都没有
tls_2022/12/08 10:00:53 EBPFProbeOPENSSL        close.
tls_2022/12/08 10:00:53 EBPFProbeOPENSSL        close.

**Comment by 1190300107** [comment]
我也遇到这个问题了，我是android12，已经解决了，可能是网卡选择的问题。
你试试Ifconfig一下列出网卡,可能会有lo,dummy0,etho0,wlan0,
然后 ./ecapture tls -i etho0   -w file.pcapng 试试，或者上面四个都试试。

**Comment by 2962816128** [comment]
> 

好，我去试试

**Comment by 2962816128** [comment]
> 

thanks，./ecapture tls -i eth0 -w test.pcapng
