### ISSUE TITLE
  나는 사용할 줄 모른다. 튜토리얼이 너무 짧다 

### ISSUE THREAD

**Issue by umena337** [gojue/ecapture#281]
나는 사용할 줄 모른다. 튜토리얼이 너무 짧다

**Comment by chriskaliX** [comment]
Hi, umena. There are several ways that you can learn how to use eCapture.
1. Follow the README.md doc
2. [User Manual vedio](https://www.youtube.com/watch?v=CoDIjEQCvvA) or some other videos like [video-1](https://www.youtube.com/watch?v=Au1YeB0nz3g) and [video-2](https://www.youtube.com/watch?v=KX8-hsM1tg4)
3. Read the manual from `--help` and have some tests

If you can read Chinese,Join QQ Group for better communication.(群号码在微信公众号里)
