### ISSUE TITLE
ecapture能支持像tcpdump一样的过滤规则包语法吗

### ISSUE THREAD

**Issue by boost2020** [gojue/ecapture#282]
**Describe the bug**

VERSION:
	linux_x86_64:0.4.10-20221211-3a46b62:[CORE]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by cfc4n** [comment]
In the next two years, it is not in the plan. I do not expect eCapture to be as complex and large as tcpdump, and hope that eCapture is a supplement to tcpdump.

---------------------

未来2年内，不在计划中。我不期望eCapture做的跟tcpdump一样复杂庞大，希望eCapture是tcpdump的一个补充
