### ISSUE TITLE
bug: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by luckymrwang** [gojue/ecapture#287]
**Describe the bug**
configure --gobin="xxx" 
When capturing go app, it reports panic: invalid memory address or nil pointer

**To Reproduce**
1. ./ecapture tls -i enp0s5 -w pcapng.pcap --port=443 --gobin="xxxx"
2. runing go app
3. ecapture is stopped by panic

**Expected behavior**
support gobin completely

**Screenshots**
![WX20230106-154752](https://user-images.githubusercontent.com/8869360/210954886-93291869-c6f3-4312-8725-ce669da3d1eb.png)

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [Ubuntu 21.04]
- Arch: [amd64]
- Kernel Version: [5.15]
- Version: [5.15.0-56-generic]

**Comment by cfc4n** [comment]
thanks .

but ecapture do not supported capture master key and capture decrypted network packets on `gobin`. only support capture plaintext on `gobin`.   

maybe supported in the future.
