### ISSUE TITLE
Android系统内核x86_64 4.18 

### ISSUE THREAD

**Issue by darknight-666** [gojue/ecapture#289]
请问   哪款手机 是 Android系统内核x86_64 4.18？

**Comment by cfc4n** [comment]
我不清楚，你可以使用Android studio模拟器测试。

**Comment by SeeFlowerX** [comment]
现在应该没有用x86的手机吧...

不过mumu模拟器Android 12版本的，是可以使用ecapture抓包的，内核是4.19

**Comment by cfc4n** [comment]
ping?
