### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by 5dxj8** [gojue/ecapture#297]
gobin模式

panic: runtime error: slice bounds out of range [:24958] with length 4096

goroutine 16 [running]:
ecapture/user/event.(*GoSSLEvent).String(0xc0001da690)
        /home/runner/work/ecapture/ecapture/user/event/event_gossl.go:29 +0x12d
ecapture/user/module.(*Module).Dispatcher(0xc0000c0630, {0x97a1b8, 0xc000bd5300})
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:298 +0xfd
ecapture/user/module.(*Module).perfEventReader.func1()
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:231 +0x2eb
created by ecapture/user/module.(*Module).perfEventReader
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:199 +0x1a5

**Comment by cfc4n** [comment]
what's the reproduce steps, what's your env?

**Comment by cfc4n** [comment]
@5dxj8 fixed, please try again.

**Comment by 5dxj8** [comment]
panic: runtime error: slice bounds out of range [:2904] with capacity 0

goroutine 66 [running]:
ecapture/user/event.(*GoSSLEvent).StringHex(0x0?)
        /root/ecapture/user/event/event_gossl.go:44 +0x1af
ecapture/user/module.(*Module).Dispatcher(0xc00011a630, {0x9e09a0, 0xc0000a03c0})
        /root/ecapture/user/module/imodule.go:296 +0xb4
ecapture/user/module.(*Module).perfEventReader.func1()
        /root/ecapture/user/module/imodule.go:231 +0x2da
created by ecapture/user/module.(*Module).perfEventReader
        /root/ecapture/user/module/imodule.go:199 +0x19e

**Comment by 5dxj8** [comment]
panic: runtime error: slice bounds out of range [:31] with capacity 0

goroutine 51 [running]:
ecapture/user/event.(*GoSSLEvent).String(0x0?)
        /root/ecapture/user/event/event_gossl.go:38 +0x119
ecapture/user/module.(*Module).Dispatcher(0xc000112840, {0x9e09a0, 0xc00020abc0})
        /root/ecapture/user/module/imodule.go:298 +0xfd
ecapture/user/module.(*Module).perfEventReader.func1()
        /root/ecapture/user/module/imodule.go:231 +0x2da
created by ecapture/user/module.(*Module).perfEventReader
        /root/ecapture/user/module/imodule.go:199 +0x19e

**Comment by cfc4n** [comment]
Could you give the step to reproduce the behavio?

**Comment by 5dxj8** [comment]
#https://github.com/ginuerzh/gost
gost -L=tls://:8080
ecapture tls --hex --gobin=./gost

**Comment by cfc4n** [comment]
cannot reproduce.

**Comment by 5dxj8** [comment]
#server
gost -L=:8080
ecapture tls --hex --gobin=./gost

#client browser setting proxy server:8080
request  https website

**Comment by cfc4n** [comment]
>  client browser setting proxy server:8080

is it a socks5 proxy?

and what's the app used to request https website?  chrome ? curl ?
