### ISSUE TITLE
Ecapture  does not work in pcapng mode on openEuler.

### ISSUE THREAD

**Issue by RyanCode** [gojue/ecapture#300]
## what?
I use ecapture to capture the rdp protocol flow to analyze the protocol details, but the packets captured in the pcapng mode are incomplete.
--
### ecapture version
linux_x86_64:0.4.11-20230107-7b66305:5.15.0-1023-azure

###  arch and os 
Linux localhost.localdomain 5.10.0-106.18.0.68.oe2209.x86_64 #1 SMP Wed Sep 28 07:03:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

And I checked the kernel's support for btf debug
![image](https://user-images.githubusercontent.com/61410262/215260749-58bfee07-c54d-4366-b507-21a92ba72d88.png)

### freerdp
U can download freerdp、Xvnc directly using yum:
```shell
yum install freerdp tigervnc-server
```
run Xvnc
Xvnc :0 -rfbport 5900 -depth 24 -SecurityTypes None -pixelformat RGB888
run xfreerdp
DISPLAY=:0 xfreerdp -u foo --sec nla -v 192.168.1.8 -p bar
and ecapture
./ecapture tls -i foo --port 3389 --hex -w rdp.pcapng

**Comment by chriskaliX** [comment]
Could you please provide some details of the pcapng file. I've tested in my ubuntu 22.04 with ecapture opened, which seems works well...
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/46471110/216758431-760c0cb3-4661-47cc-bfe9-b933a4fc3016.png">

**Comment by RyanCode** [comment]
> 



> Could you please provide some details of the pcapng file. I've tested in my ubuntu 22.04 with ecapture opened, which seems works well... <img alt="image" width="1032" src="https://user-images.githubusercontent.com/46471110/216758431-760c0cb3-4661-47cc-bfe9-b933a4fc3016.png">

wireshark can not open this file,file format maybe wrong. cat like:
```pcapng
�M<+��������
            ecapture.luaHsee https://ecapture.cc for more information. CFC4N <cfc4n.cs@gmail.com>eCapture Hardware�`��ens192/eCapture (旁观者): github.com/gojue/ecapture    `\��lo/eCapture (旁观者): github.com/gojue/ecapture              \`��ens192/eCapture (旁观者): github.com/gojue/ecapture         `
$KSLTCLIENT_RANDOM 3f1875bde5f56b1b264c7c461ef3a127a656dc0a56a6356d7a0e2f4702eaaeca 560b52cab00dfb95ef2a1e2938ca06b133fab34fcdf4c6edeb6ee400c86915fc6253fb47263085cb9cbf545d3972d996
CLIENT_RANDOM a330e461fb848806ddbfdab70fc6dbb2b2cfc6704d961bcd02a93f234e37df9b 333ba1c150300af43d95d457fca20cbdcaa0ee2fbe379e219025764261b691c934258d93ce725f9d087f1518f68c3d3b
CLIENT_RANDOM d410d9ea509db4194ad74fda7742760628179eeaa9a4bf77ba9d9ccaa722684b 3b07b24b336b995d89999e828378423e8d96e4c6a59698679b48b669b84ab5785e4c7b3108ecba67313fdccca551593f
```

**Comment by chriskaliX** [comment]
Got it. I'll try this again on openEuler.

**Comment by chriskaliX** [comment]
Problem is solved. To solve this, just compile the ecapture from source, where the vmlinux.h will be generated.
