### ISSUE TITLE
如何从打印的信息里获得IP信息

### ISSUE THREAD

**Issue by cq1982** [gojue/ecapture#303]
我看到capture_packets里有获取到，但后续好像没有传值，想问问怎么才能在parserEvent或Display的时候取到？
// IP headers
struct iphdr *iph = (struct iphdr *)(data_start + sizeof(struct ethhdr));

**Comment by cfc4n** [comment]
after https://github.com/gojue/ecapture/blob/c1d88ea629d58add5143632b771697a74f016a56/user/module/probe_openssl_tc.go#L213

add 
```go
tmpPacket := gopacket.NewPacket(tcEvent.Payload(),layers.LayerTypeEthernet,
		gopacket.Default)
// something you want ,allin tmpPacket
```

**Comment by cq1982** [comment]
我试试，非常感谢

**Comment by cq1982** [comment]
我试了一下pkg/event_processor/iworker.go的Display()里
加上
tmpPacket := gopacket.NewPacket(this.payload, layers.LayerTypeEthernet, gopacket.Default)
srcIP := tmpPacket.Layer(layers.LayerTypeIPv4).(*layers.IPv4).SrcIP

输出报错：
panic: interface conversion: gopacket.Layer is nil, not *layers.IPv4

猜想是否在capture_packets的
bpf_perf_event_output(skb, &skb_events, flags, &event, pkt_size);
时就没有传完整的payload字节呢？

**Comment by cq1982** [comment]
然后[probe_openssl_tc.go里加ip转换，日志没有任何输出信息

**Comment by cq1982** [comment]
这个地方我看到有一个TODO，但是打开会报循环依赖
func (this *SSLDataEvent) StringHex() string {
	//addr := this.module.(*module.MOpenSSLProbe).GetConn(this.Pid, this.Fd)

	addr := "[TODO]"

**Comment by cfc4n** [comment]
eCapture的tls模块捕获结果有两种模式
1. 文本模式
2. pcapng模式

`capture_packets`拿到的流量信息，是pcapng模式的数据。
`parserEvent` 跟 `Display`是文本模式的功能。

文本模式不支持TLS数据的IP提取。

建议你自己阅读代码，再根据自己的需求做调整。

**Comment by cq1982** [comment]
好的，非常感谢

**Comment by cq1982** [comment]
我找到这个
