### ISSUE TITLE
关于调试一个golang程序

### ISSUE THREAD

**Issue by qptrello** [gojue/ecapture#304]
ldd bin/Go 
        not a dynamic executable

 ./ecapture tls
tls_2023/02/05 09:25:23 ECAPTURE :: ecapture Version : linux_x86_64:0.4.11-20230107-7b66305:5.15.0-1023-azure
tls_2023/02/05 09:25:23 ECAPTURE :: Pid Info : 19480
tls_2023/02/05 09:25:23 ECAPTURE :: Kernel Info : 5.4.218
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        module initialization
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        master key keylogger: ecapture_masterkey.log
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        Module.Run()
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        UPROBE MODEL
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        origin version:OpenSSL 1.1.1f, as key:openssl 1.1.1f
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/lib/x86_64-linux-gnu/libssl.so.1.1
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        Hook masterKey function:SSL_write
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        target all process. 
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        target all users. 
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/openssl_1_1_1d_kern.o
tls_2023/02/05 09:25:23 EBPFProbeOPENSSL        module started successfully.
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS module initialization
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS Module.Run()
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS HOOK type:2, binrayPath:/lib/x86_64-linux-gnu/libgnutls.so.30
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS target all process. 
tls_2023/02/05 09:25:23 EBPFProbeGNUTLS module started successfully.
tls_2023/02/05 09:25:23 EBPFProbeNSPR   module initialization
tls_2023/02/05 09:25:23 EBPFProbeNSPR   Module.Run()
tls_2023/02/05 09:25:23 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2023/02/05 09:25:23 EBPFProbeNSPR   HOOK type:2, binrayPath:/lib/x86_64-linux-gnu/libnspr4.so
tls_2023/02/05 09:25:23 EBPFProbeNSPR   target all process. 
tls_2023/02/05 09:25:23 EBPFProbeNSPR   module started successfully.
tls_2023/02/05 09:25:23 EBPFProbeGoSSL  module [disabled].
tls_2023/02/05 09:25:23 ECAPTURE ::     start 3 modules

怎么都抓不到，麻烦请教过程，官方文档也是空的，我在代码看到了相关抓取golang tls的代码，请教如何使用

**Comment by qptrello** [comment]
EBPFProbeGoSSL module [disabled]. 
这里被关闭了

**Comment by cfc4n** [comment]
> EBPFProbeGoSSL module [disabled]. 
> 
> 这里被关闭了
> 
> 
> 
>  --gobin="/home/https_client"  增加这个参数后 module initialization failed, [skip it]. error:decoding dwarf section info at offset 0x0: too short
> 
> 
> 
>  --gover=go1.18 增加版本参数，提示为未找到参数

https_client的源码、编译参数是什么？

**Comment by yllhwa** [comment]
Just have a look at #120 .
ecapture can't deal with stripped golang app.

**Comment by cfc4n** [comment]
@qptrello 如 @yllhwa  所述，eCapture 依赖调试的DWARF端来定位HOOK的函数地址。  strip后的go elf无法定位。 建议你编译时，保留DWARF段，或者自助定位被HOOK函数的Offset，手动设定到eCapture里，自行魔改实现hook。
