### ISSUE TITLE
Missing masterkey file. Just TCP/TLS packets in wireshark, no HTTP/S

### ISSUE THREAD

**Issue by wherebrain** [gojue/ecapture#307]
The masterkey file is not written. Can't see HTTP/HTTPS packets of pcapng file in wireshark.  Just TCP and TLS packets are visible in wireshark.
I tried Ubuntu 20.05 with openssl 1.1.1f and Ubuntu 22.04 with openssl 3.0.3

**Screenshots**
Ubuntu 22.04:
![image](https://user-images.githubusercontent.com/124807828/217599930-d9de2c96-577f-450a-a643-5793b747a81f.png)

Ubuntu 20.05:
![image](https://user-images.githubusercontent.com/124807828/217600484-ee18e76a-3765-4e02-9872-b030f19d9903.png)

How to get the HTTP/S data?
Thanks in advance

**Comment by cfc4n** [comment]
please confirm that the client of the HTTPS request has used the ecapture hook's so library.

**Comment by cfc4n** [comment]
you can used `curl https://github.com` to tests on ubuntu 20.04.

**Comment by wherebrain** [comment]
> you can used `curl https://github.com` to tests on ubuntu 20.04.

Using curl the masterkey is written. How could I get the the browsers working?

**Comment by cfc4n** [comment]
You need to confirm which tls class library your browser used. 
```shell
sudo pldd $PID | grep -E "tls|ssl|nspr|nss"
```

and  see `./ecapture tls -h` for more detail.

**Comment by wherebrain** [comment]
I already identified the classes in my first screenshots with both machines and put them into the --nspr flag. 
`sudo ./ecapture tls --nspr /usr/lib/firefox/libnspr4.so`

![image](https://user-images.githubusercontent.com/124807828/218118784-e88fd7d3-65ff-4616-9aa4-8a87a83746dd.png)

**Comment by cfc4n** [comment]
> 

upload the shell result.
```shell
ps -ef|grep ${YOUR BROWSER}
sudo pldd $PID | grep -E "tls|ssl|nspr|nss"
```

**Comment by wherebrain** [comment]
![image](https://user-images.githubusercontent.com/124807828/218126741-023ed45a-6ea4-4b58-a906-b93e159fdde9.png)

**Comment by cfc4n** [comment]
in your screenshot, The tls lib path is `/usr/lib/firefox/libnspr4.so` which firefox used.  it not equal to `/snap/firefox/1635/usr/lib/firefox/libnpr4.so` from your first screenshot.

please try again with `./ecapture tls --nspr=/usr/lib/firefox/libnspr4.so`

see https://www.cnxct.com/what-is-ecapture/ for more `firefox/chrome` tips if you can read Chinese.
However, the content of this article is a bit old.

**Comment by wherebrain** [comment]
> in your screenshot, The tls lib path is `/usr/lib/firefox/libnspr4.so` which firefox used. it not equal to `/snap/firefox/1635/usr/lib/firefox/libnpr4.so` from your first screenshot.
> 
> please try again with `./ecapture tls --nspr=/usr/lib/firefox/libnspr4.so`
> 
> see https://www.cnxct.com/what-is-ecapture/ for more `firefox/chrome` tips if you can read Chinese. However, the content of this article is a bit old.

First screenshot is the Ubuntu22.04 vm. The path is different there. If you look at the second screenshot, I got the path right there.

I already looked at that article on the wechat https://mp.weixin.qq.com/s/DvTClH3JmncpkaEfnTQsRg. But could'nt find the issue.

Did you got it running with the masterkey and browser (firefox or chrome)?

**Comment by wherebrain** [comment]
Identifying firefox $PID
![image](https://user-images.githubusercontent.com/124807828/218137070-d37ee101-c1e6-4210-90b4-becd755f09f7.png)

Checking firefox tls library path
![image](https://user-images.githubusercontent.com/124807828/218137504-d54d4bd3-ad25-4a43-b50e-2a2ba55bfc30.png)

Inserting information in the flags ->
`./ecapture tls --nspr=/usr/lib/firefox/libnspr4.so`
But masterkey.log file is not written  to.

I'm gonna try it with chrome next.

**Comment by cfc4n** [comment]
eh, I found the problem that eCapture  is not supported capture master secrets for nspr/nss yet. 

😅
