### ISSUE TITLE
about ecapture_masterkey.log format 日志文件解读

### ISSUE THREAD

**Issue by kernelhe** [gojue/ecapture#309]
提一个小问题，README 里可以对日志文件的内容做个介绍吗，比如我获取到了下面的密钥信息，但是有两串数字，这两串数字都是密钥吗，或者第一串数字代表什么意思，第二串数字代表什么意思，对于新手不太了解这两串数字的含义，感谢
> # cat ecapture_masterkey.log                                                                  [±master ●]
CLIENT_HANDSHAKE_TRAFFIC_SECRET 37fac1856acd679e92dadb31baf345ad57761b2be62a7f70ca711508f2ace692 5e17801a3a2808692c28a3bc07d9e7005b5b5f15f4dd5dcd0eb81bc46a040d67
SERVER_HANDSHAKE_TRAFFIC_SECRET 37fac1856acd679e92dadb31baf345ad57761b2be62a7f70ca711508f2ace692 a31063deb05a82f3cfc78519fb2b2a32a8b22ed420266cd0e811365616235aa5
CLIENT_TRAFFIC_SECRET_0 37fac1856acd679e92dadb31baf345ad57761b2be62a7f70ca711508f2ace692 03e86a2f1225528411f0dc0b21e73b08d03af7b25062d8a09848f4b53b4d72cf0000000000000000000000000000000000000000000000000000000000000000
SERVER_TRAFFIC_SECRET_0 37fac1856acd679e92dadb31baf345ad57761b2be62a7f70ca711508f2ace692 4b80b464d6c5fa0f8453e940bb107e96e7c7635fd69d4b28dcef60aebb2373e50000000000000000000000000000000000000000000000000000000000000000
EXPORTER_SECRET 37fac1856acd679e92dadb31baf345ad57761b2be62a7f70ca711508f2ace692 0345cfd4f84ffa135baf5c1be58e7b4b81ac3eb367821cc99b6cd8ac46f44aed

**Comment by cfc4n** [comment]
`ecapture_masterkey.log` is not a log file.  It's a `Master Secret` key log file.   

use `-l` flag to set logfile which path you want. 

see [`https://wiki.wireshark.org/TLS`](https://wiki.wireshark.org/TLS)  for more detail.
