### ISSUE TITLE
MuMu 模拟器X beta 使用ecapture报错

### ISSUE THREAD

**Issue by Daikq** [gojue/ecapture#312]
panic: runtime error: slice bounds out of range [:28849] with length 48

goroutine 25 [running]:
ecapture/user/module.(*MOpenSSLProbe).saveMasterSecretBSSL(0xc00013ab00, 0xc0003fe000)
        /home/runner/work/ecapture/ecapture/user/module/probe_openssl.go:620 +0xb7f
ecapture/user/module.(*MOpenSSLProbe).Dispatcher(0x0?, {0x9ec258?, 0xc0003fe000?})
        /home/runner/work/ecapture/ecapture/user/module/probe_openssl.go:716 +0x18f
ecapture/user/module.(*Module).Dispatcher(0xc00013ab00, {0x9ec258, 0xc0003fe000})
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:304 +0x87
ecapture/user/module.(*Module).perfEventReader.func1()
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:231 +0x2da
created by ecapture/user/module.(*Module).perfEventReader
        /home/runner/work/ecapture/ecapture/user/module/imodule.go:199 +0x19e

使用的 [ecapture-v0.4.12-android-x86_64.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.4.12/ecapture-v0.4.12-android-x86_64.tar.gz)

**Comment by HorseLuke** [comment]
安卓版本是12的话，考虑是这个链接的问题，按照这个修改来重新编译一份试试：https://github.com/gojue/ecapture/discussions/310
