### ISSUE TITLE
tls 正常工作，但无法转储

### ISSUE THREAD

**Issue by francisLee777** [gojue/ecapture#317]
tls 正常运行输出在控制台。但 -w 转储报错
./ecapture tls -i eth0 -w pcapng -p 443
其中 eth0 是 ifconfig 显示的本机网卡。
![F$@I3{GR7)$NJ63F JGT4WJ](https://user-images.githubusercontent.com/30818378/220702825-6efc8d21-327b-4705-8935-86e21975f01a.png)

**Comment by cfc4n** [comment]
what's your OS version? device info? steps? or other env?

**Comment by cfc4n** [comment]
I have not Win11 device and can't reproduce it.

Anybody can help me?

**Comment by cfc4n** [comment]
or you can try again on Android Studio emualtor.. and use android kernel 5.5 or higher..

**Comment by francisLee777** [comment]
> 
 
good idea， let me try to use Android Studio emualtor

**Comment by SeeFlowerX** [comment]
会不会是执行路径的问题，换到 /data/local/tmp 下执行呢（而且你这个路径有空格）

**Comment by ryanlycch** [comment]
同样问题，archlinux, kernel 6.1.2
1. 加-w参数，不带-i参数，错误

/tmp> sudo ecapture tls --hex -w /tmp/git.pcap
tls_2023/03/13 15:24:37 ECAPTURE :: ecapture Version : linux_x86_64:0.5.0-20230310-9f8b931:[CORE]
tls_2023/03/13 15:24:37 ECAPTURE :: Pid Info : 3574649
tls_2023/03/13 15:24:37 ECAPTURE :: Kernel Info : 6.2.1
tls_2023/03/13 15:24:37 EBPFProbeOPENSSL	module initialization
tls_2023/03/13 15:24:37 EBPFProbeOPENSSL	Module.Run()
tls_2023/03/13 15:24:37 EBPFProbeOPENSSL	TC MODEL
tls_2023/03/13 15:24:37 EBPFProbeOPENSSL	**module run failed, [skip it]. error:route ip+net: no such network interface**


2. 同时加-w和-i参数，错误如下：

tls_2023/03/13 15:26:15 ECAPTURE :: ecapture Version : linux_x86_64:0.5.0-20230310-9f8b931:[CORE]
tls_2023/03/13 15:26:15 ECAPTURE :: Pid Info : 3575427
tls_2023/03/13 15:26:15 ECAPTURE :: Kernel Info : 6.2.1
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	module initialization
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	Module.Run()
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	TC MODEL
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found from shared library file, used default version:linux_default_3_0
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/lib64/libssl.so.3
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	Ifname:enp2s0, Ifindex:2,  Port:443, Pcapng filepath:/tmp/t.pcap
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	Hook masterKey function:SSL_write
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	target all process. 
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	target all users. 
tls_2023/03/13 15:26:15 EBPFProbeOPENSSL	BPF bytecode filename:user/bytecode/openssl_3_0_0_kern.o
tls_2023/03/13 15:26:16 EBPFProbeOPENSSL	** module run failed, [skip it]. error:couldn't start bootstrap manager error:2 errors occurred:
	* error:error:netlink receive: no such file or directory , couldn't add a ", err clsact" qdisc to interface 2, {UID:, EbpfFuncName:egress_cls_func}
	* error:error:netlink receive: no such file or directory , couldn't add a ", err clsact" qdisc to interface 2, {UID:, EbpfFuncName:ingress_cls_func}

, probes activation validation failed . **

3. 不加-w时带不带-i参数都是正常的
