### ISSUE TITLE
安卓11用哪个版本呢

### ISSUE THREAD

**Issue by babaloveyou** [gojue/ecapture#318]
eCapture v0.22开始支持android5.5内核，所以换了0.2.1写着4.18+

我的手机内核版本Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64
版本号大于4.18为什么不支持呢？

错误：
taimen:/data/local/tmp $ ./ecapture
2023/02/25 11:57:53 Linux Kernel version 4.4.223 is not supported. Need > 4.18

**Comment by cfc4n** [comment]
Android aarch64版本，是需要5.5以上内核，才能完全正常运行。  4.18以上内核也能运行，不过，拿不到完整的流量内容。 是因为 aarch64 kernel 有个bug，可以看下 #296 。


如果你自己编译android的话，可以自己打补丁，参考 https://github.com/gojue/ecapture/discussions/308

**Comment by cfc4n** [comment]
ping?
