### ISSUE TITLE
bug: gotls crash

### ISSUE THREAD

**Issue by aloooha** [gojue/ecapture#322]
https://github.com/gojue/ecapture/blob/3a813ac5b86b068b7654afad4386b24c9b27a62f/user/event/event_gotls.go#L23-L35

The variable e was used incorrectly(Line 26) during exception handling, causing the data of GoTLSEvent to be empty, and an exception occurred during recording

**Comment by cfc4n** [comment]
Can you provide the complete steps to reproduce the issue?

**Comment by cfc4n** [comment]
I see.  I will send a PR ,thanks.
