### ISSUE TITLE
If the program is fully statically compiled, is there still a way to obtain TLS plaintext? For example, if I know the addresses of ssl_write and ssl_read.

### ISSUE THREAD

**Issue by WinMin** [gojue/ecapture#327]
If the program is fully statically compiled, is there still a way to obtain TLS plaintext? For example, if I know the addresses of ssl_write and ssl_read.

**Comment by cfc4n** [comment]
config the address at https://github.com/gojue/ecapture/blob/07a01a91c35e0c2f7f3ef2be95afdeb1586a8a9c/user/module/probe_openssl.go#L314

like that:
```go
{
    Section:          "uretprobe/SSL_write",
    EbpfFuncName:     "probe_ret_SSL_write",
    AttachToFuncName: "SSL_write",
    BinaryPath:       binaryPath,
    UprobeOffset: 0x1111111, // set values here...
},
```
and recompile it.

**Comment by cfc4n** [comment]
ping? @WinMin
