### ISSUE TITLE
using -w and -i can't get any data

### ISSUE THREAD

**Issue by gophernancy** [gojue/ecapture#339]
**Describe the bug**
When I use "./ecapture gotls -e=/root/zn/itim_plugin/test-client/main -w=save.pcapng -i ens160", I can't get any monitor data in save.pcapng.

**To Reproduce**
1. start my go app.
2. start ecapture
3. request my go app using postman
4. download save.pcapng, see this file in wireshark

**Expected behavior**
I want to get request ip, request path, request data, reponse ip, response data.

**Screenshots**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/3292071/227834179-877cdbdc-aef6-403a-bd7c-924b685b9487.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/3292071/227834219-17f02f45-b35f-45b5-ae8d-0c034074d043.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/3292071/227834414-6eed8027-4f72-41ff-8ec5-d5e87a439641.png">

![image](https://user-images.githubusercontent.com/3292071/227834233-836678f5-919d-40d1-b532-77742666f09a.png)

**Linux Server/Android (please complete the following information):**

- Env: 
- OS: Linux version 4.18.0-348.7.1.el8_5.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)) #1 SMP Wed Dec 22 13:25:12 UTC 2021
- go 1.20.2

**Comment by cfc4n** [comment]
The port you are using is not the default 443, but rather 8087. You need to set the listening port. This can be done by using the `--port` parameter.

If you are using a kernel system below version 5.2, then it does not support specifying the `--port` parameter through command line and you will need to modify the source code and recompile.

See https://github.com/gojue/ecapture/blob/fe4a76d76487ef2b66d171a188a5e9453d4baba7/cli/cmd/gotls.go#L51
---
你使用的端口，不是默认的443，而是8087，需要设定监听的端口。可以通过`--port`参数设定。

如果你使用的是5.2一下内核系统，那么，是不支持通过命令行来指定`--port`参数的，你需要自行更改源码，重新编译。

见 https://github.com/gojue/ecapture/blob/fe4a76d76487ef2b66d171a188a5e9453d4baba7/cli/cmd/gotls.go#L51
