### ISSUE TITLE
Kernel config read failed, error:Config not found,  item:CONFIG_UPROBES.

### ISSUE THREAD

**Issue by AntonioShare** [gojue/ecapture#351]
Kernel config read failed, error:Config not found,  item:CONFIG_UPROBES.

- OS: [HarmonyOS 3]
- Arch: [arm_aarch64]
- Kernel Version: [5.10.43]
- Version: [v0.5.1]

**Comment by cfc4n** [comment]
Your kernel has not enabled uprobe. You need to enable this parameter and recompile the kernel.
`CONFIG_UPROBES=y`


ref:https://docs.kernel.org/trace/uprobetracer.html

**Comment by AntonioShare** [comment]
> Your kernel has not enabled uprobe. You need to enable this parameter `CONFIG_UPROBES=y` and recompile the kernel.
> 
> ref:https://github.com/iovisor/bcc/blob/master/INSTALL.md#kernel-configuration

I see. But mainly, I can't modify the kernel compilation configuration of HarmonyOS 3. I mean, is there any other way to use it?

**Comment by cfc4n** [comment]
Sorry, there is no way to support it. It must be necessary to enable this parameter in the kernel.
