### ISSUE TITLE
using -w and -i can't get pcap file in tls mode

### ISSUE THREAD

**Issue by ShipeiXu** [gojue/ecapture#353]
**Describe the bug**
the server(dns of https) and the client is in the same host.
./ecapture tls -w ./save_3_0_5.pcapng  -i lo --port 3333. (client port)
or 
 ./ecapture tls -w ./save_3_0_5.pcapng  -i lo --port 443 （server port）

**To Reproduce**
1.  ./ecapture tls -w ./save_3_0_5.pcapng  -i lo --port 443
2. kdig -b 127.0.0.1#3333  @127.0.0.1 www.baidu.com +https

**Expected behavior**
Get the save_3_0_5.pcapng file under the ecapture path

**Screenshots**
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/3360832/233833678-f37f0bf9-86ff-441f-9f25-ebf7f19e11b7.png">

**Linux Server/Android (please complete the following information):**

rocky linux,
```shell
[root@localhost bin]# cat /etc/redhat-release
Rocky Linux release 9.1 (Blue Onyx)
[root@localhost bin]# uname -r
5.14.0-162.23.1.el9_1.x86_64
```
- Env: [run `make env` to get the environment variables]

```text
---------------------------------------
eCapture Makefile Environment:
---------------------------------------
PARALLEL                 4
---------------------------------------
CLANG_VERSION            14
GO_VERSION               1.19
---------------------------------------
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
VERSION                  0.5.1-20230416-f0ec428
LAST_GIT_TAG             0.5.1-20230416-f0ec428
BPF_NOCORE_TAG           5_14_0-162_23_1_el9_1_x86_64.0_5_1-20230416-f0ec428
---------------------------------------
UNAME_M                  x86_64
UNAME_R                  5.14.0-162.23.1.el9_1.x86_64
ARCH                     x86_64
LINUX_ARCH               x86
---------------------------------------
KERN_RELEASE             5.14.0-162.23.1.el9_1.x86_64
KERN_BUILD_PATH          /lib/modules/5.14.0-162.23.1.el9_1.x86_64/build
KERN_SRC_PATH            /lib/modules/5.14.0-162.23.1.el9_1.x86_64/source
---------------------------------------
GO_ARCH                  amd64
ANDROID
AUTOGENCMD               bpftool btf dump file /sys/kernel/btf/vmlinux format c > kern/bpf/x86/vmlinux.h
---------------------------------------
rpmdev-setuptree         rpmdev-setuptree
tar                      tar
rpmbuild                 rpmbuild
---------------------------------------
```

**Additional context**

**Comment by cfc4n** [comment]
抱歉，没太理解你的问题是什么？

如图所示，不是已经很好的捕获了https的明文响应吗？ 只不过是http2 编码后的，需要你自己再解码。如果你使用pcapng模式，是会在安Ctrl+C 停止后，保存到文件中。

另外，你发的截图，可以保存更完整一些吗？

---

Sorry, I didn't quite understand what your question is.

As shown in the picture, isn't it already capturing plaintext responses for https? It's just encoded with http2 and needs to be decoded by yourself. If you use pcapng mode, it will be saved to a file after stopping with Ctrl+C.

Also, can you save a more complete screenshot of what you uploaded?

**Comment by ShipeiXu** [comment]
我的问题是-w ./save_3_0_5.pcapng 参数没有生效。Ctrl+C 停止后也没有文件。

**Comment by cfc4n** [comment]
我测试了一下，无法重现。
你上面的截图可以截大点吗？ 包含执行的命令

**Comment by ShipeiXu** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3360832/236395258-cd9220ab-bd2b-4427-8e07-4f237f1a16ef.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/3360832/236395286-b2aeb4b5-17b6-4e90-a9bf-2339f7f2fd58.png">

如图所示，我已经展示了完整的命令和结果。没有抓到pcap文件。

**Comment by ShipeiXu** [comment]
对http2的抓包似乎不太友好。

**Comment by cfc4n** [comment]
注意看报错的信息吧。提示你了，不支持`lo` 回环网卡的抓包。

**Comment by ShipeiXu** [comment]
> 注意看报错的信息吧。提示你了，不支持`lo` 回环网卡的抓包。

没看到错误提示。不过既然不支持lo，我又用eth0试了次，一样的结果。

**Comment by cfc4n** [comment]
`eth0`网卡也报相同的错误？ 也说是loopback回环网卡？

**Comment by ShipeiXu** [comment]
1  lo的报错在上面，，才注意到。

2. sorry。是我自己用错了。-i指定了错误的网卡。问题关闭。
3. 感谢带来这么好用的工具。
