### ISSUE TITLE
Error: unknown flag: --gobin

### ISSUE THREAD

**Issue by IBUMBLEBEE** [gojue/ecapture#354]
`./ecapture gotls -w save_android.pcapng -i wlan0 --port 443 --gobin=/home/cfc4n/go_https_client`
The gobin option is not available.
<img width="781" alt="image" src="https://user-images.githubusercontent.com/16176000/233906856-8116fb10-21d0-4a69-b7cf-bb0c72fb83ef.png">
```
./ecapture --version
ecapture version:	linux_x86_64:0.5.1-20230408-e1afbb8:5.15.0-1035-azure
```
https://github.com/gojue/ecapture/blob/v0.5.1/cli/cmd/gotls.go#L42

**Comment by cfc4n** [comment]
Sorry, `--gobin` is an incorrect flag. The correct flag should be `--elfpath`. I will fix it as soon as possible.
