### ISSUE TITLE
64-bit ELF file

### ISSUE THREAD

**Issue by tongrendx** [gojue/ecapture#359]
130|zeus:/data/local/tmp # getprop ro.product.cpu.abi
arm64-v8a
zeus:/data/local/tmp # chmod 777 ecapture
zeus:/data/local/tmp # uname -a
Linux localhost 5.10.101-android12-9-g30979850fc20 #1 SMP PREEMPT Fri Dec 23 08:30:36 UTC 2022 aarch64 Toybox
127|zeus:/data/local/tmp # ./ecapture tls
/system/bin/sh: ./ecapture: not executable: 64-bit ELF file

机型为Xiaomi 12 pro

**Comment by cfc4n** [comment]
是不是软件包版本下错了？x86还是aarch的？

**Comment by cfc4n** [comment]
你手机是aarch的，要下aarch64的包。
