### ISSUE TITLE
The captured data is incomplete （捕获的数据不全）

### ISSUE THREAD

**Issue by tongrendx** [gojue/ecapture#360]
以starbucks为例

fiddler

GET https://bff.starbucks.com.cn/common-api/v1/coupons?channel=MOP&lang=zh_CN&page_num=1&appid=859977c6f22b4f9ce98d4b02d031b4a8&timestamp=1683218280995 HTTP/1.1
Accept: application/json
X-API-Version: 2.0
Content-Type: application/json
X-Tingyun-Id: p35OnrDoP8k;c=2;r=1374163551;
x-signature: pbif1++XiLt7SaJiQtHGBCS8z1ZH3KvllJtErMWkdUwqfXLuimPHXyBc+iFU0RaR1R5u/akRMoOQPkWB1n3Mm9c4ArH/43qFBKxueKSXbJUzVGX+sCEhFEk2/ORTcT6P8BqxG683/FQ2oKhvGqDzGIN24wye3KuVzSyTGWjA8os=
Host: bff.starbucks.com.cn
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: com.starbucks.cn/9.6.0
x-bs-device-id: GXyJcTco2_Nn28CQRbiGtJVr6tjDBZ80YxoJ4SK0IUQfMPlluuq4gwQ350aRCINjp0phcYbc2fCEwW-yO47WS5vnTjyrC79T3HIV5AQr3ub5ileIxeZbi2ZkQSvvFrZreYubfY0P7t5uomOjt1zBImTgJw0ZvWv8
X-XHPAcPXq-f: A_J_fueHAQAA1dMMZmy48pV9MIpk3kGGtDeW2NN1sm2tybFqw8XFziAF3-j5AXVX1gAAAAAAAAAAAAAAAAAAAA==
X-XHPAcPXq-c: AADkfeeHAQAARSwOJw78E87R-PWWyk08xurz-jUBg58OgmQ8ShIKpz0W_9lu
X-XHPAcPXq-d: ABZAkAiQhrIBgACAQ4AQ0EKgCIGOlAiACIAAgBEAEgqnPRb_2W4AAAAAROt4bwCodWq_6EuFkvdSWyWHLLv5
X-XHPAcPXq-a: mRbZWtDeCb_kcihA5_zfUpZzbQRZfYCKir_-04GqTSLSeEdEmIQkrIp3-s_7fE1R=LPcYETlyDOsYCW=kboWcDtL=2=kOb0DxX3WedIlChvwqaYrLuh=q_KAA72ZX2mEQO5eF6DYE6EoSKXCaZJ4U4ZY2fQpXaj3SKn8AurdiEgTsYGp0TSWtb-nd14L-h7Q1qlRUZaO-00yuqLkzXl1iXfoY_b1TuI2zk6hrzEIEYsLXnzHQdnpapTwpvy2ERtueWG0hpMzTLYWE9fDIFtE2alYCDS2fHkXbHC142VTPw6y3UcKdohLuEYb2rbk_284nY-Ugfh5xx2Fpylce_aq0HMLctIsK8xrwE6G0sceur-r=9VuzrCAt00V=Hwemxd3W2xwVpzGjrycgsnUbuwhTKMa0kChI2zdMAW5nXaA5c6FaUm1F0Fp-=tr5IwFvGzfuVoGCDVznDwm6MX9jvA221sEsVkV3WZYZHGqKwanJ-mpDThims6Q1G7Xz3epwnNRWzDmS6=lbCF_2f7V6kN2_Aj7vfSNrbd=mpZvtrKyk6MkO=KXhxqozWGn2_z23I192WNwSik_ojDiouCy1I1uV2KxlUvqem4pqfHSYEJdllP2sVilAZCPYWrTaaOA0c9Wb9AyFn7dKmlXOw01-YvKep2HIRhEc6K2J6UbHyL2EZqiFNdiij1wqWJubu3CyWVX7rT=VQZeuxeyMS1thoNT6wS4-nZGqV3bSAcPl9-6C01r4uEdcAGk4Wr3L1rAVYdE7oca3K6Wc2SoFJeSNrNrzz89eRn5QSYQortYGoveqI3dwYqPgG2_oujG2hhpIlFpqfThRDJVDAwTbRkEQcLRgjOZciwW0v1imANhkNozzQzNbdFYHWFCTtikd_W-PTpThDD=mUO2MdqtQ45YRFQj7VWiko0j8NZn0tz=pYxsElWgYrQONOWyDPUeM18_jC5t6Jl-zyA4_uV8-qiapXqmR3O9F72V0Kvjmmv0vKbAIG1J3QCUb2mgLg3hfnT1Klus3a-dgEIIgQGo4bjFozRaf24rX=yiAKcSzyYb1kGpCjQwiE6Z99VgI1=-k4JSry0vTKyMv4MK9P7z7TFcmyuWm2Hbjeh4Sg6HxxRqFttT1yupUGZM1HsKnZb0xucYlycIUZsPYgwfAa=F=i=ZO5Sykotw5fRhePbyLyVz=UMxGEcsLEfJlmOD1=mjQshC9jU4jMg711oxh56Vl3L=P9Mta_LxmMiVXlD-OKYsDf426Gypj6sb7ccacCyobrh8YjRC48PnENRiNCycqDiwcX7l03dE89heQgITgbTxE-XjxpE_aMTNfpC4V39gv0XDwLdNw-RTETgMhcUdHo=7_29E=hy4Eo6Dzfo33H5C=_FLCN1P=sjYIwFjXroImsvobdNNE2GyXlzhQo2emhulNRAse8SF=X=liqlUZ4lLKE84O7gOC8FWczDf6dHes3OkDi-5FVq-OC_fb2uO0U1pgrUuzbKXaYKtsX=ZF66xxu-IINRyiYTaohvUFYFadrKqtJrK8GCCz1W-zx9UiGFzfD96W3CfoEiSR1VO=hKrbmXsWyd7Am-VsL1cllLxpr8SI_-L5WhbKi226fq56QTZkXYphkdzWC8nuhTE2x2CJTA2Khh-KPqZS6pc5PFGrzX3_43YhySSEsVhJ3dMgYVymSMy5V9hMqeK5cZZ4WH=4TSt7we-Z200kJU7T3vPOwihI4Z0dybNqyZDy1ISHuFS_PshcerH2Nscpe8xalehj9h2=W2CXalxgDQfYHmmiIZPWiffzbMFhxxaGpG9gPayhWR9ddmyNwfx45kEPmjzImmx87q2ZMkZRkJcu3bjva44n6GXrk9An6J1d5GTzneaeW4gf1s3Gp779DaJM6ruKAQxdX5eHiyPMHh154eDbUjwWa4=7uQqmXzbnW=z2aiuwprx1NiuyagjiUo48apKt__VkDmP3YkCVhO1wI870GeJFCz-ilzYZc8b8smau5Ul-z4oP881yMxuGA4zqw-YoNIe_e60dXqeGNJ1r6H8ESIGtxPFZwzEuNNOojNpbqfyrxrJOEnN5txCU-pbp2z8stWGk6W4ovN_=qhEEL7arap=Y_SGgCJWoI_d3o7gpo-DWNHiqLUQ_EpY8VSrQuRDP=EvOTr6aPczGpqwSodm7xCo8otjwHPWlXOuoOPxRehh1ONrpRScguEY7mJgKySkLRH7jcNUJLplAmNhhMmjbSgV1ScyLXiAisYsTMTuDD1p1ujow845D3PCwHh_e7KjJ5DuSq4XqNvLsU-QbLrElVLX7hWOHaXgHlTy1wCWJe9WqSriQYdb39=t-gNucD0U9-g-zrMNlekVlAeL0j-a2-XnYqrzruwgWHT7rLva-KvcRTxydUIcb_aa8rcKKoY1OVNk8FIaJrhompkcl=0R-QfniCpC_-9_G7YISfRhZ3eoYAmWxI7vr44_WZU4yjKxKOOKLQ=97iQaWq5hhxdgdrW_bAbSfn3VJOKn_2H_JI8DoDXF9SOiMNyFzdJ9Zssct3WbDmQv2qZNdXj9KD4=zLtsWsbQylpQy9kdj2yVG5kJfw-j7C2m1KPA2NS=k3zPzIurx_RGdiFfwvlPWgAI4ObY17gLR0TqD7hxpYwpj_sQYrdDRz2m=kgamKdIaofGzAnTaFGTtspyklFeU5=CJa0i-_EnJUmRxw5gLseGTWijrWR9H0pb1FEqr6x1HjxpP1_Pv=ihs4AVQJYuHkT6zpn1Z2e64saq4WSpzOWcet5FIPhZUgF4YT8K4FfsUEQ0IO5Uh4-VJDtR2E2EKSilm=AP-7qQFLFvNm--4m9-3Iw7N676-e6DIt2yxxGEFdJxrsPaMLJ6KznwpuhgAodiTOGC-O2Ea6pvyGnxm0ZNvQaI9AQdXzoqJSZf0Gn6pGUl-PPfGJvjakuf77_p1jE6gMvlPUE3GmQmyds4_CjGXq8bZyEk8=XMpARtl1x_ZlkPHCUN4TJ95hy13xk_C6PyzbD9ZRam1J69fF=7LXFGX45qOhqQrWi_M=8YKnctEpNfEoms9ZXlRxdhG0wvx9bXjGJanRvXAZKjjLbP0rEeqhcR9Mu=Y=iXiOlvGU9u6F=b9Y
X-XHPAcPXq-b: mduqml
X-XHPAcPXq-z: q
X-XHPAcPXq-e: b;7LB4hFXrQ2t7YYZB84GYsWbQqBwCkYrrp7Spq37mP7EfyPdtsj5u7lBtbZUgZ6YYEIv4zXZi_p_jB8aAlnO7DymZCg3Hxj0CspD8OpQBZFlS-Zt5NSMJL3neBrXoETqQeMGSRrfBACEBzKDDxH-mn_1hxFC5VLbrN0MumNZ1mdX7Scu-FOlW6zRnvqo3P_WFrKdU84dh9N5LBirXWWuoSFKWFj3OYB3maeIPePAjORj0icTE3H2T3bAWOM9CAULmBTFrnKm7eRc_ykc_-BJ11Hpe-jqTlEdqVCnsMWw3aT0WipIKIyMbLtEWhuHFd-lYdRfW1330QQP1cLe2Wksp3xMfWoD5cnVg6ozDk06pBsfYRpB36oINNgFlbcq2kXmZWQ71po-GJqhQyddOhV5zZod88NWSc2ADFR5N_QOlRBAqwtgqJ5lVh8HxFHCTlXTifZ8_bZGE1KmHA-XeB5KZvr0520dKUx29qUIQWYV3P3NCY4ABV_xSeqTW-JsLKy52IE2Dimvr7bk935kZGKvOhdaH-Z7Mrq_XEHlDyiI_bvBmHtQhp-2RWhvSR-gw6lJ_ZZJmPtIWICwfkEQlX2bF_mkBrvM-xrccszvyw_u_hGUfJXXQOjLL-1-iut4jgX3g5jGQgKjTx4Z5BRyNSHjTf0KsnDP0vN1zJ5Xbpcu88c1vwuNYg05FuFt2lqwR43I6O7dgqHIDDJ2CKD47FQPV7bajXoohGzjq-WF1rjGhCA-eluGMrcmWE3KByVTNLBKCOGGnpdiGEumBWV9ASMphqyKsNZm1nZ7NQyfNgqvBgTZzs0UWF1_PzPEDcGKgFkP2MikLLdVwQ3QBpK3ZvvMhzb6iWh1AFzHKvYBf1chBtdVEOWv4bIGWQ3pWaGijc3-HRJXzTomgbTS3;UNr6KrW8Cinhpv8WXKzY2FDc75tTHGkJmDPJc-ct4B0=
x-phone-type: ANDROID
x-app-version: 9.6.0
x-device-id: 8bc37c04192c2326
Authorization: Bearer c6b7c40d72c74359b33a188c02852ecc.K+Ca3jtALZAiE/Qg1r+B6q9kasMr9SgEZL42ZFZhiUk

ecapture

tls_2023/05/04 16:39:16 UUID:19636_26378_ucks.com.cn/..._1261_1, Name:DefaultParser, Type:0, Length:4096
tls_2023/05/04 16:39:16
GET /common-api/v1/coupons?channel=MOP&lang=zh_CN&page_num=1&appid=859977c6f22b4f9ce98d4b02d031b4a8&timestamp=1683218356307 HTTP/1.1
Accept: application/json
X-API-Version: 2.0
Content-Type: application/json
X-Tingyun-Id: p35OnrDoP8k;c=2;r=183808137;
x-signature: QL06lG+tMl53YXIhuCLLUWuxNGjhHOsUt2EeDuKIP8mw6z2vMWJOCDkaUtqobFGnzmwKrJTlRKHpBI4DkhiBDnYb2rilQTPAAUGI9TxPTHnOooHxNMNGvQ1HfMrwsUZNS3Vbvzgv3dbBs42Zo2Q6w98bovYcG/cw8E3xkHRPx+8=
Host: bff.starbucks.com.cn
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: com.starbucks.cn/9.6.0
x-bs-device-id: GXyJcTco2_Nn28CQRbiGtJVr6tjDBZ80YxoJ4SK0IUQfMPlluuq4gwQ350aRCINjp0phcYbc2fCEwW-yO47WS5vnTjyrC79T3HIV5AQr3ub5ileIxeZbi2ZkQSvvFrZreYubfY0P7t5uomOjt1zBImTgJw0ZvWv8
X-XHPAcPXq-f: A_J_fueHAQAA1dMMZmy48pV9MIpk3kGGtDeW2NN1sm2tybFqw8XFziAF3-j5AXVX1gAAAAAAAAAAAAAAAAAAAA==
X-XHPAcPXq-c: AADkfeeHAQAARSwOJw78E87R-PWWyk08xurz-jUBg58OgmQ8ShIKpz0W_9lu
X-XHPAcPXq-d: ABZAkAiQhrIBgACAQ4AQ0EKgCIGOlAiACIAAgBEAEgqnPRb_2W4AAAAAROt4bwCodWq_6EuFkvdSWyWHLLv5
X-XHPAcPXq-a: mRbZWtDeCb_kcihA5_zfUpZzbQRZfYCKir_-04GqTSLSeEdEmIQkrIp3-s_7fE1R=LPcYETlyDOsYCW=kboWcDtL=2=kOb0DxX3WedIlChvwqaYrLuh=q_KAA72ZX2mEQO5eF6DYE6EoSKXCaZJ4U4ZY2fQpXaj3SKn8AurdiEgTsYGp0TSWtb-nd14L-h7Q1qlRUZaO-00yuqLkzXl1iXfoY_b1TuI2zk6hrzEIEYsLXnzHQdnpapTwpvy2ERtueWG0hpMzTLYWE9fDIFtE2alYCDS2fHkXbHC142VTPw6y3UcKdohLuEYb2rbk_284nY-Ugfh5xx2Fpylce_aq0HMLctIsK8xrwE6G0sceur-r=9VuzrCAt00V=Hwemxd3W2xwVpzGjrycgsnUbuwhTKMa0kChI2zdMAW5nXaA5c6FaUm1F0Fp-=tr5IwFvGzfuVoGCDVznDwm6MX9jvA221sEsVkV3WZYZHGqKwanJ-mpDThims6Q1G7Xz3epwnNRWzDmS6=lbCF_2f7V6kN2_Aj7vfSNrbd=mpZvtrKyk6MkO=KXhxqozWGn2_z23I192WNwSik_ojDiouCy1I1uV2KxlUvqem4pqfHSYEJdllP2sVilAZCPYWrTaaOA0c9Wb9AyFn7dKmlXOw01-YvKep2HIRhEc6K2J6UbHyL2EZqiFNdiij1wqWJubu3CyWVX7rT=VQZeuxeyMS1thoNT6wS4-nZGqV3bSAcPl9-6C01r4uEdcAGk4Wr3L1rAVYdE7oca3K6Wc2SoFJeSNrNrzz89eRn5QSYQortYGoveqI3dwYqPgG2_oujG2hhpIlFpqfThRDJVDAwTbRkEQcLRgjOZciwW0v1imANhkNozzQzNbdFYHWFCTtikd_W-PTpThDD=mUO2MdqtQ45YRFQj7VWiko0j8NZn0tz=pYxsElWgYrQONOWyDPUeM18_jC5t6Jl-zyA4_uV8-qiapXqmR3O9F72V0Kvjmmv0vKbAIG1J3QCUb2mgLg3hfnT1Klus3a-dgEIIgQGo4bjFozRaf24rX=yiAKcSzyYb1kGpCjQwiE6Z99VgI1=-k4JSry0vTKyMv4MK9P7z7TFcmyuWm2Hbjeh4Sg6HxxRqFttT1yupUGZM1HsKnZb0xucYlycIUZsPYgwfAa=F=i=ZO5Sykotw5fRhePbyLyVz=UMxGEcsLEfJlmOD1=mjQshC9jU4jMg711oxh56Vl3L=P9Mta_LxmMiVXlD-OKYsDf426Gypj6sb7ccacCyobrh8YjRC48PnENRiNCycqDiwcX7l03dE89heQgITgbTxE-XjxpE_aMTNfpC4V39gv0XDwLdNw-RTETgMhcUdHo=7_29E=hy4Eo6Dzfo33H5C=_FLCN1P=sjYIwFjXroImsvobdNNE2GyXlzhQo2emhulNRAse8SF=X=liqlUZ4lLKE84O7gOC8FWczDf6dHes3OkDi-5FVq-OC_fb2uO0U1pgrUuzbKXaYKtsX=ZF66xxu-IINRyiYTaohvUFYFadrKqtJrK8GCCz1W-zx9UiGFzfD96W3CfoEiSR1VO=hKrbmXsWyd7Am-VsL1cllLxpr8SI_-L5WhbKi226fq56QTZkXYphkdzWC8nuhTE2x2CJTA2Khh-KPqZS6pc5PFGrzX3_43YhySSEsVhJ3dMgYVymSMy5V9hMqeK5cZZ4WH=4TSt7we-Z200kJU7T3vPOwihI4Z0dybNqyZDy1ISHuFS_PshcerH2Nscpe8xalehj9h2=W2CXalxgDQfYHmmiIZPWiffzbMFhxxaGpG9gPayhWR9ddmyNwfx45kEPmjzImmx87q2ZMkZRkJcu3bjva44n6GXrk9An6J1d5GTzneaeW4gf1s3Gp779DaJM6ruKAQxdX5eHiyPMHh154eDbUjwWa4=7uQqmXzbnW=z2aiuwprx1NiuyagjiUo48apKt__VkDmP3YkCVhO1wI870GeJFCz-ilzYZc8b8smau5Ul-z4oP881yMxuGA4zqw-YoNIe_e60dXqeGNJ1r6H8ESIGtxPFZwzEuNNOojNpbqfyrxrJOEnN5txCU-pbp2z8stWGk6W4ovN_=qhEEL7arap=Y_SGgCJWoI_d3o7gpo-DWNHiqLUQ_EpY8VSrQuRDP=EvOTr6aPczGpqwSodm7xCo8otjwHPWlXOuoOPxRehh1ONrpRScguEY7mJgKySkLRH7jcNUJLplAmNhhMmjbSgV1ScyLXiAisYsTMTuDD1p1ujow845D3PCwHh_e7KjJ5DuSq4XqNvLsU-QbLrElVLX7hWOHaXgHlTy1wCWJe9WqSriQYdb39=t-gNucD0U9-g-zrMNlekVlAeL0j-a2-XnYqrzruwgWHT7rLva-KvcRTxydUIcb_aa8rcKKoY1OVNk8FIaJrhompkcl=0R-QfniCpC_-9_G7YISfRhZ3eoYAmWxI7vr44_WZU4yjKxKOOKLQ=97iQaWq5hhxdgdrW_bAbSfn3VJOKn_2H_JI8DoDXF9SOiMNyFzdJ9Zssct3WbDmQv2qZNdXj9KD4=zLtsWsbQylpQy9kdj2yVG5kJfw-j7C2m1KPA2NS=k3zPzIurx_RGdiFfwvlPWgAI4ObY17gLR0TqD7hxpYwpj_sQYrdDRz2m=kgamKdIaofGzAnTaFGTtspyklFeU5=CJa0i-_EnJUmRxw5gLseGTWijrWR9H0pb1FEqr6x1HjxpP1_Pv=ihs4AVQJYuHkT6zpn1Z2e64saq4WSpzOWcet5FIPhZUgF4YT8K4FfsUEQ0IO5Uh4-VJDtR2E2EKSilm=AP-7qQFLFvNm--4m9-3Iw7N676-e6DIt2yxxGEFdJxrsPaMLJ6KznwpuhgAodiTOGC-O2Ea6pvyGnxm0ZNvQaI9AQdXzoqJSZf0Gn6pGUl-PPfGJvjakuf77_p1jE6gMvlPUE3GmQmyds4_CjGXq8bZyEk8=XMpARtl1x_ZlkPHCUN4TJ95hy13xk_C6PyzbD9ZRam1J69fF=7LXFGX45qOhqQrWi_M=8YKnctEpNfEoms9ZXlRxdhG0wvx9bXjGJanR
tls_2023/05/04 16:39:16 UUID:19636_26239_RxCachedThreadS_7355_1, Name:DefaultParser, Type:0, Length:4096
tls_2023/05/04 16:39:16

**Comment by konwa** [comment]
请求长度大于4096会出现这个问题 抓到的请求会被截断

**Comment by konwa** [comment]
kern/common.h  #define MAX_DATA_SIZE_OPENSSL 1024 * 4 
user/event/event_openssl.go const MaxDataSize = 1024 * 4 
‎pkg/event_processor/base_event.go const MaxDataSize = 1024 * 4 
这里限制了每个事件的长度 改大一些可以解决  pcapng也可以抓完整的包

**Comment by cfc4n** [comment]
为什么又关了。
