### ISSUE TITLE
在k8s中 -w参数无法捕获明文数据

### ISSUE THREAD

**Issue by 1006er** [gojue/ecapture#361]
**Describe the bug**
我在k8s部署了https的nginx的服务，在不加入-w 参数的时候，可以在标准输出中看到请求响应的明文数据，但是在加入-w 参数以后捕获到的pcapng文件利用Tshark解析依旧是加密的。
**To Reproduce**
1. 在k8s中部署nginx服务并且配置https。
2. 找到服务对应的pod的网卡以及nginx容器的加密库的位置。
3. 在不采用-w 参数的情况下可以在标准输出中获取到pod的明文的数据。
4. 在加入 -w 参数以后 利用Tshark进行解析，发现获取的数据包依然是加密过的。
**Expected behavior**
希望可以通过-w参数获取明文数据包。
**Screenshots**
在不加入-w 参数的情况下
![QQ截图20230505115709](https://user-images.githubusercontent.com/48878953/236440304-3f3db8ff-1725-4909-95a7-0033bd5799d4.png)
在加入-w 的情况下
![QQ截图20230505115737](https://user-images.githubusercontent.com/48878953/236440375-c0dbba63-ec3c-4ea8-bbcd-7a08078c5283.png)
利用Tshrk解析pcapng文件发现数据包依旧是TLS加密的。

**Comment by cfc4n** [comment]
要用`wireshark` 4.0以上版本来打开 eCapture抓到的包。

**Comment by 1006er** [comment]
感谢，之前ubuntu18.0.4默认安装wireshark2.x与tshark2.x，在更新以后就可以解析出http的内容了
