### ISSUE TITLE
In Android13 Raspberry 4b：read-only file system

### ISSUE THREAD

**Issue by daxianyu** [gojue/ecapture#362]
我在Raspberry 4b中安装了Android13 LineageOS 定制版本，Linux version 5.15.106-v8-g8d0475872f62

因为使用ecapture-v0.5.2-android-aarch64后提示未开启btf,于是换成nocore版本

在开启adb并获得root权限后,运行adb shell，进入环境
然后运行/data/local/tmp/ecapture tls命令，提示如下

rpi4:/ # /data/local/tmp/ecapture tls                                                                     
tls_2023/05/05 09:22:11 ECAPTURE :: ecapture Version : androidgki_aarch64:0.5.2-20230501-ae62a6a:5.4.0-104-generic
tls_2023/05/05 09:22:11 ECAPTURE :: Pid Info : 2157
tls_2023/05/05 09:22:11 ECAPTURE :: Kernel Info : 5.15.106
tls_2023/05/05 09:22:11 EBPFProbeOPENSSL	module initialization
tls_2023/05/05 09:22:11 EBPFProbeOPENSSL	module initialization failed, [skip it]. error:open ecapture_masterkey.log: read-only file system
tls_2023/05/05 09:22:11 ECAPTURE :: 	No runnable modules, Exit(1)

**Comment by SeeFlowerX** [comment]
先cd到 /data/local/tmp 再执行 ./ecapture

**Comment by daxianyu** [comment]
> 先cd到 /data/local/tmp 再执行 ./ecapture

谢谢，有效果了，但是紧接着开始启动后，我打开安装的app，点进去到处进行网络访问，并没有包的请求记录打出来，ecapture_masterkey.log文件中也是空的

130|:/data/local/tmp # ./ecapture tls                                                                     
tls_2023/05/05 09:43:14 ECAPTURE :: ecapture Version : androidgki_aarch64:0.5.2-20230501-ae62a6a:5.4.0-104-generic
tls_2023/05/05 09:43:14 ECAPTURE :: Pid Info : 2231
tls_2023/05/05 09:43:14 ECAPTURE :: Kernel Info : 5.15.106
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	module initialization
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	master key keylogger: ecapture_masterkey.log
tls_2023/05/05 09:43:14 ECAPTURE ::	Module.Run()
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	UPROBE MODEL
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found, used default version :android_default
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	Hook masterKey function:SSL_in_init
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	target all process. 
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	target all users. 
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	BPF bytecode filename:user/bytecode/boringssl_1_1_1_kern.o
tls_2023/05/05 09:43:14 EBPFProbeOPENSSL	module started successfully.
tls_2023/05/05 09:43:14 ECAPTURE :: 	start 1 modules


tls_2023/05/05 09:52:17 EBPFProbeOPENSSL	close. 
tls_2023/05/05 09:52:18 EBPFProbeOPENSSL	close

**Comment by SeeFlowerX** [comment]
这也看不出来什么原因...

你cat下你APP的maps，看看 libssl.so 路径对不对。以及这个只支持64位的进程。

另外多打开几个APP试试
