### ISSUE TITLE
panic: runtime error: slice bounds out of range [:116] with length 48

### ISSUE THREAD

**Issue by kittyzero520** [gojue/ecapture#363]
- OS: [e.g. Ubuntu 21.04] 虚拟出的安卓12客户端
- Arch: [e.g. arm_aarch64]
- Kernel Version: [5.10]
- Version: [0.52]

blueline:/data/local/tmp # ./ecapt tls -i eth0 -w test.pcapng
tls_2023/05/06 09:48:48 ECAPTURE :: ecapture Version : androidgki_aarch64:0.5.2-20230501-ae62a6a:[CORE]
tls_2023/05/06 09:48:48 ECAPTURE :: Pid Info : 54362
tls_2023/05/06 09:48:48 ECAPTURE :: Kernel Info : 5.10.110
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        module initialization
tls_2023/05/06 09:48:48 ECAPTURE ::     Module.Run()
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        TC MODEL
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        OpenSSL/BoringSSL version not found, used default version :android_default
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        Ifname:eth0, Ifindex:8,  Port:443, Pcapng filepath:/data/local/tmp/test.pcapng
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        Hook masterKey function:SSL_in_init
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        target all process.
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        target all users.
tls_2023/05/06 09:48:48 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/boringssl_1_1_1_kern.o
tls_2023/05/06 09:48:50 EBPFProbeOPENSSL        module started successfully.
tls_2023/05/06 09:48:50 ECAPTURE ::     start 1 modules
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 9ddd1ca29cc72c4f7dc814603314bef6f7c173e294ac644e5b61207fcfac2e08 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 476b9d822f476aaada299dfc78e496fa9d7f6625fdc52484511adc495b181244 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 46dce2827302308c8ddc726717d177ede32535dfb7f885a3a77db4afe511ace2 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 5cc3a588a7fbe22e8284de8c24854f6fb658bd7fafdb77c734e48f10f6595c9e to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 9548a35557b62ffc6903735ef3b0c4656df78f9988fca1b810a85a171a6f6ef4 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM 8f5a1a54312ce5ae7e8b571872b19334a7045246dec013cd88e2011fb378ec75 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM be476e31b26e7d3dab729f8f47f55bdaf8610df6f3f3904fdadb3ee732147945 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_3_VERSION: save CLIENT_RANDOM af3089ae7498864656451d8e2476ea441db690b59c42eae4c168d5ddfaba04c0 to file success, 938 bytes
tls_2023/05/06 09:48:54 TLS1_2_VERSION: save CLIENT_RANDOM 80a02899d5c86dd6f4a44a57b39dcb98bb43112cf87e25c05f1641bab1010611 to file success, 176 bytes
tls_2023/05/06 09:48:55 TLS1_3_VERSION: save CLIENT_RANDOM 805c15082c31442683d9b0eb94f5e4ff308e0d049247033e8d440f70e88fa6ae to file success, 938 bytes
panic: runtime error: slice bounds out of range [:116] with length 48

goroutine 24 [running]:
ecapture/user/module.(*MOpenSSLProbe).saveMasterSecretBSSL(0x40001b6dc0, 0x4005c01800)
        /source_code/user/module/probe_openssl.go:533 +0x88c
ecapture/user/module.(*MOpenSSLProbe).Dispatcher(0x0?, {0x5dca38?, 0x4005c01800?})
        /source_code/user/module/probe_openssl.go:629 +0x180
ecapture/user/module.(*Module).Dispatcher(0x40001b6dc0, {0x5dca38, 0x4005c01800})
        /source_code/user/module/imodule.go:304 +0x80
ecapture/user/module.(*Module).perfEventReader.func1()
        /source_code/user/module/imodule.go:231 +0x21c
created by ecapture/user/module.(*Module).perfEventReader
        /source_code/user/module/imodule.go:199 +0x170

**Comment by cfc4n** [comment]
怎么重现这问题呢？
Can you tell me how to reproduce it?
