### ISSUE TITLE
请问支持 boring ssl 并且是静态编译的情况吗

### ISSUE THREAD

**Issue by yankunsam** [gojue/ecapture#367]
我们的场景是希望针对 Envoy tls 的流量解析，按文档中给 envoy 在 host 上的路径未生效。

**Comment by cfc4n** [comment]
libssl路径指定为静态编译的程序即可。

**Comment by yankunsam** [comment]
是的，应该是我之前没找到本地的文件 感谢

<img width="882" alt="Screen Shot 2023-05-23 at 11 00 58 AM" src="https://github.com/gojue/ecapture/assets/16130147/49f3e1d6-2fef-48d7-b039-a5729b50cff0">
