### ISSUE TITLE
when run ecapture in a container(k8s),  nothing captured

### ISSUE THREAD

**Issue by yankunsam** [gojue/ecapture#368]
actually I test by grpc service.
 
1. /home/ecapture/ecapture tls --libssl=/usr/local/bin/envoy    --port  15443 -p 16 -i eth0 -w /home/ecapture/test.pcapng

it reports 

```tls_2023/05/25 07:49:01 nothing captured, please check your network interface, see "ecapture tls -h" for more information.
tls_2023/05/25 07:49:01 EBPFProbeOPENSSL	close.
tls_2023/05/25 07:49:01 EBPFProbeOPENSSL	close
```
2. when not use -w option, it capture below information

<img width="1065" alt="image" src="https://github.com/gojue/ecapture/assets/16130147/49669e72-3c39-4237-90cc-1f2ee9f7c4b0">

**Comment by cfc4n** [comment]
It should be the wrong network card for monitoring. Make sure that the network card corresponding to the `-i` parameter is the one used for network traffic.

**Comment by yankunsam** [comment]
@cfc4n  when I use -i and not -w, it works. And the same network card. Is it containers's virtual interface effect?

**Comment by cfc4n** [comment]
I'm not sure if it has been affected, but what I can confirm is that the network Interface being monitored is definitely incorrect.

**Comment by cfc4n** [comment]
ping... @yankunsam

**Comment by yankunsam** [comment]
Still the same situation.  maybe ecapture not work for veth obtained from k8s(docker runtime)

**Comment by cfc4n** [comment]
Can tcpdump capture these packets?

**Comment by yankunsam** [comment]
yes.

**Comment by yankunsam** [comment]
1. you need a k8s cluster, such as minikube
2. deploy Istio in k8s cluster, also enable east-west gateway
3. deploy grpc-go client and server, https://github.com/grpc/grpc-go/tree/master/examples/helloworld

**Comment by chriskaliX** [comment]
I'll check the issue this week

**Comment by cfc4n** [comment]
> I'll check the issue this week

ping ...

**Comment by chriskaliX** [comment]
received, check this now

**Comment by chriskaliX** [comment]
Hi, im still struggling for the env......would you please join qq group 177508087 for better communication, thanks @yankunsam

**Comment by yankunsam** [comment]
Fine

**Comment by chriskaliX** [comment]
:-), touch me if u've in the group. I'll solve this this weekend

**Comment by yankunsam** [comment]
@chriskaliX  is the number(177508087) right? I only find a people, not group.

**Comment by chriskaliX** [comment]
yes 177508087, or touch me chriskali@163.com... I'll invite you into the group...

**Comment by chriskaliX** [comment]
@yankunsam We've talked, next week

**Comment by chriskaliX** [comment]
You have to get the offset of the binary~Reach me if anything needed
