### ISSUE TITLE
DumpResponse error: unexpected EOF

### ISSUE THREAD

**Issue by YumeMichi** [gojue/ecapture#370]
**Describe the bug**
Unable to capture response JSON from some game servers.

**To Reproduce**
1. Install game [LoveLive ALL STARS](https://apkcombo.com/%E3%83%A9%E3%83%96%E3%83%A9%E3%82%A4%E3%83%96-%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AB%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%ABall-stars/com.klab.lovelive.allstars/)
2. Open ALL STARS
3. Press Return to skip Google account login
4. Enter game
5. Check console log output

**Expected behavior**
JSON response

**Screenshots**
![](https://i.imgur.com/SLLsEAl.jpg)

**Linux Server/Android (please complete the following information):**

- Env: Mumu Emulator
- OS: Android 12
- Arch: x86_64
- Kernel Version: 4.19
- Version: androidgki_x86_64:0.5.3-20230521-fba6930:5.15.0-1037-azure

**Additional context**

**Comment by cfc4n** [comment]
@YumeMichi  please try PR #372 ,thanks.
