### ISSUE TITLE
unresolved symbol assets.Asset 

### ISSUE THREAD

**Issue by arctan90** [gojue/ecapture#373]
https://github.com/gojue/ecapture/blob/dbc827e0eeeb84c233a022063e952ae2f68616b1/user/module/probe_bash.go#L62

I traced git log, the func Asset() is removed in [commit](https://github.com/gojue/ecapture/commit/28d9c0cc9585ca50522e1851264760246a46efc9)

That's a tragedy XD

**Comment by cfc4n** [comment]
`Makefile` will create func `Asset()`.


Run cmd :
```shell
make -j4
```

**Comment by arctan90** [comment]
> `Makefile` will create func `Asset()`.
> 
> Run cmd :
> 
> ```shell
> make -j4
> ```

ok, I went through the Makefile, and found the depended repo. 
I'll do some work on offline system by myself.
