### ISSUE TITLE
是否可以增加http的监听，这样http和https就可以配套使用了

### ISSUE THREAD

**Issue by ownthink** [gojue/ecapture#375]

**Comment by cfc4n** [comment]
eCapture 产品定位是用于`https/tls`的加密数据明文捕获，而非`http`的明文抓包。近期不会考虑支持http数据包补货需求，你可以使用`tcpdump`来代替。


补充一下：
1. pcapng模式已支持。
2. text模式下，比较难区分`read`、`write` 函数的调用目的，是普通文件读写、磁盘读写、还是网络数据写入。
