### ISSUE TITLE
Encountered an Error while Compiling eCapture.

### ISSUE THREAD

**Issue by jpgong** [gojue/ecapture#381]
编译报错：
clang -D__TARGET_ARCH_x86 \
        -O2 -mcpu=v1  -nostdinc -Wno-pointer-sign \
        -I ./kern -I ./kern/bpf/x86 \
        -target bpfel -c kern/openssl_1_1_1a_kern.c -o user/bytecode/openssl_1_1_1a_kern.o \
        -fno-ident -fdebug-compilation-dir . -g -D__BPF_TARGET_MISSING="GCC error \"The eBPF is using target specific macros, please provide -target\"" \
        -MD -MP

看起其他问题，并不是clang，cmake版本过低问题

配置
kernel：5.4.249
clang:11.0.1
llvm:11.0.1
pahole 1.22
bpftool:7.2.0，用5.4.249试了更不行
感觉大多数error涉及error: use of undeclared identifier 'BPF_ANY'; did you mean 'BPF_OK'?
![image](https://github.com/gojue/ecapture/assets/27892657/a9096f2a-b93a-4b11-a181-8371c8601db5)

**Comment by cfc4n** [comment]
看着像是bpftool导出的`vmlinux.h`不全，试试`make nocore`.

**Comment by cfc4n** [comment]
ping ?

**Comment by jpgong** [comment]
> 看着像是bpftool导出的`vmlinux.h`不全，试试`make nocore`.
> 
> It seems like the `vmlinux.h` exported by bpftool is incomplete. Give `make nocore` a try.

网上的一些方法我都试了也不行，make nocore也试过，不太行。可能是centos的原因，内核安装一直有些问题？我直接使用编译好的版本来尝试了，感谢。
