### ISSUE TITLE
找不到tls的几个库

### ISSUE THREAD

**Issue by jpgong** [gojue/ecapture#382]
运行bin/ecapture tls --hex，会找不到gnutls、nss/nspr的TLS库
![image](https://github.com/gojue/ecapture/assets/27892657/ba9ea150-e0c0-4e0b-88d7-4a479f3198cd)
在系统中这两个库在/usr/lib64下，同时也在/etc/ld.so.conf中添加了/usr/lib64路径，但还是报错
![image](https://github.com/gojue/ecapture/assets/27892657/8f350506-faf0-4ee5-bfe9-a9e78c4dcfc4)

**Comment by jpgong** [comment]
> 不是报错，只是跳过了那几个类库。 但 openssl的正常。 可以捕获基于openssl的动态连接库加密的协议。

好的，那要是我要捕获基于gnutls的协议就需要使用--libssl来指定特定的库就行了是吧

**Comment by cfc4n** [comment]
忘记是哪个参数了，你看help内容吧
