### ISSUE TITLE
ecapture是不是只能在部署的设备上，采集访问外网地址数据？

### ISSUE THREAD

**Issue by kittyzero520** [gojue/ecapture#383]
1.测试服务器上部署了ecapture，并且搭建了一个nginx
2.服务器上自己访问自己的网址https://test.kittycat520.top/index.html
./ecapture tls可以抓到数据
2.武汉家宽访问服务器上的https://test.kittycat520.top/index.html
./ecapture tls无数据

ecapture是不是只能在部署的设备上，采集访问外网地址数据，不可以采集别人访问部署了ecapture服务器的http服务

- OS: [ Ubuntu 21.04]
- Kernel Version: [5.4.0-153-generic]
- Version: [eCapture v0.6.1]

**Comment by cfc4n** [comment]
不区分服务端还是客户端，只跟HOOK的类库地址有关。
你要确保当你是客户端或服务端时，触发网络行为所使用的ssl类库地址是被ecapture hook的。

**Comment by kittyzero520** [comment]
ecapture部署在服务器设备上，笔记本没有ecapture，笔记本访问服务器，也是可以hook的？

**Comment by cfc4n** [comment]
> ecapture部署在服务器设备上，笔记本没有ecapture，笔记本访问服务器，也是可以hook的？

站在服务端角度，都是这个操作系统上的TLS流量。

不管自己的角色是client，还是server，只要使用了被ecapture hook的ssl.so，那么都应该被捕获到。

**Comment by kittyzero520** [comment]
ths
