### ISSUE TITLE
--port filter seems do not change anyting it is still capturing packets from all ports

### ISSUE THREAD

**Issue by os11k** [gojue/ecapture#384]
**Describe the bug**
--port filter seems do not change anything it is still capturing packets from all ports

**To Reproduce**
1. start ecapture with `./ecapture tls --port 443` and expect only traffic to be seen on port 443.
2. Run SIP TLS traffic on port 5061
3. You will see traffic hitting port 5061

**Expected behavior**
I would expect to see only traffic on provided port, 443 in this example

**Screenshots**
![image](https://github.com/gojue/ecapture/assets/6322576/c7496e8a-f89f-449a-b412-eec0796790cb)

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables] - N/A (I used pre-compiled ecapture)
- OS: [Ubuntu-Server 20.04.3 2021.12.08]
- Arch: [x86_64]
- Kernel Version: [5.4.0-109-generic]
- Version: [linux_x86_64:0.6.1-20230716-e1cd6c7:5.15.0-1041-azure]

**Comment by os11k** [comment]
seems -i is ignored too, I have several interfaces on my test box, and it doesn't matter which interface I choose it stills shows all traffic

**Comment by cfc4n** [comment]
Only when pcapng mode(aka `-w` flag) is enabled, these two parameters  will take effect.

#### pcapng mode usage
```shell
 ./ecapture -tls -w 1.pcapng -i ens33 --port 5601
```

**Comment by os11k** [comment]
I just tried

`./ecapture tls -w 1.pcapng -i ens192`

And it do not writes traffic on port 5061, but it does writes traffic for 443 port...

**Comment by cfc4n** [comment]
> I just tried
> 
> `./ecapture tls -w 1.pcapng -i ens192`
> 
> And it do not writes traffic on port 5061, but it does writes traffic for 443 port...
> 
> when I do run `./ecapture tls`
> 
> I see traffic on both ports 443 and 5061

Did you forget to include the `--port` parameter?

```shell
./ecapture tls -w 1.pcapng -i ens192 --port 5061
```



If it still doesn't work properly, you can modify it and recompile it yourself. However, I believe there is no need to compile it on your own for it to function normally.

https://github.com/gojue/ecapture/blob/e1cd6c7c7c71d604ae7aa4c23875b7857541b6e4/kern/common.h#L52

**Comment by cfc4n** [comment]
By the way, if you are using `pcapng` mode, you need to open `1.pcapng`  with Wireshark to view it. Make sure your Wireshark version is higher than 4.0.

**Comment by os11k** [comment]
Aah, if I do not put `--port` parameter it will look only on port 443?

Correct?

I just tried:

`./ecapture tls -w 1.pcapng -i ens192 --port 5061`

and it captured nothing...

**Comment by os11k** [comment]
> If it still doesn't work properly, you can modify it and recompile it yourself

Ahh, I just noticed this your comment. let me try to recompile it and report back

**Comment by os11k** [comment]
Hi! Sorry, I didn't had time to recompile with port 5061, I will try to do it during this week. Thank you!

**Comment by os11k** [comment]
Hi @cfc4n! It worked after recompiling. I can see packets on port 5061, when I compile with:

```
const volatile u64 target_port = 5061;
```

Any plans to make ` --port` argument to work? It doesn't work during live capture or during writing to file... Seems that arguments does nothing. Or?

Thank you again for your help and have a good day!

**Comment by cfc4n** [comment]
Hmm, I will debug this issue in the near future.

**Comment by cfc4n** [comment]
I checked and confirmed that this parameter can take effect when the kernel version is greater than 5.2 or above.Will write network packet information to a file.

<img width="768" alt="image" src="https://github.com/gojue/ecapture/assets/709947/93922285-b049-433b-84cf-fad69112f856">


However, I will add some prompts when the kernel is less than 5.2.
