### ISSUE TITLE
The capture file appears to have been cut short in the middle of a packet.

### ISSUE THREAD

**Issue by newcworld** [gojue/ecapture#385]
**Describe the bug**
use ecapture save pcapng  format file
After open the dump file, it appears 
```
The capture file appears to have been cut short in the middle of a packet.
```
<img width="827" alt="截屏2023-08-11 15 19 28" src="https://github.com/gojue/ecapture/assets/71140907/bc53fdcf-9c33-4619-9f78-3b9249bb7c04">

**To Reproduce**
```
./ecapture tls -i rmnet_data2 -w /sdcard/BaiduNetdisk/test_2.pcapng  
```

**Comment by cfc4n** [comment]
Please make sure that `rmnet_data2` is the network interface you are using for data usage.

**Comment by cfc4n** [comment]
ping?

**Comment by cfc4n** [comment]
No response. closed.
