### ISSUE TITLE
isContainerCgroup() for linux doesn't work in certain scenarios

### ISSUE THREAD

**Issue by pemarko** [gojue/ecapture#395]
**Describe the bug**
Running local kind cluster, when ecapture is executed inside ubuntu:22.04 container, it fails to start as it cannot find /boot/config-*
Problem is detection in isContainerCgroup() which reads single 1024 chunk of /proc/1/cgroups and looks for "cpuset:/" substring. However in my case, substring is at byte1612. 

**To Reproduce**
Run ecapture inside container on local kind cluster.

**Expected behavior**
ecapture should detect that's running inside container and thus won't require /boot/config* file to be present.

**Comment by cfc4n** [comment]
Running ecapture in a container, file absence is not the main issue. There are also many problems related to the container's BPF execution permissions, library location, symbol table search, and so on. It is recommended that you use `ecapture` inside the host machine.

ref: https://github.com/gojue/ecapture/issues/65

**Comment by cfc4n** [comment]
ping?
