### ISSUE TITLE
tmp/go-build4031096546/b001/exe/go-bindata: exec format error make: *** [Makefile:370：assets] 错误 1

### ISSUE THREAD

**Issue by 1683728221** [gojue/ecapture#411]
Hello!

Development environment ：
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/lib/go-1.21'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go-1.21/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'

Use the command make nocore，The result is an error as follows，

go run github.com/shuLhan/go-bindata/cmd/go-bindata -pkg assets -o "assets/ebpf_probe.go" ./user/bytecode/bash_kern_less52.o ./user/bytecode/bash_kern.o ./user/bytecode/boringssl_1_1_1_kern_less52.o ./user/bytecode/boringssl_1_1_1_kern.o ./user/bytecode/gnutls_kern_less52.o ./user/bytecode/gnutls_kern.o ./user/bytecode/gotls_kern_less52.o ./user/bytecode/gotls_kern.o ./user/bytecode/mysqld_kern_less52.o ./user/bytecode/mysqld_kern.o ./user/bytecode/nspr_kern_less52.o ./user/bytecode/nspr_kern.o ./user/bytecode/openssl_1_0_2a_kern_less52.o ./user/bytecode/openssl_1_0_2a_kern.o ./user/bytecode/openssl_1_1_0a_kern_less52.o ./user/bytecode/openssl_1_1_0a_kern.o ./user/bytecode/openssl_1_1_1a_kern_less52.o ./user/bytecode/openssl_1_1_1a_kern.o ./user/bytecode/openssl_1_1_1b_kern_less52.o ./user/bytecode/openssl_1_1_1b_kern.o ./user/bytecode/openssl_1_1_1d_kern_less52.o ./user/bytecode/openssl_1_1_1d_kern.o ./user/bytecode/openssl_1_1_1j_kern_less52.o ./user/bytecode/openssl_1_1_1j_kern.o ./user/bytecode/openssl_3_0_0_kern_less52.o ./user/bytecode/openssl_3_0_0_kern.o ./user/bytecode/postgres_kern_less52.o ./user/bytecode/postgres_kern.o
fork/exec /tmp/go-build4031096546/b001/exe/go-bindata: exec format error
make: *** [Makefile:370：assets] 错误 1

After analysis, I found that go-bindata reported an error, it is the first time for me to contact it, very strange, is there any good solution，After analysis, I found that go-bindata reported an error, it is the first time for me to contact it, very strange, is there any good solution? I mainly want to compile files that support android_core-aarch64

**Comment by cfc4n** [comment]
It seems to be an issue with your compilation environment.

for more detail: [cmd/compile: "exec format error" when running newly-built binary on linux-loong64-3a5000](https://github.com/golang/go/issues/53116)
https://stackoverflow.com/questions/36198418/golang-cannot-execute-binary-file-exec-format-error
