### ISSUE TITLE
Intermittent Omission of HTTP Requests/Responses in pcapng Capture Files

### ISSUE THREAD

**Issue by douglasmakey** [gojue/ecapture#414]
Hi everyone,

Firstly, thanks for this amazing project. It has been incredibly useful.

**Describe the bug**
Capturing HTTP requests and responses using the -w option occasionally results in missing entries. In instances where 10 requests are made, only about 7 or 8 requests are recorded in the pcapng file, and a majority of the expected responses are absent.

Could this be a bug, or is there a specific reason why some packets might not be captured? Any guidance on how to ensure all requests and responses are captured would be greatly appreciated.

**To Reproduce**
Steps to reproduce the behavior are not fully determinable, as the missing packets issue seems sporadic. However, it typically occurs during normal packet capture sessions using the -w flag.

```sh
sudo ./ecapture tls -w pcapng -i wlp5s0
```

**Expected behavior**
All HTTP requests and responses made during the capture session should be recorded in the pcapng file.

**Screenshots**
![2023-11-14 17 33 53](https://github.com/gojue/ecapture/assets/8400576/7689313c-7a3e-4865-a90b-c70a97f84b07)

**Linux Server/Android (please complete the following information):**

- Env: 

```txt
- ---------------------------------------
eCapture Makefile Environment:
---------------------------------------
PARALLEL                 12
---------------------------------------
CLANG_VERSION            12
GO_VERSION               1.18
---------------------------------------
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
VERSION                  0.6.4-20231015-f50129f
LAST_GIT_TAG             0.6.4-20231015-f50129f
BPF_NOCORE_TAG           6_2_0-33-generic.0_6_4-20231015-f50129f
---------------------------------------
UNAME_M                  x86_64
UNAME_R                  6.2.0-33-generic
ARCH                     x86_64
LINUX_ARCH               x86
---------------------------------------
KERN_RELEASE             6.2.0-33-generic
KERN_BUILD_PATH          /lib/modules/6.2.0-33-generic/build
KERN_SRC_PATH            /lib/modules/6.2.0-33-generic/build
---------------------------------------
GO_ARCH                  amd64
ANDROID                  
AUTOGENCMD               bpftool btf dump file /sys/kernel/btf/vmlinux format c > kern/bpf/x86/vmlinux.h
---------------------------------------
rpmdev-setuptree         rpmdev-setuptree
tar                      tar
rpmbuild                 rpmbuild
---------------------------------------
```

- OS: Ubuntu 22.04.3 LTS
- Kernel Version: 6.2.0-33-generic
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**
The issue was observed in a stream where multiple HTTP responses can be seen without their corresponding requests, indicating potential packet loss or an issue with the capture process.

**Comment by cfc4n** [comment]
as https://github.com/gojue/ecapture/pull/409 said , please set `--port=0` to capture all ports network packets on `pcapnng` model.

**Comment by cfc4n** [comment]
> and a majority of the expected responses are absent.

What kind of network communication package is this for? Can you provide some demos?

**Comment by douglasmakey** [comment]
Thank you for your prompt response, @cfc4n.

I attempted using --port=0 with the command, but unfortunately, the output indicated nothing captured, please check your network interface. Additionally, Wireshark was unable to open the file, reporting that it contained no packets.

```txt
sudo ./cap tls -w pcapng -i wlp5s0 --port=0
tls_2023/11/15 14:54:26 ECAPTURE :: ecapture Version : linux_x86_64:0.6.4-20231015-f50129f:[CORE]
tls_2023/11/15 14:54:26 ECAPTURE :: Pid Info : 572873
tls_2023/11/15 14:54:26 ECAPTURE :: Kernel Info : 6.2.16
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL module initialization
tls_2023/11/15 14:54:26 ECAPTURE :: Module.Run()
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL TC MODEL
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL OpenSSL/BoringSSL version not found from shared library file, used default version:linux_default_3_0
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL HOOK type:2, binrayPath:/lib/x86_64-linux-gnu/libssl.so.3
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL Ifname:wlp5s0, Ifindex:3,  Port:0, Pcapng filepath:/home/douglasmakey/ecapture/bin/pcapng
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL Hook masterKey function:SSL_write
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL target all process. 
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL target all users. 
tls_2023/11/15 14:54:26 EBPFProbeOPENSSL BPF bytecode filename:user/bytecode/openssl_3_0_0_kern.o
tls_2023/11/15 14:54:27 EBPFProbeOPENSSL module started successfully.
tls_2023/11/15 14:54:27 ECAPTURE ::  start 1 modules
tls_2023/11/15 14:54:36 TLS1_3_VERSION: save CLIENT_RANDOM 43e6e71e345d5819f07db26de720ca103b7df9c06daf9cce96d6c9b065e9326b to file success, 1002 bytes
tls_2023/11/15 14:54:37 TLS1_3_VERSION: save CLIENT_RANDOM db26607e76e3081b467916c13f665a300cc82709018007f7fcf8b74c16e7e56a to file success, 1002 bytes
tls_2023/11/15 14:54:38 TLS1_3_VERSION: save CLIENT_RANDOM 2c007d3126d2703dac12fdc9b873a0102f02a473f59b0f959f5d3569657c9371 to file success, 1002 bytes



^Ctls_2023/11/15 14:54:43 EBPFProbeOPENSSL saving pcapng file /home/douglasmakey/ecapture/bin/pcapng
tls_2023/11/15 14:54:43 nothing captured, please check your network interface, see "ecapture tls -h" for more information.
tls_2023/11/15 14:54:43 EBPFProbeOPENSSL close. 
tls_2023/11/15 14:54:43 EBPFProbeOPENSSL close
```

The console output indicated various operations, including module initializations and BPF bytecode loading, but ended with the message “nothing captured”. 

> > and a majority of the expected responses are absent.
> 
> What kind of network packets is this for? Can you provide some demos?

Regarding your question about the type of network packets and a request for demos:

The issue primarily involves HTTP traffic. I used curl to send requests to simple endpoints for testing. However, I'm facing challenges in capturing these packets consistently.

**Comment by cfc4n** [comment]
Sorry, I overlooked one thing - `--port=0` is a new feature in v0.6.5, please use the new version. 

However, I still cannot understand the situation you mentioned in your screenshot about not receiving some responses. I need a reproducible demo.

**Comment by douglasmakey** [comment]
I am experiencing an issue where not all HTTP responses are being captured in the pcapng file generated by ecapture, and I'm unsure if I'm missing something. To reproduce this issue, I have set up two terminals with the following configurations:

**Terminal 1 (Running ecapture):**
I run ecapture to monitor TLS traffic on my network interface (wlp5s0) and write the output to a pcapng file:

```bash
sudo ./ecapture tls -w pcapng -i wlp5s0
```

**Terminal 2 (Executing HTTP Requests):**
In another terminal, I execute a loop of 10 simple HTTP GET requests to a public API:

```bash
for i in {1..10}; do curl https://dog.ceo/api/breeds/image/random; done
```

**Observed Behavior:**
While I successfully receive all 10 responses from the API in Terminal 2, the pcapng file generated in Terminal 1 shows an inconsistency. All 10 requests are captured, but only 2 or 3 responses are visible in the file. This can be further evidenced in the screenshot provided earlier, where there are visible requests but not their corresponding response packets.

**Expected Behavior:**
I expect to see all 10 HTTP requests and their corresponding responses captured in the pcapng file.

**Comment by cfc4n** [comment]
My test results are normal, and I have captured 10 HTTPS requests.

**Terminal 1**
```shell
sudo ./ecapture tls -w 2.pcapng -i eth0 --port=0
tls_2023/11/17 19:07:59 ECAPTURE :: ecapture Version : linux_x86_64:0.6.5-20231111-256a2b5:5.15.0-1050-azure
tls_2023/11/17 19:07:59 ECAPTURE :: Pid Info : 16161
tls_2023/11/17 19:07:59 ECAPTURE :: Kernel Info : 5.15.122
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	module initialization
tls_2023/11/17 19:07:59 ECAPTURE ::	Module.Run()
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	TC MODEL
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found from shared library file, used default version:linux_default_3_0
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/lib/x86_64-linux-gnu/libssl.so.3
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	Ifname:eth0, Ifindex:2,  Port:0, Pcapng filepath:/home/ubuntu/ecapture-v0.6.5-linux-x86_64/2.pcapng
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	Hook masterKey function:SSL_write
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	target all process.
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	target all users.
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	BPF bytecode filename:user/bytecode/openssl_3_0_0_kern.o
tls_2023/11/17 19:07:59 EBPFProbeOPENSSL	module started successfully.
tls_2023/11/17 19:07:59 ECAPTURE :: 	start 1 modules
tls_2023/11/17 19:08:06 TLS1_3_VERSION: save CLIENT_RANDOM 7e79283f4f5afdf900137f81226c3b62fec6a7fa4fc7ae37e2496f4df8a12579 to file success, 1002 bytes
tls_2023/11/17 19:08:07 TLS1_3_VERSION: save CLIENT_RANDOM 5f131320813cf7a9382fa5eec748447d7c6ead26c3d5c75b75a29915070ae9e2 to file success, 1002 bytes
tls_2023/11/17 19:08:07 TLS1_3_VERSION: save CLIENT_RANDOM a3a0ea2ab56a5733b957091a8df29456b8421e4a55c979c311fcd293fa4774d2 to file success, 1002 bytes
tls_2023/11/17 19:08:08 TLS1_3_VERSION: save CLIENT_RANDOM 6009619bccd367ce273c4b51649ff5a87e2f7cd48d2489af96afb90c47c974dd to file success, 1002 bytes
tls_2023/11/17 19:08:09 TLS1_3_VERSION: save CLIENT_RANDOM 7fd176b773644a68f35a5555a75734118b8f55638bce067fbeeb0fcfff8ca185 to file success, 1002 bytes
tls_2023/11/17 19:08:09 TLS1_3_VERSION: save CLIENT_RANDOM 8e3a6e4966e775392322518452afa06281258d0eda1689afd1e78614fcc96d90 to file success, 1002 bytes
tls_2023/11/17 19:08:09 TLS1_3_VERSION: save CLIENT_RANDOM eae62361c9e8533b10dc86b7682e188117fb8842380a71055bda10ba69548319 to file success, 1002 bytes
tls_2023/11/17 19:08:10 TLS1_3_VERSION: save CLIENT_RANDOM 0071fda5336b07a96a6d1a2b8f24b204724d6e18da9907382671155c5c9289d1 to file success, 1002 bytes
tls_2023/11/17 19:08:11 TLS1_3_VERSION: save CLIENT_RANDOM a1cb41f2244e706789f5eeb43111e3602921ad7a0895fb284092dce4820cf48e to file success, 1002 bytes
tls_2023/11/17 19:08:11 TLS1_3_VERSION: save CLIENT_RANDOM fde96587117902dd3f4f5e38a56761879fe0f6652c3386ac018a8ea2a6b3ff94 to file success, 1002 bytes
^Ctls_2023/11/17 19:08:14 EBPFProbeOPENSSL	saving pcapng file /home/ubuntu/ecapture-v0.6.5-linux-x86_64/2.pcapng
tls_2023/11/17 19:08:14 EBPFProbeOPENSSL	 save 308 packets into pcapng file.
tls_2023/11/17 19:08:14 EBPFProbeOPENSSL	close.
tls_2023/11/17 19:08:14 EBPFProbeOPENSSL	close
```
**Terminal 2**
```shell
for i in {1..10}; do curl https://dog.ceo/api/breeds/image/random; done
{"message":"https:\/\/images.dog.ceo\/breeds\/setter-irish\/n02100877_407.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/terrier-wheaten\/n02098105_2001.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/terrier-sealyham\/n02095889_2019.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/terrier-russell\/iguet3.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/hound-english\/n02089973_1312.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/setter-gordon\/n02101006_1205.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/mountain-bernese\/n02107683_705.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/pointer-germanlonghair\/hans4.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/pekinese\/n02086079_2073.jpg","status":"success"}{"message":"https:\/\/images.dog.ceo\/breeds\/terrier-patterdale\/320px-05078045_Patterdale_Terrier.jpg","status":"success"}
```

You can use Wireshark to open `2.pcapng`. From `tcp.stream eq 1` to `tcp.stream eq 10`, they are all HTTPS requests.

<img width="900" alt="image" src="https://github.com/gojue/ecapture/assets/709947/e344273c-6d83-4411-b913-0264fd89c1b9">

[wireshark-ssl-debug.log](https://github.com/gojue/ecapture/files/13391026/wireshark-ssl-debug.log)
[2.pcapng.zip](https://github.com/gojue/ecapture/files/13391032/2.pcapng.zip)

**Comment by douglasmakey** [comment]
Hi @cfc4n 

Thank you for your time. It seems the issue is associated with using my WiFi connection. When I switch to my wired connection (eth0), I am able to capture all the packets correctly! Do you have any idea on why this might be happening?

Again thank so much for your time and help!

**Comment by cfc4n** [comment]
I'm not sure, maybe some requests have chosen a different routing table and using other network interface.
