### ISSUE TITLE
通过 ecapture tls -p 26570 数据由于加密乱码，有啥办法能请求body和返回body只输出十六进制文本呢？

### ISSUE THREAD

**Issue by makeloveandroid** [gojue/ecapture#416]
![1700098901827](https://github.com/gojue/ecapture/assets/16134562/6e4e6f60-6ae6-4faf-b841-feaeb26acbb0)

通过一下类似这几个命令，我发现就抓不到对应的请求了
ecapture tls -w save_3_0_5.pcapng --ssl_version="openssl 3.0.5" --libssl=/lib/x86_64-linux-gnu/libssl.so.3 
ecapture tls -w save_android.pcapng -i wlan0 --libssl=/apex/com.android.conscrypt/lib64/libssl.so --ssl_version="boringssl 1.1.1" --port 443

尝试了下 --hex 也不行

**Comment by cfc4n** [comment]
--hex应该可以的，你这报错了？

**Comment by makeloveandroid** [comment]
> --hex 应该可以的，你这个报错了？
![111](https://github.com/gojue/ecapture/assets/16134562/474116cf-bb57-484a-86ad-d7e5a7d33ff5)

意思是报错了？设备信息如下
![222](https://github.com/gojue/ecapture/assets/16134562/fa40bd9f-0412-4faf-b8ed-ed533ff95c78)

**Comment by BiteFoo** [comment]
我感觉应该是请求的body部分需要额外的处理，因为输出的时候是整个都输出了，如果将请求的header和body分割出来，应该能把这个原始加密的数据进行hex输出，这个主要针对的是body部分。

**Comment by cfc4n** [comment]
你这里是http reponse的gzip格式， 理论上说，不属于加密、解密的范畴。

不过，确实是可以优化的点。  另外，`--hex`模式没生效好像是bug。

你可以使用pcapng模式，将网络包保存到文件里，在用wireshark来查看。
