### ISSUE TITLE
Converting kernel-space timestamp to user-space timestamp

### ISSUE THREAD

**Issue by h0x0er** [gojue/ecapture#420]
In code under `/kern`, `bpf_ktime_get_ns()` is being used to get the timestamp. This function returns kernel-space timestamp. 

The timestamp along with other data is then returned to user-space. So converting it to  user-space timestamp makes more sense, instead of keeping it as kernel timestamp. As end-user would be more interested to know at what user-time, specific event was received.

Refer: #418

**Comment by cfc4n** [comment]
yep, got it. thanks.

**Comment by h0x0er** [comment]
@cfc4n ,Thanks for merging the PR. Feel free to close the issue.
