### ISSUE TITLE
Your environment is like a container. We won't be able to detect the BTF configuration.

### ISSUE THREAD

**Issue by ten-plus-month** [gojue/ecapture#427]
**Describe the bug**
不能运行 ./ecapture tls,这个报错怎么解决？

**To Reproduce**
vbox86p:/data/local/tmp #  ./ecapture tls
2023/11/23 05:23:00 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2023/11/23 05:23:00 ECAPTURE :: ecapture Version : linux_x86_64:0.6.6-20231119-06b63d6:5.15.0-1050-azure
tls_2023/11/23 05:23:00 ECAPTURE :: Pid Info : 2958
tls_2023/11/23 05:23:00 ECAPTURE :: Kernel Info : 5.10.101
tls_2023/11/23 05:23:00 EBPFProbeOPENSSL        module initialization failed. [skip it]. error:cant found openssl so load path
tls_2023/11/23 05:23:00 EBPFProbeGNUTLS module initialization
tls_2023/11/23 05:23:00 ECAPTURE ::     Module.Run()
tls_2023/11/23 05:23:00 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2023/11/23 05:23:00 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /lib/x86_64-linux-gnu/libgnutls.so.30: no such file or directory
tls_2023/11/23 05:23:00 EBPFProbeNSPR   module initialization
tls_2023/11/23 05:23:00 ECAPTURE ::     Module.Run()
tls_2023/11/23 05:23:00 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2023/11/23 05:23:00 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /usr/lib/firefox/libnspr4.so: no such file or directory
tls_2023/11/23 05:23:00 ECAPTURE ::     No runnable modules, Exit(1)
![image](https://github.com/gojue/ecapture/assets/39802701/55648139-bd1f-49ce-a6b9-f180f883b298)

- Env: [run `make env` to get the environment variables]
Linux localhost 5.10.101-genymotion+-ab74 #1 SMP PREEMPT Thu Dec 1 14:03:02 UTC 2022 x86_64

**Comment by cfc4n** [comment]
看一下 help参数吧，   而且报错提示比较清晰，没找到libssl.so 的路径，可以通过`--libssl=xxxxx.so`来指定，如果你还是不熟悉，那建议你看下ecapture的教学视频。

**Comment by ten-plus-month** [comment]
加了参数还是报错
1|vbox86p:/data/local/tmp # ./ecapture tls --libssl=/system/lib64/libssl.so
2023/11/24 01:17:34 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2023/11/24 01:17:34 ECAPTURE :: ecapture Version : linux_x86_64:0.6.6-20231119-06b63d6:5.15.0-1050-azure
tls_2023/11/24 01:17:34 ECAPTURE :: Pid Info : 2501
tls_2023/11/24 01:17:34 ECAPTURE :: Kernel Info : 5.10.101
tls_2023/11/24 01:17:34 EBPFProbeOPENSSL        module initialization failed. [skip it]. error:cant found 'connect' function to hook in files::[libpthread.so.0 libc.so.6 libc.so]
tls_2023/11/24 01:17:34 EBPFProbeGNUTLS module initialization
tls_2023/11/24 01:17:34 ECAPTURE ::     Module.Run()
tls_2023/11/24 01:17:34 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2023/11/24 01:17:34 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /lib/x86_64-linux-gnu/libgnutls.so.30: no such file or directory
tls_2023/11/24 01:17:34 EBPFProbeNSPR   module initialization
tls_2023/11/24 01:17:34 ECAPTURE ::     Module.Run()
tls_2023/11/24 01:17:34 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2023/11/24 01:17:34 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /usr/lib/firefox/libnspr4.so: no such file or directory
tls_2023/11/24 01:17:34 ECAPTURE ::     No runnable modules, Exit(1)

**Comment by ten-plus-month** [comment]
ldd是这样的
127|vbox86p:/data/local/tmp # ldd `which wget`
        linux-vdso.so.1 => [vdso] (0x7fff9ed95000)
        libcutils.so => /system/lib64/libcutils.so (0x7a4042d89000)
        libc++.so => /system/lib64/libc++.so (0x7a4042ec5000)
        libc.so => /apex/com.android.runtime/lib64/bionic/libc.so (0x7a4042f89000)
        libm.so => /apex/com.android.runtime/lib64/bionic/libm.so (0x7a4042e2c000)
        libdl.so => /apex/com.android.runtime/lib64/bionic/libdl.so (0x7a4042e99000)
        liblog.so => /system/lib64/liblog.so (0x7a4042dcd000)
        libbase.so => /system/lib64/libbase.so (0x7a4045e6a000)

**Comment by cfc4n** [comment]
还有一个参数`--pthread`，来指定一下。 
`--pthread=/apex/com.android.runtime/lib64/bionic/libc.so`  或 `--pthread=/system/lib64/libc++.so`  试试。

**Comment by ten-plus-month** [comment]
这两个都不行
1|vbox86p:/data/local/tmp # ./ecapture tls --libssl=/system/lib64/libssl.so --pthread=/apex/com.android.runtime/lib64/bionic/libc.so
2023/11/24 07:48:04 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2023/11/24 07:48:04 ECAPTURE :: ecapture Version : linux_x86_64:0.6.6-20231119-06b63d6:5.15.0-1050-azure
tls_2023/11/24 07:48:04 ECAPTURE :: Pid Info : 6997
tls_2023/11/24 07:48:04 ECAPTURE :: Kernel Info : 5.10.101
tls_2023/11/24 07:48:04 EBPFProbeOPENSSL        module initialization failed. [skip it]. error:cant found 'connect' function to hook in files::[libpthread.so.0 libc.so.6 libc.so]
tls_2023/11/24 07:48:04 EBPFProbeGNUTLS module initialization
tls_2023/11/24 07:48:04 ECAPTURE ::     Module.Run()
tls_2023/11/24 07:48:04 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2023/11/24 07:48:04 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /lib/x86_64-linux-gnu/libgnutls.so.30: no such file or directory
tls_2023/11/24 07:48:04 EBPFProbeNSPR   module initialization
tls_2023/11/24 07:48:04 ECAPTURE ::     Module.Run()
tls_2023/11/24 07:48:04 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2023/11/24 07:48:04 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /usr/lib/firefox/libnspr4.so: no such file or directory
tls_2023/11/24 07:48:04 ECAPTURE ::     No runnable modules, Exit(1)
1|vbox86p:/data/local/tmp #
1|vbox86p:/data/local/tmp #
1|vbox86p:/data/local/tmp #
1|vbox86p:/data/local/tmp # ./ecapture tls --libssl=/system/lib64/libssl.so --pthread=/system/lib64/libc++.so
2023/11/24 07:48:32 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2023/11/24 07:48:32 ECAPTURE :: ecapture Version : linux_x86_64:0.6.6-20231119-06b63d6:5.15.0-1050-azure
tls_2023/11/24 07:48:32 ECAPTURE :: Pid Info : 7012
tls_2023/11/24 07:48:32 ECAPTURE :: Kernel Info : 5.10.101
tls_2023/11/24 07:48:32 EBPFProbeOPENSSL        module initialization failed. [skip it]. error:cant found 'connect' function to hook in files::[libpthread.so.0 libc.so.6 libc.so]
tls_2023/11/24 07:48:32 EBPFProbeGNUTLS module initialization
tls_2023/11/24 07:48:32 ECAPTURE ::     Module.Run()
tls_2023/11/24 07:48:32 EBPFProbeGNUTLS BPF bytecode filename:user/bytecode/gnutls_kern.o
tls_2023/11/24 07:48:32 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /lib/x86_64-linux-gnu/libgnutls.so.30: no such file or directory
tls_2023/11/24 07:48:32 EBPFProbeNSPR   module initialization
tls_2023/11/24 07:48:32 ECAPTURE ::     Module.Run()
tls_2023/11/24 07:48:32 EBPFProbeNSPR   BPF bytecode filename:user/bytecode/nspr_kern.o
tls_2023/11/24 07:48:32 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /usr/lib/firefox/libnspr4.so: no such file or directory
tls_2023/11/24 07:48:32 ECAPTURE ::     No runnable modules, Exit(1)

我用的是genymotion模拟的安卓12
