### ISSUE TITLE
Running ecapture with the --hex flag does not produce a hex output as expected from the video tutorial on Ubuntu 22.04. 

### ISSUE THREAD

**Issue by pathnames** [gojue/ecapture#429]
**Describe the bug**
Running ecapture with the --hex flag does not produce a hex output as expected from the video tutorial on Ubuntu 22.04. 

**To Reproduce**
1. Run `sudo ./ecapture tls --hex`
2. In another terminal window, run `curl https://www.baidu.com`
3. Observe the output of ecapture and confirm that no hex output exists.

**Expected behavior**
The output is expected to be in a hex form. 

**Screenshots**
<img width="640" alt="image" src="https://github.com/gojue/ecapture/assets/47400339/9a4ada24-9662-48f6-b3a1-46b319b1c701">
<img width="641" alt="image" src="https://github.com/gojue/ecapture/assets/47400339/f3dad673-4cf4-46f2-b0ed-ecaeb9cf922b">
<img width="605" alt="image" src="https://github.com/gojue/ecapture/assets/47400339/ed666926-405a-47dd-865a-20fcc4b65a9f">

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
<img width="608" alt="image" src="https://github.com/gojue/ecapture/assets/47400339/1b9155e8-d6c3-4a94-994f-2469ff457b52">

- OS: [e.g. Ubuntu 22.04]
- Arch: x86_64

<img width="604" alt="image" src="https://github.com/gojue/ecapture/assets/47400339/fd8e5611-46ff-43e3-b865-a76b691348cd">

- Kernel Version: 6.2.0-36-generic

**Comment by cfc4n** [comment]
fixed at #421 ,please update.
