### ISSUE TITLE
Can eCapture save decrypted HTTP to pcapng instead of saving the master key to DSB?

### ISSUE THREAD

**Issue by bugfixer-coder** [gojue/ecapture#430]
能否将解密后的HTTP保存到pcapng，而不是将master key保存到DSB呢？

**Comment by cfc4n** [comment]
不能。
1. 原始报文用于wireshark的网络分析场景，不适合剥离HTTP。
2. 剥离HTTP的成本较大，需要拆解skb的内容，解密HTTPS，再读取HTTP，再还原到skb里。

建议你自行使用wireshark来实现，未来或许可以在`文本模式`中规划这部分能力。

**Comment by bugfixer-coder** [comment]
谢谢解答，我自己考虑下如何实现这个功能。

**Comment by cfc4n** [comment]
enjoy.
