### ISSUE TITLE
怎么抓经过手机热点的流量

### ISSUE THREAD

**Issue by xingkong123600** [gojue/ecapture#442]
环境：小米12 Linux localhost 5.10.136
手机端ecapture能正常运行，app的流量能抓到。
此时一台电脑连接了手机发射的热点，无法抓到电脑访问的流量。
怎么抓经过手机热点的流量。

**Comment by cfc4n** [comment]
做不到这一点。eCapture不支持针对网络层通信做明文捕获，只支持运行时密文做明文捕获。 即，产生密文跟抓包工具在同一台操作系统上。
