### ISSUE TITLE
Not working with redroid

### ISSUE THREAD

**Issue by XiaoliChan** [gojue/ecapture#445]
ENV:
- ecapture: 0.7.0
- devices: redroid 13 (docker container)

Error:
`2023/12/16 17:30:14 Failed to read kernel configuration., error:open /proc/config.gz: no such file or directory`

Redroid didn't include `/proc/config.gz`, maybe can add some argument like `--force` to force execute ecapture?

**Comment by cfc4n** [comment]
Good suggestion, I will evaluate it.

**Comment by XiaoliChan** [comment]
Can confirm `/sys/kernel/btf/vmlinux` is existed in redroid
![image](https://github.com/gojue/ecapture/assets/30458572/b7e811e8-4672-4c97-97a6-29b7b830515c)

**Comment by cfc4n** [comment]
Not all androids will have `/sys/kernel/btf/vmlinux` present. I intend to be compatible with both cases.

**Comment by XiaoliChan** [comment]
> Not all androids will have `/sys/kernel/btf/vmlinux` present. I intend to be compatible with both cases.

Sweet, I'm looking forward to using it with redroid👍

**Comment by cfc4n** [comment]
Can you check where the '/proc/config.gz' file has been changed on your Redroid device?

**Comment by XiaoliChan** [comment]
> Can you check where the '/proc/config.gz' file has been changed on your Redroid device?

I have tried many times with the Redroid (from android 12-13), it looks like `/proc/config.gz` has removed and I can't find where is it.

**Comment by XiaoliChan** [comment]
Okay, I know what happens now, so the `IsContainer` function in `bpf_androidgki.go` is not done yet

Force return `true` in `IsContainer` function to make it work
![image](https://github.com/gojue/ecapture/assets/30458572/6470c943-8ccc-4411-bef5-97a71fd08a59)

**Comment by cfc4n** [comment]
The 'IsContainer' function does not return 'true' directly, and some features need to be detected. What are the characteristics of Redroid that are different from Android? Like a file? A configuration?

**Comment by XiaoliChan** [comment]
> The `IsContainer` function does not return `true` directly, and some features need to be detected. What are the characteristics of Redroid that are different from Android? Like a file? A configuration?

TBH, I also don't know what the difference between them XD.
The reason why I use Redroid is it just a docker container and it is easy to deploy it.

**Comment by cfc4n** [comment]
Well, it looks like a niche need. I'm not going to fix it to the project, what do you think?

**Comment by XiaoliChan** [comment]
> Well, it looks like a niche need. I'm not going to fix it to the project, what do you think?

Well, maybe need a `--force` arg and don't need to fix the `IsContainer` function

**Comment by cfc4n** [comment]
@hongyang51 在你的开发板设备上， config的路径是什么呢？

**Comment by hongyang51** [comment]
> @hongyang51 在你的开发板设备上， config的路径是什么呢？

/boot/config* , 但是我只是修改了检索的路径，修改为/data/local/config.gz 可以手动push上去。
校验与否对我来说实际不太重要
