### ISSUE TITLE
鸿蒙4.0支持分析https内容不

### ISSUE THREAD

**Issue by maojianyou** [gojue/ecapture#447]
目前是发现有些APP应用故障，但因为https加密，无法看到内容，所有无法具体分析故障原因，该项目是否支持解密鸿蒙4.0的系统，具体怎么安装

**Comment by maojianyou** [comment]
能否做成类似安卓apk直接安装验证抓包的

**Comment by cfc4n** [comment]
我没有鸿蒙的设备，没测试过。理论来说，只要是基于Linux的内核，都可以运行。就看内核版本是否支持。


APK的方向，我不太会写Android程序，你可以做个贡献吗？

**Comment by cfc4n** [comment]
ping @maojianyou ??
