### ISSUE TITLE
eCapture run failed, error log: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hhhhhge** [gojue/ecapture#451]
# ecapture-v0.7.0-android_core-aarch64 ./ecapture
2023/12/21 12:39:30 BTF is not supported, please check it. shell: cat /boot/config-`uname -r` | grep CONFIG_DEBUG_INFO_BTF
 You can compile the BTF-free version by using the command `make nocore`, please read the Makefile for more information.

这是什么情况，小米，安卓13，内核5.10

**Comment by cfc4n** [comment]
换 non-CO-RE版本 ： https://github.com/gojue/ecapture/releases/download/v0.7.0/ecapture-v0.7.0-android-aarch64-nocore.tar.gz

**Comment by hhhhhge** [comment]
# / cd /storage/emulated/0/ecapture; sh /storage/emulated/0/ecapture/run.sh; exit &>/dev/null
tls_2023/12/21 22:34:22 ECAPTURE :: ecapture Version : androidgki_aarch64:0.7.0-20231203-2fbdf3f:5.4.0-155-generic
tls_2023/12/21 22:34:22 ECAPTURE :: Pid Info : 28169
tls_2023/12/21 22:34:22 ECAPTURE :: Kernel Info : 5.10.200
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        module initialization
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        master key keylogger:
tls_2023/12/21 22:34:22 ECAPTURE ::     Module.Run()
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        Text MODEL
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        OpenSSL/BoringSSL version found, ro.build.version.release=13
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        Hook masterKey function:SSL_in_init
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        libPthread:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        target all process.
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        target all users.
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/boringssl_a_13_kern.o
tls_2023/12/21 22:34:22 EBPFProbeOPENSSL        perfEventReader created. mapSize:20 MB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2b4d80]

goroutine 1 [running]:
github.com/cilium/ebpf/perf.NewReaderWithOptions(0x40003b25a0, 0x1400000, {0x118fb00?, 0xd8?})
        /home/ubuntu/go/pkg/mod/github.com/cilium/ebpf@v0.12.3/perf/reader.go:234 +0x270
github.com/cilium/ebpf/perf.NewReader(...)
        /home/ubuntu/go/pkg/mod/github.com/cilium/ebpf@v0.12.3/perf/reader.go:187
ecapture/user/module.(*Module).perfEventReader(0x400013e580, 0x40005f0000, 0x40003b25a0)
        /home/ubuntu/project/ecapture/user/module/imodule.go:193 +0x140
ecapture/user/module.(*Module).readEvents(0x400013e580)
        /home/ubuntu/project/ecapture/user/module/imodule.go:181 +0xfc
ecapture/user/module.(*Module).Run(0x400013e580)
        /home/ubuntu/project/ecapture/user/module/imodule.go:140 +0x100
ecapture/cli/cmd.openSSLCommandFunc(0x4000172a00?, {0x52d3c8?, 0x4?, 0x52d324?})
        /home/ubuntu/project/ecapture/cli/cmd/tls.go:131 +0x680
github.com/spf13/cobra.(*Command).execute(0xc1d4c0, {0x118e2c0, 0x0, 0x0})
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x53c
github.com/spf13/cobra.(*Command).ExecuteC(0xc1d240)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
ecapture/cli/cmd.Execute()
        /home/ubuntu/project/ecapture/cli/cmd/root.go:75 +0x108
ecapture/cli.Start(...)
        /home/ubuntu/project/ecapture/cli/main.go:22
main.main()
        /home/ubuntu/project/ecapture/main.go:73 +0x1c0

run.sh是自己写的sh文件
cd /data/media/0/ecapture
./ecapture tls
这样有什么问题

**Comment by cfc4n** [comment]
```shell
./ecapture tls --mapsize=256
```
