### ISSUE TITLE
gotls 访问百度，https 包无法获取、只能截取 http 包

### ISSUE THREAD

**Issue by cleverhu** [gojue/ecapture#458]
**Describe the bug**

**To Reproduce**
1. 使用以下代码
```
package main

import (
	"crypto/tls"
	"fmt"
	"io"
	"net/http"
	"os"
)

func main() {

	b, e := GetHttp("https://baidu.com")
	if e == nil {
		fmt.Printf("response body: %s\n\n", b)
	} else {
		fmt.Printf("error :%v", e)
	}
}

func GetHttp(url string) (body []byte, err error) {
	// 开启TLS密钥记录，用于跟eCpature捕获的密钥对比。
	f, err := os.OpenFile("/tmp/go_master_secret.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	c := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true, KeyLogWriter: f},
		}}
	resp, e := c.Get(url)
	if e != nil {
		return nil, e
	}

	defer resp.Body.Close()
	body, err = io.ReadAll(resp.Body)
	return body, err
}
```
2. 构建
`go build -o test main.go`
3. 抓包
```
ecapture gotls -e /root/test
```

**Expected behavior**
实际得到结果:
![image](https://github.com/gojue/ecapture/assets/51436614/b2ece8c3-18bc-483e-bcf3-99ee1aacd59d)
需要结果是:
![image](https://github.com/gojue/ecapture/assets/51436614/14634342-29f2-43a0-a52c-1f933ca37f17)

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: 22.04.1-Ubuntu
- Arch: x86_64
- Kernel Version: 6.2.0-39-generic
- Version: ecapture version:	linux_x86_64:v0.7.2:5.15.0-1053-azure

**Additional context**
go version go1.21.3 linux/amd64
参考的是这个链接学习: https://www.cnxct.com/ecapture-supported-golang-tls-plaintext-captured/

**Comment by cleverhu** [comment]
b, e := GetHttp("https://baidu.com")
我将这个改成 	b, e := GetHttp("https://www.baidu.com") 后乱码了，
![image](https://github.com/gojue/ecapture/assets/51436614/e97c2005-0388-4fd4-99c4-67e60bf71789)
咱们程序支持 gzip 解压吗，相关参数没找到

**Comment by cfc4n** [comment]
有这个功能，不过不完善，我给关了。 你可以先用pcap模式，用wireshark打开分析。
