### ISSUE TITLE
加解密模式对性能的影响是多少

### ISSUE THREAD

**Issue by yifannir** [gojue/ecapture#459]
请问一下关于tls模式下加解密模式对性能的影响是多少，有测试过么

**Comment by cfc4n** [comment]
你说的应该是“解密”吧？ 我没有做过相关测试，

不过，根据eBPF原理来看，注入HOOK的影响很小。 eCapture 的代码逻辑只是读取相应内存内容，并没有复杂的逻辑，理论也是可以忽略的。

**Comment by yifannir** [comment]
实测只针对某个函数测试影响有好几倍的劣化，可能是由于频繁int3的原因？
