### ISSUE TITLE
tls 模式，app抓包解密失败

### ISSUE THREAD

**Issue by amwait** [gojue/ecapture#460]
手机配置：pixel 6 pro
系统：android 12
内核版本：5.10.81
ecapture 版本： ecapture-v0.7.2-android-aarch64-nocore

问题描述：货拉拉app 流量解密失败
<img width="597" alt="截屏2024-01-16 14 37 11" src="https://github.com/gojue/ecapture/assets/58285710/c997d2a7-9540-4e78-a314-61bfb34b8412">
<img width="962" alt="截屏2024-01-16 14 48 05" src="https://github.com/gojue/ecapture/assets/58285710/08c492a7-8376-408e-a46a-02f93102f416">

<img width="582" alt="截屏2024-01-16 14 45 15" src="https://github.com/gojue/ecapture/assets/58285710/85eff80a-17a3-4144-bf9f-dda300193865">

**Comment by cfc4n** [comment]
如图所示，已经看到“HTTP/1.1 200 OK"字样了，已经是解密后的内容了。只不过内容是gzip压缩的，需要业务层解码。 目前eCapture关闭了解码功能。你可以先使用`pcap`模式来保存为pcapng文件，再用wireshark打开阅读。
