### ISSUE TITLE
error: couldn't start bootstrap manager error

### ISSUE THREAD

**Issue by hellogirl007** [gojue/ecapture#461]
OS: android
kernel: Linux localhost 5.10.43 #1 SMP PREEMPT Fri Jun 30 15:54:27 CST 2023 aarch64

error messages:
2024/01/18 08:36:53 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2024/01/18 08:36:53 ECAPTURE :: ecapture Version : androidgki_aarch64:v0.7.2:5.4.0-155-generic
tls_2024/01/18 08:36:53 ECAPTURE :: Pid Info : 26607
tls_2024/01/18 08:36:53 ECAPTURE :: Kernel Info : 5.10.43
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        module initialization
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        master key keylogger:
tls_2024/01/18 08:36:53 ECAPTURE ::     Module.Run()
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        Text MODEL
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        OpenSSL/BoringSSL version not found, used default version :android_default
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        Hook masterKey function:SSL_in_init
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        libPthread:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        target all process.
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        target all users.
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/boringssl_a_13_kern.o
tls_2024/01/18 08:36:53 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't start bootstrap manager error:8 errors occurred:
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_write' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:probe_entry_SSL_write}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_write' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:true, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:probe_ret_SSL_write}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_read' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:probe_entry_SSL_read}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_read' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:true, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:probe_ret_SSL_read}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_set_fd' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_ssl_set_fd, EbpfFuncName:probe_SSL_set_fd}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_set_rfd' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_ssl_set_rfd, EbpfFuncName:probe_SSL_set_fd}
        * error:opening uprobe: creating trace event '/apex/com.android.conscrypt/lib64/libssl.so:SSL_set_wfd' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_ssl_set_wfd, EbpfFuncName:probe_SSL_set_fd}
        * error:opening uprobe: creating trace event '/apex/com.android.runtime/lib64/bionic/libc.so:connect' in tracefs: creating probe entry on tracefs: open /sys/kernel/tracing/uprobe_events: no such file or directory , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_connect, EbpfFuncName:probe_connect}

, probes activation validation failed .
tls_2024/01/18 08:36:53 ECAPTURE ::     No runnable modules, Exit(1)

**Comment by cfc4n** [comment]
你在用的这部手机是什么型号的？    
What model is the mobile phone you are using?

**Comment by cfc4n** [comment]
It works on MacBook M2 with Android Studio Emulator.
**Android Version**
Tiramisu arm64-v8a, API 33
<img width="1076" alt="snipaste_2024-01-21_15-23" src="https://github.com/gojue/ecapture/assets/709947/3ea19a11-007e-4ecf-a98a-01790e854050">
<img width="1024" alt="snipaste_2024-01-21_15-20" src="https://github.com/gojue/ecapture/assets/709947/b2e5714b-a27b-4d76-ba36-54b70b492a22">

**Comment by cfc4n** [comment]
ping @hellogirl007
