### ISSUE TITLE
The SSL structure in openssl 3.2.0 has been modified

### ISSUE THREAD

**Issue by Z3ratu1** [gojue/ecapture#464]
`kern/openssl.h`中有一段解析SSL*获取fd的代码，看起来一个是认为结构体大致以如下形式分布
```C
struct ssl_st {
    int version;
    const SSL_METHOD *method;
    BIO *rbio;
    BIO *wbio;
    BIO *bbio;
...
}
```
但是在[openssl 3.2.0](https://github.com/openssl/openssl/blob/master/ssl/ssl_local.h#L1200)中，这个结构体直接大改，bio系列结构体都放进了一个`ssl_connection_st`的结构体，原ssl_st变为
```C
struct ssl_st {
    int type;
    SSL_CTX *ctx;
    const SSL_METHOD *defltmeth;
    const SSL_METHOD *method;
    CRYPTO_REF_COUNT references;
    CRYPTO_RWLOCK *lock;
    /* extra application data */
    CRYPTO_EX_DATA ex_data;
};
```

ssl_connection_st为
```C
struct ssl_connection_st {
    struct ssl_st ssl;
    int version;
    BIO *rbio;
    BIO *wbio;
    BIO *bbio;
    ...
}
```
在调用时`ssl_st`使用宏`SSL_CONNECTION_FROM_SSL`进行转换为`ssl_connection_st`，因此对于新的openssl版本，需整体添加`sizeof(struct ssl_st)+sizeof(int)`的偏移才能获取到rbio/wbio结构体

以及，在`uprobe/SSL_write`中，读出`ssl_wbio_addr`后，后续却是使用`ssl_wbio_ptr`加上偏移去读取数据，是否有误？
```C
   ssl_wbio_ptr = (u64 *)(ssl + SSL_ST_WBIO);
    ret = bpf_probe_read_user(&ssl_wbio_addr, sizeof(ssl_wbio_addr),
                              ssl_wbio_ptr);
    if (ret) {
        debug_bpf_printk(
            "(OPENSSL) bpf_probe_read ssl_wbio_addr failed, ret :%d\n",
            ret);
        return 0;
    }

    // get fd ssl->wbio->num
    ssl_wbio_num_ptr = (u64 *)(ssl_wbio_ptr + BIO_ST_NUM);
    ret = bpf_probe_read_user(&ssl_wbio_num_addr, sizeof(ssl_wbio_num_addr),
                              ssl_wbio_num_ptr);
    if (ret) {
        debug_bpf_printk(
            "(OPENSSL) bpf_probe_read ssl_wbio_num_ptr failed, ret :%d\n",
            ret);
        return 0;
    }

```

**Comment by cfc4n** [comment]
openssl 3.2是刚出的版本，比较新。正如你所说，存在结构体变化的情况。需要 eCapture 适配。 近期我来支持一下。

**Comment by cfc4n** [comment]
openssl 3.2.x does have a particularly big change, and I need to find a suitable HOOK function again, and I need to take some time.

However, I started by supporting the 3.1.x version of openssl library

**Comment by cfc4n** [comment]
不过，哪怕是bio的结构体发生了变化，也不影响eCapture的核心功能，依旧可以做到明文捕获。 只是影响了发送网络包的目标IP地址。

However, even if the structure of the `bio` changes, it will not affect the core functions of eCapture, and it can still be captured in plaintext. It just affects the destination IP address where the network packet is sent.

**Comment by cfc4n** [comment]
Support for `OpenSSL 3.2.0` has been completed, please try the new version [v0.7.3.](https://github.com/gojue/ecapture/releases/tag/v0.7.3)
