### ISSUE TITLE
这是我姿势不对么？最新版本的总提示No runnable modules, Exit(1)

### ISSUE THREAD

**Issue by w296488320** [gojue/ecapture#473]
2|zeus:/ # chmod 777 /data/local/tmp/ecapture
zeus:/ # /data/local/tmp/ecapture tls
2024/01/29 09:10:49 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2024/01/29 09:10:49 ECAPTURE :: ecapture Version : androidgki_aarch64:0.7.3-20240128-1a2abb8:[CORE]
tls_2024/01/29 09:10:49 ECAPTURE :: Pid Info : 28535
tls_2024/01/29 09:10:49 ECAPTURE :: Kernel Info : 5.10.101
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        module initialization
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        master key keylogger:
tls_2024/01/29 09:10:49 ECAPTURE ::     Module.Run()
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        Text MODEL
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        OpenSSL/BoringSSL version found, ro.build.version.release=13
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        Hook masterKey function:[SSL_in_init]
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        libPthread:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        target all process.
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        target all users.
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/boringssl_a_13_kern.o
tls_2024/01/29 09:10:49 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't init manager error:program probe_entry_SSL_write: apply CO-RE relocations: load kernel spec: no BTF found for kernel version 5.10.101-android12-9-00005-ga829d48e78bd-ab9206161: not supported , couldn't load eBPF programs, cs:&{map[.rodata:Array(keySize=4, valueSize=36, maxEntries=1, flags=128) active_ssl_read_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) bpf_context:LRUHash(keySize=8, valueSize=472, maxEntries=2048, flags=0) bpf_context_gen:Array(keySize=4, valueSize=472, maxEntries=1, flags=0) connect_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=1024, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4152, maxEntries=1, flags=0) mastersecret_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=1024, flags=0) network_map:LRUHash(keySize=20, valueSize=20, maxEntries=10240, flags=0) skb_data_buffer_heap:PerCPUArray(keySize=4, valueSize=40, maxEntries=1, flags=0) skb_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=10240, flags=0) ssl_st_fd:Hash(keySize=8, valueSize=8, maxEntries=10240, flags=0) tls_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=1024, flags=0)] map[egress_cls_func:0x40001fc2d0 ingress_cls_func:0x40001fc240 probe_SSL_set_fd:0x40001fc5a0 probe_connect:0x40001fc510 probe_entry_SSL_read:0x40001fc480 probe_entry_SSL_write:0x40001fc120 probe_ret_SSL_read:0x40001fc1b0 probe_ret_SSL_write:0x40001fc3f0 probe_ssl_master_key:0x40001fc000 tcp_sendmsg:0x40001fc360] 0x40000bc000 LittleEndian}
tls_2024/01/29 09:10:49 ECAPTURE ::     No runnable modules, Exit(1)
1|zeus:/ # uname -a
Linux localhost 5.10.101-android12-9-00005-ga829d48e78bd-ab9206161 #1 SMP PREEMPT Fri Oct 21 21:49:09 UTC 2022 aarch64 Toybox
zeus:/ #

**Comment by cfc4n** [comment]
问题解决了吗？
试试 non-co-re模式的zip包。

**Comment by w296488320** [comment]
解决啦，确实版本问题。感谢回复，这块建议在readme里面添加一下nocore和正常的区别。
