### ISSUE TITLE
I am new. How to use software?

### ISSUE THREAD

**Issue by HuAn28** [gojue/ecapture#476]
huan@huan-virtual-machine:~/桌面/ecapture/bin$ ./ecapture tls -m pcap -i eth0 --pcapfile=ecapture.pcapng --port=443
tls_2024/02/01 10:46:27 ECAPTURE :: ecapture Version : linux_x86_64:0.7.3-20240128-1a2abb8:[CORE]
tls_2024/02/01 10:46:27 ECAPTURE :: Pid Info : 8434
tls_2024/02/01 10:46:27 ECAPTURE :: Kernel Info : 6.5.3
tls_2024/02/01 10:46:27 EBPFProbeOPENSSL	module initialization
tls_2024/02/01 10:46:27 ECAPTURE ::	Module.Run()
tls_2024/02/01 10:46:27 EBPFProbeOPENSSL	Pcapng MODEL
tls_2024/02/01 10:46:27 EBPFProbeOPENSSL	module run failed, [skip it]. error:route ip+net: no such network interface
tls_2024/02/01 10:46:27 ECAPTURE :: 	No runnable modules, Exit(1)

**Comment by cfc4n** [comment]
See [Reade.md](https://www.youtube.com/watch?v=CoDIjEQCvvA) for more detail.

------
可以看下B站的[演示视频](https://www.bilibili.com/video/BV1si4y1Q74a/)，以及[公众号文章](https://github.com/gojue/ecapture/blob/master/README_CN.md)介绍。
