### ISSUE TITLE
gotls报错

### ISSUE THREAD

**Issue by Alberthchang** [gojue/ecapture#482]
tls_2024/02/13 15:04:18 ECAPTURE :: Pid Info : 980247
tls_2024/02/13 15:04:18 ECAPTURE :: Kernel Info : 5.4.252
tls_2024/02/13 15:04:18 EBPFProbeGoTLS	module [disabled].

uname -a
Linux 5.4.0-167-generic #184-Ubuntu SMP Tue Oct 31 09:21:49 UTC 2023

 cat /etc/issue
Ubuntu 20.04.2 LTS

**Comment by cfc4n** [comment]
认真看下readme吧。

**Comment by Alberthchang** [comment]
<img width="610" alt="image" src="https://github.com/gojue/ecapture/assets/17517153/30929f63-a583-4ef9-8ccd-7120ff09d2f6">

**Comment by Alberthchang** [comment]
这个我也开了啊

**Comment by cfc4n** [comment]
贴上全部的启动命令，以及返回的错误。

**Comment by Alberthchang** [comment]
<img width="778" alt="image" src="https://github.com/gojue/ecapture/assets/17517153/48a2a7c9-3da3-4b5f-b880-6aeefab204c4">
root@vulhub:/home/ubuntu# uname -a
Linux vulhub 5.4.0-167-generic #184-Ubuntu SMP Tue Oct 31 09:21:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@vulhub:/home/ubuntu# cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

root@vulhub:/home/ubuntu# ./ecapture gotls -m text
tls_2024/02/16 14:09:37 ECAPTURE :: ecapture Version : linux_x86_64:v0.7.3:5.15.0-1053-azure
tls_2024/02/16 14:09:37 ECAPTURE :: Pid Info : 1077940
tls_2024/02/16 14:09:37 ECAPTURE :: Kernel Info : 5.4.252
tls_2024/02/16 14:09:37 EBPFProbeGoTLS	module [disabled].
root@vulhub:/home/ubuntu# cat /boot/config-`uname -r ` |grep CONFIG_DEBUG_INFO_BTF
CONFIG_DEBUG_INFO_BTF=y
root@vulhub:/home/ubuntu# ./ecapture gotls -m pcap -i any --pcapfile=aaa.pcap
tls_2024/02/16 14:11:37 ECAPTURE :: ecapture Version : linux_x86_64:v0.7.3:5.15.0-1053-azure
tls_2024/02/16 14:11:37 ECAPTURE :: Pid Info : 1077992
tls_2024/02/16 14:11:37 ECAPTURE :: Kernel Info : 5.4.252
tls_2024/02/16 14:11:37 EBPFProbeGoTLS	module [disabled].

**Comment by cfc4n** [comment]
gotls的启动命令是`ecapture gotls --elfpath=/home/cfc4n/go_https_client --hex` ，需要指定`--elfpath`参数的值。

readme里文档介绍未更新。我修复一下。

**Comment by Alberthchang** [comment]
好的谢谢
