### ISSUE TITLE
how to use ecapture in redroid

### ISSUE THREAD

**Issue by fancy45daddy** [gojue/ecapture#483]
I install redroid (https://github.com/remote-android/redroid-doc) in oracle aarch64 machine and I want to install ecapture in the redroid. I see there are [ecapture-v0.7.3-android-aarch64-nocore.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.7.3/ecapture-v0.7.3-android-aarch64-nocore.tar.gz) and [ecapture-v0.7.3-android-aarch64.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.7.3/ecapture-v0.7.3-android-aarch64.tar.gz). I want to know which one I should use?

cat /boot/config-`uname -r` | grep CONFIG_DEBUG_INFO_BTF output nothing. there is no file /boot/config-`uname -r` in redroid

**Comment by cfc4n** [comment]
The `CONFIG_DEBUG_INFO_BTF` configuration option is not enabled, which means it is a non-core environment and can use the [ecapture-v0.7.3-android-aarch64-nocore.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.7.3/ecapture-v0.7.3-android-aarch64-nocore.tar.gz) version. 

In the future, the two versions will be merged and automatically selected by ecapture.

**Comment by cfc4n** [comment]
No response for more than 7 days
