### ISSUE TITLE
linux 环境抓go相关的包报错

### ISSUE THREAD

**Issue by zhaozuowu** [gojue/ecapture#492]
执行：ecapture gotls -m pcap -w 抓不了包，报错,相关报错截图：
![image](https://github.com/gojue/ecapture/assets/5884470/3a16b138-0c75-499b-8876-815344bc0537)

**Comment by ruitianzhong** [comment]
I also reproduced this bug in commit 2127596
![Screenshot from 2024-02-27 17-28-44](https://github.com/gojue/ecapture/assets/99736992/83082fea-c3f0-4a1c-b86b-2e54df46dc76)

**Comment by ruitianzhong** [comment]
I also reproduced this bug in commit 2127596
![Screenshot from 2024-02-27 17-28-44](https://github.com/gojue/ecapture/assets/99736992/83082fea-c3f0-4a1c-b86b-2e54df46dc76)

**Comment by cfc4n** [comment]
@zhaozuowu please try #493

**Comment by cfc4n** [comment]
hello @zhaozuowu
