### ISSUE TITLE
error: couldn't start bootstrap manager error

### ISSUE THREAD

**Issue by r0ysue** [gojue/ecapture#496]
**Describe the bug**

# ./ecapture tls -m pcap -i wlan0 -w save.pcapng tcp port 443
tls_2024/02/29 20:46:30 ECAPTURE :: ecapture Version : linux_aarch64:0.7.4-20240224-cad79db:[CORE]
tls_2024/02/29 20:46:30 ECAPTURE :: Pid Info : 4585
tls_2024/02/29 20:46:30 ECAPTURE :: Kernel Info : 5.10.110
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	module initialization
tls_2024/02/29 20:46:30 ECAPTURE ::	Module.Run()
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	Pcapng MODEL
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found from shared library file, used default version:linux_default_3_0
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	HOOK type: 2, binrayPath: /usr/lib/aarch64-linux-gnu/libssl.so.3
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	PcapFilter: tcp port 443
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	Ifname: wlan0, Ifindex: 2
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	Hook masterKey function: [SSL_get_wbio SSL_in_before SSL_do_handshake]
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	target all process. 
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	target all users. 
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	BPF bytecode filename:user/bytecode/openssl_3_0_0_kern.o
tls_2024/02/29 20:46:30 EBPFProbeOPENSSL	saving pcapng file: /root/ecapture-v0.7.4-linux-aarch64/save.pcapng
tls_2024/02/29 20:46:31 EBPFProbeOPENSSL	module run failed, [skip it]. error:couldn't start bootstrap manager error:2 errors occurred:
	* error:error:netlink receive: no such file or directory , couldn't add a ", err clsact" qdisc to interface 2, {UID:, EbpfFuncName:egress_cls_func}
	* error:error:netlink receive: no such file or directory , couldn't add a ", err clsact" qdisc to interface 2, {UID:, EbpfFuncName:ingress_cls_func}

, probes activation validation failed .
tls_2024/02/29 20:46:31 ECAPTURE :: 	No runnable modules, Exit(1)

**To Reproduce**
 # neofetch
            .-/+oossssoo+/-.               geduer@ulan 
        `:+ssssssssssssssssss+:`           ----------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 23.04 aarch64 
    .ossssssssssssssssssdMMMNysssso.       Host: YourLand Code Book - XiuFeng1 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.10.110-yanzi 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 26 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2813 (dpkg), 1 (flatpak), 9 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.2.15 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/1 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: RK3588 Cortex-A55 x 4 (8) @ 1.800GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 1401MiB / 15917MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

![截屏2024-02-29 20 52 31](https://github.com/gojue/ecapture/assets/23090578/575a2c12-08d7-4c87-a6be-09acb77ca4d2)

**Comment by cfc4n** [comment]
There have been similar issues, most likely due to incorrect network card settings or mismatched network card IDs in the emulator.

* #422
* #347
