### ISSUE TITLE
gojue/ebpfmanager dependency with an AGPL license

### ISSUE THREAD

**Issue by algorithmace24** [gojue/ecapture#507]
**Describe the bug**
We would like to use ecapture in our enterprise environment. However, a quick license scan revealed that this project depends on [gojue/ebpfmanager](https://github.com/gojue/ebpfmanager), which has an AGPL-3.0 license. This would prevent many enterprises from adopting this project.

I was wondering if the maintainers would be open to either using a non-copyleft license for _gojue/ebpfmanager_ or replace _gojue/ebpfmanager_ with another open-source dependency that does not use AGPL.

**To Reproduce**
1. Check out the go dependency at https://github.com/gojue/ecapture/blob/master/go.mod#L7
2. Check out the [license for gojue/ebpfmanager](https://github.com/gojue/ebpfmanager/blob/master/LICENSE)

**Comment by cfc4n** [comment]
I will change its license in the near future.

**Comment by algorithmace24** [comment]
Thanks @cfc4n! Please let me know if I can help in any way. If you could let me know the license (e.g., Apache 2 similar to ecapture) you would like to use for [gojue/ebpfmanager](https://github.com/gojue/ebpfmanager), I will be happy to create a PR in that project.

**Comment by cfc4n** [comment]
already been updated， enjoy .
