### ISSUE TITLE
SSL_in_before hook点在openssl 1.0.2k的系统上找不到符号表

### ISSUE THREAD

**Issue by boost2020** [gojue/ecapture#518]
**Describe the bug**
从官网下载的0.76的版本在内核4.19.91 openssl版本1.0.2k上无法运行，提示找不到符号SSL_in_before，我重新换到1.1.1的上面就正常了

**To Reproduce**
openssl 1.0.2k
kernel: 4.19.91( non btf) x86_64 (( Linux wave-test-arm 4.19.91-27.7.al7.x86_64 #1 SMP Wed Oct 25 17:46:42 CST 2023 x86_64 x86_64 x86_64 GNU/Linux ))
epcapture release version:  0.76

**Screenshots**
../soft/ecapture  --libssl /usr/lib64/libssl.so tls -m pcap
2024/04/12 17:20:09 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2024/04/12 17:20:09 ECAPTURE :: ecapture Version : linux_x86_64:v0.7.6:5.15.0-1059-azure
tls_2024/04/12 17:20:09 ECAPTURE :: Pid Info : 23473
tls_2024/04/12 17:20:09 ECAPTURE :: Kernel Info : 4.19.91
2024/04/12 17:20:09 read keylogger :ld.so.conf.d/*.conf error .
2024/04/12 17:20:09 read keylogger :ld.so.conf.d/*.conf error .
2024/04/12 17:20:09 read keylogger :ld.so.conf.d/*.conf error .
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        module initialization
tls_2024/04/12 17:20:09 ECAPTURE ::     Module.Run()
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        Pcapng MODEL
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        origin version:OpenSSL 1.0.2k, as key:openssl 1.0.2k
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        HOOK type: 2, binrayPath: /usr/lib64/libssl.so
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        PcapFilter: 
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        Ifname: eth0, Ifindex: 2
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        Hook masterKey function: [SSL_get_wbio SSL_in_before SSL_do_handshake]
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/openssl_1_0_2a_kern_less52.o
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        saving pcapng file: /root/ecapture/save.pcapng
tls_2024/04/12 17:20:09 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't start bootstrap manager error:2 errors occurred:
        * error:opening uprobe: symbol SSL_in_before: not found , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_in_before, EbpfFuncName:probe_ssl_master_key}
        * error:opening uprobe: invalid program: bad file descriptor , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_do_handshake, EbpfFuncName:probe_ssl_master_key}

, probes activation validation failed .
tls_2024/04/12 17:20:09 ECAPTURE ::     No runnable modules, Exit(1)

![image](https://github.com/gojue/ecapture/assets/62824352/bf01a3fd-0259-4a39-9383-e4321683ae3e)

**Additional context**

查看openssl1.0.2k的源码，可以看到SSL_in_before这个是个宏，而不像1.1.1是一个函数
1.0.2k
![image](https://github.com/gojue/ecapture/assets/62824352/5bdf4c31-5704-48a9-afe8-2f34deb8acd5)

1.1.1w
![image](https://github.com/gojue/ecapture/assets/62824352/f336e7b6-a54d-4d67-90ed-b06099a05d82)

**Comment by cfc4n** [comment]
你知道是从宏改为函数的版本吗？

**Comment by boost2020** [comment]
看起来就是从1.1.0开始改为函数的
https://github.com/openssl/openssl/commit/49ae742398aecd81551d59f421e4116a5b8a4ea9

![image](https://github.com/gojue/ecapture/assets/62824352/568a8d59-b515-4436-bb3e-e28f821c3fff)

**Comment by boost2020** [comment]
感谢，确认ok了
<img width="1394" alt="image" src="https://github.com/gojue/ecapture/assets/62824352/2ba3a70f-54a1-4da6-8493-5e043c0049d3">
