### ISSUE TITLE
数据抓不全的问题

### ISSUE THREAD

**Issue by ljz2009y** [gojue/ecapture#526]
使用 0.7.6 版本，在pixel 7 上面运行 https://www.wandoujia.com/apps/49917 这个app的航.班查询。

使用命令：
./ecapture tls -m text -l log

发现数据不全。json数据被截断了。

![image](https://github.com/gojue/ecapture/assets/2174368/24c2cb1c-91d6-4314-94af-26ce0c035028)

**Comment by ljz2009y** [comment]
使用的过程，有也很多 EOF 错误
2024/04/18 15:18:22 [http response] DumpResponse error: unexpected EOF
2024/04/18 15:18:25 DumpRequest error: unexpected EOF
2024/04/18 15:18:31 DumpRequest error: unexpected EOF
2024/04/18 15:18:32 unexpected EOF
2024/04/18 15:18:32 [http response] DumpResponse error: unexpected EOF

**Comment by cfc4n** [comment]
`text`模式可能会出现EOF的问题，可以尝试 pcapng模式。

```shell
./ecapture tls -m pcap -i eth0 -w  save.pcapng
```

**Comment by ljz2009y** [comment]
> `text`模式可能会出现EOF的问题，可以尝试 pcapng模式。
> 
> ```shell
> ./ecapture tls -m pcap -i eth0 -w  save.pcapng
> ```

可以请教一个问题吗？就是 save.pcapng 使用 wrieshake 打开之后，我如何解密 https 的内容。。。。

**Comment by cfc4n** [comment]
wireshark打开的就是明文的。看下以往的视频介绍吧。

**Comment by ljz2009y** [comment]
> wireshark打开的就是明文的。看下以往的视频介绍吧。

那就有问题了，通过 ./ecapture tls -m pcap -i eth0 -w  save.pcapng 抓出来的数据，http 的请求只有1个，实际应该有很多个。感觉缺了数据

![image](https://github.com/gojue/ecapture/assets/2174368/372e76f3-67ea-433e-8b70-30e378e054b9)

**Comment by bulalalla** [comment]
> > wireshark打开的就是明文的。看下以往的视频介绍吧。
> 
> 那就有问题了，通过 ./ecapture tls -m pcap -i eth0 -w save.pcapng 抓出来的数据，http 的请求只有1个，实际应该有很多个。感觉缺了数据
> 
> ![image](https://private-user-images.githubusercontent.com/2174368/323807070-372e76f3-67ea-433e-8b70-30e378e054b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjQ2ODUsIm5iZiI6MTcxMzYyNDM4NSwicGF0aCI6Ii8yMTc0MzY4LzMyMzgwNzA3MC0zNzJlNzZmMy02N2VhLTQzM2UtOGI3MC0zMGUzNzhlMDU0YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTQ0NjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q4MmE5MmM3MDBmYmQ4MTE2Y2ZmMWMzN2EzM2Y4YWZjNTA0MWNlZTBjOTkzZGE1YjI0MzI1OGU5ZmNiMDBjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qnn-Vt6l99At1rVy7Nhy8sFoV93esN1wZzwxTDmYc-U)

可能是并没有完全解密，默认情况下，它的解密依赖于找到的openssl库，不指定此库位置的话，一般会有一个默认位置，如果应用程序不使用此库，则会不能解密，不过同一个应用程序有的能解密，有的不能，这个我也很疑惑

**Comment by blaisewang** [comment]
如果能提供 pcap 我可以帮忙分析下

**Comment by cfc4n** [comment]
ping ?
