### ISSUE TITLE
unsupported arch library

### ISSUE THREAD

**Issue by shac0** [gojue/ecapture#551]
**Describe the bug**
When I run eCapture, I get an error：
unsupported arch library ,ELF Header Machine is :EM_386, must be one of EM_X86_64 and EM_AARCH64
**To Reproduce**
1. ./ecapture tls --libssl=/system/lib/libssl.so
2. module run failed

- OS: android
- Kernel Version: 5.4.40

**Comment by cfc4n** [comment]
Yes, the 32-bit libssl.so is not supported for now.

**Comment by cfc4n** [comment]
Hello, do you have any other questions?
