### ISSUE TITLE
master secret length is too long for every connection

### ISSUE THREAD

**Issue by jeromekleinen** [gojue/ecapture#569]
**Describe the bug**
For every TLS connection made, I get the error `master secret length is too long, truncate to 64 bytes, but it may cause keylog file error length=xxx`. As a consequence, I am not able to decrypt packet capture traffic using the `ecapture_openssl_key.og` that is created by ecapture.

Also the pcap mode does not create packet captures with unencrypted traffic.

Text mode does work and is able to display the contents of the requests and responses, but this mode sometimes crashes ecapture.

**To Reproduce**
1. run `ecapture tls -m keylog` on your device
2. use any app to make a TLS network connection
3. See error

**Expected behavior**
ecapture is able to capture the correct master secret that would allow me to decrypt the network traffic in wireshark

**Screenshots**
Not really applicable

**Linux Server/Android (please complete the following information):**

- OS: Android 13
- Arch: arm_aarch64
- Kernel Version: Linux localhost 5.10.149-android13-4-00002-gca169caca7bb-ab9598324 #1 SMP PREEMPT Mon Feb 13 12:48:28 UTC 2023 aarch64 Toybox
- Version: androidgki_arm64:v0.8.3:6.5.0-1021-azure

**Additional context**
Google Pixel 6a, Magisk 27

**Comment by cfc4n** [comment]
> Text mode does work and is able to display the contents of the requests and responses, but this mode sometimes crashes ecapture.

Please provide the corresponding crash stack.


> run ecapture tls -m keylog on your device

Please provide the output log.

**Comment by jeromekleinen** [comment]
Hi cfc4n,

I've upgraded my testing device to Android 14 and here it seems to work just fine. I guess we can close this. At least I am no longer able to help you debug.

Jerome
