### ISSUE TITLE
can not open /apex/com.android.conscrypt/lib64/libssl.so

### ISSUE THREAD

**Issue by winezer0** [gojue/ecapture#570]
夜神模拟器 9.0.0  内核4.1.9无法正常运行程序，提示找不到libssl.so

![image](https://github.com/gojue/ecapture/assets/46115146/506cffca-f10b-42a5-af87-b3af63905ba2)

find / name libssl 查找没有找到

是不支持模拟器环境吗

**Comment by cfc4n** [comment]
1. 可以通过`--libssl`参数指定ssl类库路径。 详情看help参数
2. windows上运行的android模拟器可能无法正常运行，见 https://github.com/search?q=repo%3Agojue%2Fecapture+%E6%A8%A1%E6%8B%9F&type=issues

**Comment by winezer0** [comment]
Android系统内核x86_64 4.18 · Issue #289 · gojue/ecapture
https://github.com/gojue/ecapture/issues/289

这里好像说mumu模拟器12版本是可以的，我测试下

**Comment by winezer0** [comment]
> 
> find / name libssl 查找没有找到
> 
我 手动在/lib 目录下找到了libssl.so 现在测试一下是否可以正常运行

**Comment by winezer0** [comment]
> Android系统内核x86_64 4.18 · Issue #289 · gojue/ecapture #289
> 
> 这里好像说mumu模拟器12版本是可以的，我测试下

![image](https://github.com/gojue/ecapture/assets/46115146/e2a893f7-ab4f-4973-822a-56e579538af3)

测试 mumu12模拟器是可以运行的

**Comment by cfc4n** [comment]
对`i386`的openssl近期没有支持的规划。

**Comment by winezer0** [comment]
好的，感谢回复，我先用mumu模拟器

**Comment by gexiaopeng** [comment]
> MuMu模拟器12只能用-m text模式，另外的 -m pcap与 -m keylog模式无法启动。



> 好的，感谢回复，我先用mumu模拟器

请问您的MuMu模拟器12可以用-m pcap与 -m keylog模式吗？ 我的windows环境下的MuMu模拟器12不行。
