### ISSUE TITLE
ecapture抓不到小米汽车的登录包，提示网络连接错误

### ISSUE THREAD

**Issue by doself** [gojue/ecapture#578]
小米汽车使用flutter编写，测试前我已手动patch了libflutter.so，将ssl_client所在的那部分偏移函数的返回值置1，能捕获到部分网络包，但是登录那块的流量还是抓不到、提示网络连接错误
![image](https://github.com/gojue/ecapture/assets/12570554/40f6011c-a082-4f9a-803a-881a92dfd99c)

**Comment by cfc4n** [comment]
请按照issue模版补充信息。

**Comment by cfc4n** [comment]
hello？
