### ISSUE TITLE
iOS support viability discussion 

### ISSUE THREAD

**Issue by LaiKash** [gojue/ecapture#584]
I am starting ecapture and I just want to open the topic of having iOS support. iOS is based on macOS so as I understand it is not in scope right now. SSL Pinning is a huge issue in iOS and this can be a good way to bypass it

**Comment by cfc4n** [comment]
eCapture is a software implemented based on [eBPF](https://ebpf.io) technology, and eBPF is a dynamic instrumentation solution provided by the Linux kernel. Currently, there are no plans to support these on macOS/iOS. Therefore, eCapture does not support macOS/iOS.

**Comment by cfc4n** [comment]
close with no response.
