### ISSUE TITLE
ecapture 在大于 5.2 的内核版本抱怨内核版本不大于 5.2

### ISSUE THREAD

**Issue by xxxxxliil** [gojue/ecapture#599]
**Describe the bug**
在我个人的使用过程，甚至是 #595 #598 中的日志的内核版本已经来到 6.1.*，但仍然提示 `WRN Kernel version is less than 5.2, Process filtering parameters do not take effect such as pid/uid. kernel=6.1.0`

**To Reproduce**
1. `# ./ecapture tls -m text -u $uid`
2. waiting the log

**Expected behavior**
应该不会在大于 5.2.0 的内核提示内核版本低的 bug

**Screenshots**
None, but output: `Kernel version is less than 5.2, Process filtering parameters do not take effect such as pid/uid. kernel=5.15.123`

**Linux Server/Android (please complete the following information):**

- Env: N/AKernel version is less than 5.2, Process filtering parameters do not take effect such as pid/uid. kernel=5.15.123`
- OS: HyperOS?
- Arch: arm_aarch64
- Kernel Version: 5.15.123-android13-8-00008-g3ca6a2912c7e-ab11087001
- Version: androidgki_arm64:v0.8.5:6.5.0-1025-azure

**Additional context**
看起来这是一个普遍问题，并不特定于设备

**Comment by cfc4n** [comment]
It seems there is a kernel version recognition error. 
I don't have a device called `HYperOS` and I'm not sure how to reproduce this issue. Does this problem also occur on Linux kernels that are greater than version 6.0?

**Comment by xxxxxliil** [comment]
In #595，linux kernel version > 6.0
