### ISSUE TITLE
ecapture 0.8.5 的日志记出现错误

### ISSUE THREAD

**Issue by xxxxxliil** [gojue/ecapture#600]
**Describe the bug**
相对于 0.8.4，我发现 0.8.5 的日志错误有两处：
1. 使用 -l </path/to/log> 时，对比终端的输出，类型为 warn 的日志不会在日志文件中出现
2. 使用 `tls -m text -u uid` 抓包时，在 0.8.4 类型为 info 的 http 上下文日志输出，在 0.8.5 变为没有类型（是的，在日志文件呈现的就是没有类型，但终端输出为 `???`。如果这是有意为之请额外补充一下）

**To Reproduce**
1. `# ./ecapture -l /path/to/log tls -m text -u uid`
2. waiting for start log
3. Make the target app make a tls request

**Expected behavior**
行为与 0.8.4 一致

**Screenshots**
N/A

**Linux Server/Android (please complete the following information):**

- Env: N/A
- OS: HyperOS?
- Arch: arm_aarch64
- Kernel Version: 5.15.123-android13-8-00008-g3ca6a2912c7e-ab11087001
- Version: androidgki_arm64:v0.8.5:6.5.0-1025-azure

**Additional context**

**Comment by cfc4n** [comment]
看上去是有问题的，晚点我验证一下。

**Comment by cfc4n** [comment]
> 但终端输出为 ???

Can you provide a screenshot? It seems to be an issue with your terminal display.

**Comment by xxxxxliil** [comment]
![image](https://github.com/user-attachments/assets/6a28d6e5-8d6f-4ba4-b884-2a0b581c0bf3)
![image](https://github.com/user-attachments/assets/8735d53c-4476-4ec8-ae11-dd6771a72b8f)
注意，这不是终端显示问题，在 text 模式下如果使用 -l 记录日志会发现终端输出为 `???` 的日志没有类型标签

**Comment by cfc4n** [comment]
uh... 这是个正确的字符`???`.   在0.8.5里，区分了程序运行日志和程序捕获事件两种日志。前者使用标准的日志级别输出，后者使用`Logger`的`Write`方法输出。 前者有标准的[日志级别](https://github.com/rs/zerolog/blob/master/globals.go#L141)，后者没有，使用默认的[`???`](https://github.com/rs/zerolog/blob/c78e50e2da70f4ae63e1b65222c3acf12e9ba699/console.go#L32)代替。

将来，`程序捕获事件`将会发送给不同的 Logger ，用于转发给其他网络代理软件，比如Charles Proxy 等。


----

uh... This is a correct character `???`. In version `0.8.5`, the logs from `program runtime` and `program capture events` have been distinguished. The former uses standard log levels for output, while the latter uses the Write method of the Logger for output. The former has standard [log levels](https://github.com/rs/zerolog/blob/master/globals.go#L141), while the latter does not, using the default [???](https://github.com/rs/zerolog/blob/c78e50e2da70f4ae63e1b65222c3acf12e9ba699/console.go#L32) instead.

In the future, program capture events will be sent to different Loggers for forwarding to other network proxy software, such as `Charles Proxy`, etc.

**Comment by xxxxxliil** [comment]
WARN 不会被记录在日志文件里也是预期行为吗？

**Comment by cfc4n** [comment]
> WARN 不会被记录在日志文件里也是预期行为吗？

都应该被记录到日志文件中，都是string写入到io对象。 不过，你可以给一些例子吗？ 从上面的截图中，并不能看出这个问题。

**Comment by xxxxxliil** [comment]
> > WARN 不会被记录在日志文件里也是预期行为吗？
> 
> 都应该被记录到日志文件中，都是string写入到io对象。 不过，你可以给一些例子吗？ 从上面的截图中，并不能看出这个问题。

现在尝试复现发现 warn 可以被正常记录。先关闭这个问题吧
