### ISSUE TITLE
SM-S908N 尝试抓 tls 包时手机画面冻结并重启

### ISSUE THREAD

**Issue by xxxxxliil** [gojue/ecapture#601]
**Describe the bug**
运行 S908NKSS4EXF1（构建时间：20240605090910）固件的 SM-S908N 使用 magisk su 运行 `ecapture tls [任意有效参数]` 不到五秒手机画面冻结，将近十秒后手机重启

**To Reproduce**
1. `# ./ecapture tls [Any valid parameter]`
2. output start log then [kale](https://www.urbandictionary.com/define.php?term=ka%20le)
3. device reboot

**Expected behavior**
正常进行抓包

**Screenshots**
截图无用，但是有两个 last_kmsg （实际收集了七次，筛掉了五个重复的），因为其中有一些信息疑似涉及隐私，请求私发

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: One UI 6.1?
- Arch: arm_aarch64
- Kernel Version: 5.10.198-android12-9-28575149-abS908NKSS4EXF1
- Version: androidgki_arm64:v0.8.5:6.5.0-1025-azure

**Comment by cfc4n** [comment]
你的环境比较特殊，我没有这种设备，很难重现这个bug。 看上去是内核对于ebpf hook处理上有一些异常。

**Comment by xxxxxliil** [comment]
> 你的环境比较特殊，我没有这种设备，很难重现这个bug。 看上去是内核对于ebpf hook处理上有一些异常。

有机会邮个手机？话说方便通过邮箱传内核日志吗

**Comment by cfc4n** [comment]
这倒不用。如果这个问题是大部分都会遇到的问题，我会想办法重现。如果是你个人遇到的小众问题，可能就辛苦你自己排查了。精力优先，无法支持特别小众、极端的场景。

**Comment by cfc4n** [comment]
超过2周无响应，关闭。

**Comment by xxxxxliil** [comment]
@cfc4n 请重新打开一下，日志压缩包已经发到公众号了，密码是 kmsg

**Comment by cfc4n** [comment]
公众号没有收到信息，不过，我也没有验证的环境啊。

**Comment by xxxxxliil** [comment]
> 公众号没有收到信息，不过，我也没有验证的环境啊。

发送了压缩包，提示不受支持的类型

**Comment by cfc4n** [comment]
> > 公众号没有收到信息，不过，我也没有验证的环境啊。
> 
> 发送了压缩包，提示不受支持的类型

可以上传在这里。 担心泄密的话，可以加密码，公众号告诉我解压密码即可。 （邮件也行）

**Comment by xxxxxliil** [comment]
> > > 公众号没有收到信息，不过，我也没有验证的环境啊。
> > 
> > 
> > 发送了压缩包，提示不受支持的类型
> 
> 可以上传在这里。 担心泄密的话，可以加密码，公众号告诉我解压密码即可。 （邮件也行）

我已经发了，zip 在图片里，原文件下载

**Comment by xxxxxliil** [comment]
@cfc4n 嘿，有在公众号看到带文件的图片吗？

**Comment by cfc4n** [comment]
无法解压。

**Comment by xxxxxliil** [comment]
> 无法解压。

如果是密码的话，在上面已经发过了

**Comment by cfc4n** [comment]
> > 无法解压。
> 
> 如果是密码的话，在上面已经发过了

压缩包格式不对，不是密码问题。

**Comment by xxxxxliil** [comment]
> > > 无法解压。
> > 
> > 
> > 如果是密码的话，在上面已经发过了
> 
> 压缩包格式不对，不是密码问题。 加QQ群吧，群里发文件。

请问你使用的解压工具是什么？我想了解一下会不会是压缩工具的问题

**Comment by cfc4n** [comment]
macOS自带的 `归档实用工具.app`、`The Unarchiver.app`、shell里的`unzip`都不行。 

```shell
unzip getimgdata.zip
Archive:  getimgdata.zip
warning [getimgdata.zip]:  297771 extra bytes at beginning or within zipfile
  (attempting to process anyway)
   skipping: last1                   unsupported compression method 99
   skipping: last2                   unsupported compression method 99
```

**Comment by xxxxxliil** [comment]
> macOS自带的 `归档实用工具.app`、`The Unarchiver.app`、shell里的`unzip`都不行。
> 
> ```shell
> unzip getimgdata.zip
> Archive:  getimgdata.zip
> warning [getimgdata.zip]:  297771 extra bytes at beginning or within zipfile
>   (attempting to process anyway)
>    skipping: last1                   unsupported compression method 99
>    skipping: last2                   unsupported compression method 99
> ```

搜了一下，发现 `compression method 99` 对应的是 AES 加密……在 win 上用 7zip 可以打开（如果嵌入图片则需要明确指定以 zip 读取），linux 上也可以通过 libzip/7z 提供 zip 支持的图形前端解压

https://support.redshield.co/hc/en-gb/articles/207523413-Creating-Encrypted-zip-Archives-using-Mac-OSX-or-Linux

如果环境不允许使用支持 AES 加密的压缩工具，我会换其他方式加密再发一次

**Comment by cfc4n** [comment]
QQ群里发呗，更方便。

**Comment by xxxxxliil** [comment]
> QQ群里发呗，更方便。

也行，顺便想知道 macos 上到底有没有可以解压 AES zip 的工具，如果没有就表示我需要重新压缩一份

**Comment by xxxxxliil** [comment]
已经通过邮件再发送了一份

**Comment by cfc4n** [comment]
邮件收到压缩包了，不过解压密码呢？   这个issue里也没密码啊，公众号里的聊天记录只保存30天。

哥们，跟你沟通起来成本很高啊，这么小心翼翼的，至于么？

**Comment by xxxxxliil** [comment]
> 邮件收到压缩包了，不过解压密码呢？ 这个issue里也没密码啊，公众号里的聊天记录只保存30天。

上面已经提到过，密码是 kmsg

**Comment by cfc4n** [comment]
OK，看到密码了。
`last2`文件里内容，宕机的点应该是`SDHMS:a1.e: 7735`进程，大概是该手机ROM自定义的进程，不清楚他如何实现，不能判断是否跟ebpf有关。
```shell
[  438.287296] [2:     SDHMS:a1.e: 7735] kernel BUG at drivers/soc/qcom/rpmh-rsc.c:898!
[  438.287312] [2:     SDHMS:a1.e: 7735] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
[  438.287433] [2:     SDHMS:a1.e: 7735] sec_arm64_ap_context:sec_arm64_ap_context_on_die() context saved (CPU:2)
```


你可以测试一下其他ebpf程序是否正常加载。 若可以，则尝试ecapture的text模式是否正常（即：`ecapture tls -m text`）。

另外，这个问题确实很小众，跟硬件、硬件驱动、定制内核都可能有关系，排查成本大，我未来很难有精力支持debug。 你先试试上面的思路，尝试定位吧。

**Comment by cfc4n** [comment]
Missing equipment, cannot reproduce.
