### ISSUE TITLE
Can't support 5.15.49-linuxkit .

### ISSUE THREAD

**Issue by lusains** [gojue/ecapture#615]
**Describe the bug**
Can't support 5.15.49-linuxkit .

**Linux Server/Android (please complete the following information):**
eCapture Makefile Environment:
PARALLEL                 6
CROSS_ARCH
ANDROID                  0
DEBUG                    0
SNAPSHOT_VERSION
HOST_ARCH                aarch64
UNAME_R                  5.15.49-linuxkit
CLANG_VERSION            14
GO_VERSION
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
CMD_CC_PREFIX
CMD_TAR                  tar
CMD_RPMBUILD             rpmbuild
CMD_RPM_SETUP_TREE       rpmdev-setuptree
VERSION_NUM              0.8.5-20240829-a2cb6ef
LAST_GIT_TAG             0.8.5-20240829-a2cb6ef
BPF_NOCORE_TAG           5_15_49-linuxkit.0_8_5-20240829-a2cb6ef
KERN_RELEASE             5.15.49-linuxkit
KERN_BUILD_PATH          /lib/modules/5.15.49-linuxkit/build
KERN_SRC_PATH            /lib/modules/5.15.49-linuxkit/build
TARGET_ARCH              aarch64
GOARCH                   arm64
LINUX_ARCH               arm64
LIBPCAP_ARCH             aarch64-unknown-linux-gnu
AUTOGENCMD               ls -al kern/bpf/arm64/vmlinux.h
PACKAGE_VERSION          0.0.0
OUT_DEB_FILE             ./bin/ecapture_v0.0.0_linux_arm64.deb

**Comment by Zheaoli** [comment]
提供一下具体的报错？

**Comment by cfc4n** [comment]
no response, closed.
