### ISSUE TITLE
Incorrect kernel version compare

### ISSUE THREAD

**Issue by yuchanns** [gojue/ecapture#617]
**Describe the bug**
Version compares result incorrect 6.10.6<5.2

**To Reproduce**

```
sudo ./ecapture tls --hex
```

**Expected behavior**
6.10.6>5.2

**Screenshots**
![2024-09-03_16-09](https://github.com/user-attachments/assets/3e3a31a9-9b48-491a-abb1-05fb494accf9)

**Linux Server/Android (please complete the following information):**

Linux asahi 6.10.6-401.asahi.fc40.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:13:13 UTC 2024 aarch64 GNU/Linux

**Additional context**

**Comment by Zheaoli** [comment]
问题确认，我来修一下

**Comment by cfc4n** [comment]
应该是已经修了，没发新版。
