### ISSUE TITLE
Failed to capture HTTPS traffic

### ISSUE THREAD

**Issue by lobsangshakya** [gojue/ecapture#627]
**Describe the bug**

**To Reproduce**
2. Type '....'
3. See error
4. upload the log file

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Device: [e.g. Pixel 4]
- Env: [run `ecapture -v` to get the eCapture version, or run the `make env` command for complete information]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. `uname -a`]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. arm64:0.7.7-20240303-bfb4a8c:5.15.0-113-generic]

**Additional context**

**Comment by cfc4n** [comment]
Duplicate with #622
