### ISSUE TITLE
In the MuMu 12 emulator, the pcap mode cannot work

### ISSUE THREAD

**Issue by gexiaopeng** [gojue/ecapture#634]
**1）用adb 连接MuMu模拟器12** (windows10)  ： adb shell  进入以后输入 su 切换到root用户
**2）MuMu12 内核版本**：Linux localhost 4.19.195-perf-gc77034d276bd #2 SMP PREEMPT Thu Sep 5 10:40:50 HKT 2024 aarch64
**3)运行命令**： ecapture tls  --libssl /system/apex/com.android.conscrypt/lib64/libssl.so -m pcap -i wlan0 -w /mnt/shared/MuMu12Shared/logs/ecapture.pcap
**4）ecapture版本:**[ecapture-v0.8.6-linux-amd64.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.8.6/ecapture-v0.8.6-linux-amd64.tar.gz)
**5）出错信息：** FTL module run failed, skip it. error="couldn't start bootstrap manager error:4 errors occurred:\n\t* error:error:netlink receive: no such file or directory , couldn't add a \", err clsact\" qdisc to interface 2, {UID:, EbpfFuncName:egress_cls_func}\n\t* error:error:netlink receive: no such file or directory , couldn't add a \", err clsact\" qdisc to interface 2, {UID:, EbpfFuncName:ingress_cls_func}\n\t* error:opening uprobe: symbol SSL_in_before: not found , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_in_before, EbpfFuncName:probe_ssl_master_key}\n\t* error:opening uprobe: invalid program: bad file descriptor , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_do_handshake, EbpfFuncName:probe_ssl_master_key}\n\n, probes activation validation failed ." isReload=false

**![微信截图_20240919094902](https://github.com/user-attachments/assets/a9c595b4-4664-4eb7-9930-f4a010a6c8ac)**

**Comment by cfc4n** [comment]
win的模拟器模拟的android，应该是不支持的。
