### ISSUE TITLE
In the MuMu 12 emulator, the `keylog` mode cannot work

### ISSUE THREAD

**Issue by gexiaopeng** [gojue/ecapture#635]
**1）用adb 连接MuMu模拟器12**  (windows10) ： adb shell  进入以后输入 su 切换到root用户
**2）MuMu12 内核版本**：Linux localhost 4.19.195-perf-gc77034d276bd https://github.com/gojue/ecapture/issues/2 SMP PREEMPT Thu Sep 5 10:40:50 HKT 2024 aarch64
**3)运行命令：** ecapture  tls --libssl=/system/apex/com.android.conscrypt/lib64/libssl.so -m keylog --keylogfile=openssl_keylog.log
**4）ecapture版本**:[ecapture-v0.8.6-linux-amd64.tar.gz](https://github.com/gojue/ecapture/releases/download/v0.8.6/ecapture-v0.8.6-linux-amd64.tar.gz)
**5）出错信息**：FTL module run failed, skip it. error="couldn't start bootstrap manager error:2 errors occurred:\n\t* error:opening uprobe: symbol SSL_in_before: not found , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_in_before, EbpfFuncName:probe_ssl_master_key}\n\t* error:opening uprobe: invalid program: bad file descriptor , isRet:false, opts:&{0 0 0 0 0 }, {UID:uprobe_smk_SSL_do_handshake, EbpfFuncName:probe_ssl_master_key}\n\n, probes activation validation failed ." isReload=false
![微信截图_keylog](https://github.com/user-attachments/assets/b61841b9-64c5-48c3-af48-f579b90f0013)

**Comment by cfc4n** [comment]
Please try to ask questions in English. If you are not proficient in English, then please write in Chinese characters and use translation software to translate into English. For some scenarios that are difficult to describe in English, you can use Chinese characters.

----

尽量使用英文提问。
如果英语不擅长，那么请写汉字，再使用翻译软件翻译为英文。   个别英文难以描述的场景，可以使用汉字。

**Comment by cfc4n** [comment]
It appears that the `SSL_in_before` symbol was not found. Please search within this shared object library to see which symbols start with `SSL_*`. Is there one named `SSL_do_handshake`?

**Comment by gexiaopeng** [comment]
> It appears that the `SSL_in_before` symbol was not found. Please search within this shared object library to see which symbols start with `SSL_*`. Is there one named `SSL_do_handshake`?

I couldn't find any symbols that start with "SSL_". What should we do now?
![1](https://github.com/user-attachments/assets/76a61b6e-459f-4b4c-8840-f3230cb94f6f)
![QQ20240920-091611](https://github.com/user-attachments/assets/7f8d22b7-a654-4263-8dec-6c9fab21d907)

**Comment by xxxxxliil** [comment]
会不会是 mumu 模拟器的 android 版本和 linux 内核版本都太低了导致的[](url)

**Comment by gexiaopeng** [comment]
> Linux localhost 4.19.195-perf-gc77034d276bd #2 SMP PREEMPT Thu Sep 5 10:40:50 HKT 2024 aarch64

安装版本是12,linux版本：Linux localhost 4.19.195-perf-gc77034d276bd https://github.com/gojue/ecapture/issues/2 SMP PREEMPT Thu Sep 5 10:40:50 HKT 2024 aarch64  ，估计是缺少ssl相关模块或者依赖lib

**Comment by cfc4n** [comment]
> > It appears that the `SSL_in_before` symbol was not found. Please search within this shared object library to see which symbols start with `SSL_*`. Is there one named `SSL_do_handshake`?
> 
> 
> 
> I couldn't find any symbols that start with "SSL_". What should we do now?
> 
> ![1](https://github.com/user-attachments/assets/76a61b6e-459f-4b4c-8840-f3230cb94f6f)
> 
> ![QQ20240920-091611](https://github.com/user-attachments/assets/7f8d22b7-a654-4263-8dec-6c9fab21d907)
> 
> 

你去学一下如何查看一个elf文件的符号表，学会后，再来看上面的问题。

**Comment by cfc4n** [comment]
No response for a long time, closed
