### ISSUE TITLE
unknown EbpfFuncName , couldn't find program at probe_entry_SSL_write

### ISSUE THREAD

**Issue by KardRi** [gojue/ecapture#649]
**Describe the bug**

on android 13 
Linux localhost 5.10.136-android12-9-00020-gc9f59ef34367-ab9585114 #1 SMP PREEMPT Wed Feb 8 23:50:57 UTC 2023 aarch64 Android

FTL module run failed, skip it. error="couldn't init manager xxx error:unknown EbpfFuncName , couldn't find program at probe_entry_SSL_write" isReload=false

8.6 works fine 
(Although some connections doesn't seem to capture in any app using webview, if using okhttp then it will be captured)
![image](https://github.com/user-attachments/assets/14cadede-dd27-4bba-9435-c9af3d8bba38)

8.7 does not
![image](https://github.com/user-attachments/assets/d242710a-0f9b-4315-91ce-89d81c967d0f)

**Comment by cfc4n** [comment]
It seems that there is an error when building v0.8.7, please replace it with v0.8.6 first.

**Comment by cfc4n** [comment]
It will be fixed in PR #648.

**Comment by KardRi** [comment]
FTL config check failed error="cant found openssl so load path"
![image](https://github.com/user-attachments/assets/accec73f-8892-4195-ac86-0c55c57c0411)

**Comment by KardRi** [comment]
It works now

![image](https://github.com/user-attachments/assets/4fd0ad9f-3ba7-4423-83c0-1b90e8f49da8)
