### ISSUE TITLE
如何看版本要求的最低内核版本，总不能一个一个的下载下来试吧

### ISSUE THREAD

**Issue by ench2** [gojue/ecapture#655]
**Describe the bug**
问题已解决
**To Reproduce**
2. Type '....'
3. See error
4. upload the log file

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Device: [e.g. Pixel 4]
- Env: [run `ecapture -v` to get the eCapture version, or run the `make env` command for complete information]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. `uname -a`]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. arm64:0.7.7-20240303-bfb4a8c:5.15.0-113-generic]

**Additional context**

**Comment by cfc4n** [comment]
看下readme吧。 



另外，不要用“反问”的语气。

**Comment by ench2** [comment]
不好意思，之前看README看到了，没将ISSUE关掉
