### ISSUE TITLE
如何为 openssl 3.4.0 增加支持？

### ISSUE THREAD

**Issue by xxxxxliil** [gojue/ecapture#656]
刚刚大小写锁定莫名其妙关闭了，在匆忙打开的途中不小心按到回车发出了没写完的标题和完全没写的问题。

arch 在一两周前把 openssl 更新到了 3.4.0，但是目前最新的有关获取 openssl 偏移相关的脚本仍是 3.3.*。我想试着为 3.4.0 增加支持但是不知如何下手

**Comment by cfc4n** [comment]
refer： #624

**Comment by xxxxxliil** [comment]
```
offset.c:38:21: error: call to undeclared library function 'toupper' with type 'int (int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   38 |             putchar(toupper(s[i]));
      |                     ^
offset.c:38:21: note: include the header <ctype.h> or explicitly provide a declaration for 'toupper'
```

看到了这个错误，但是 offset.c 第一行的注释要求只使用 openssl 的头文件，而且 openssl 提供的 crypto/ctype.h 中只有 `int ossl_toupper(int c)` 而不是 `int toupper(int c)`。可以在编译参数添加 `-I /usr/include` 吗？

**Comment by xxxxxliil** [comment]
所以可以加吗……不加会抱怨没那个函数啊

**Comment by xxxxxliil** [comment]
> refer： #624
> 
> * 复制 utils/openssl_offset_3.3.sh命名为3.4的shell脚本
> * 修改代码中切换分支、tags的代码
> * 修改代码中保存文件名为3.3相关特征为3.4
> * 根目录下执行sh utils/****3.4.sh

想要在 ecapture 中添加对应支持还差 #624 中没有做的一个或者两个步骤
- 在 variables.mk 中添加对应的 openssl target
- 提交时记得 add 更改过的 .sh 和生成的 .c 文件
