### ISSUE TITLE
为什么保存不了 pcap包，最新的版本，试了-w 和 --pcapfile ，就是生成不了pcap包

### ISSUE THREAD

**Issue by tengliu0929** [gojue/ecapture#657]
**Describe the bug**

**To Reproduce**
2. Type '....'
3. See error
4. upload the log file

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Device: [e.g. Pixel 4]
- Env: [run `ecapture -v` to get the eCapture version, or run the `make env` command for complete information]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. `uname -a`]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. arm64:0.7.7-20240303-bfb4a8c:5.15.0-113-generic]

**Additional context**

**Comment by cfc4n** [comment]
就标题一句话，其他任何信息都没有，请先学会提问吧。

**Comment by tengliu0929** [comment]
你要什么信息哈，操作系统ubuntu22404 lts,然后ecapture是最新版本，还有用的命令是
./ecapture tls --libssl=/usr/local/openresty/openssl3/lib/libssl.so.3 --pcapfile="/home/save.pcapng"

我也用过-w save.pcapng，但是不管用，看不到pcap或pcapng包
