### ISSUE TITLE
请教一下，怎么使用，能抓到tls明文的数据包

### ISSUE THREAD

**Issue by tengliu0929** [gojue/ecapture#658]
我先说下我的环境
  操作系统： ubuntu24.04, 内核版本6.3
我想抓的包是openresty的包，而openresty的依赖于“/usr/local/openresty/openssl3/lib/libssl.so.3”

我在机器上，先./ecapture tls -h先看了看说明，首先使用的命令是
    ./ecapture tls  --libssl=/usr/local/openresty/openssl3/lib/libssl.so.3
这条命令能在console中打印来往的http消息，然后我想着把这些http消息抓下，保存成pcap包，用wireshark分析，然后我又用了以下的命令：
   ./ecapture tls -w save.pcapng  --libssl=/usr/local/openresty/openssl3/lib/libssl.so.3 -m pcap -i ens33
不过抓下来的包，不是第一条命令打印的东西，我想，是不是哪一块出问题了，还是我操作不当？ 
我cat了下pcap包，然后里面保存的是CLIENT_HANDSHAKE_TRAFFIC_SECRET或SERVER_HANDSHAKE_TRAFFIC_SECRET,不过，我真的不需要这些，虽然我知道可以用wireshark解密，但如果直接拿出来明文，不是更好
于是我又加了一些约束条件
   ./ecapture tls -w save.pcapng  --libssl="/usr/local/openresty/openssl3/lib/libssl.so.3" -m pcap -i ens33 tcp port 8443
但是还是出不出我想要的结果，能否给说明一下，ecapture能否直接抓取tls的明文保存成pcap包呢？

**Comment by yuweizzz** [comment]
如果发起请求也是在本地，流量会因为经由 loopback 网卡无法获取，可以尝试从外部设备去访问 openresty 。

**Comment by tengliu0929** [comment]
多谢回复，我试一下
