### ISSUE TITLE
Can not get mobile browser packet or H5 app packet

### ISSUE THREAD

**Issue by WTFWITHTHISNAMESHIT** [gojue/ecapture#676]
**Describe the bug**

**To Reproduce**
1. Go to '...'   SEE TITLE
2. Type '....'   ./ecapture tls
3. See error   NONE
4. upload the log file  NONE

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Device: [e.g. Pixel 4]  Pixel 6
- Env: [run `ecapture -v` to get the eCapture version, or run the `make env` command for complete information]
- OS: [e.g. Ubuntu 21.04]   
- Arch: [e.g. `uname -a`]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. arm64:0.7.7-20240303-bfb4a8c:5.15.0-113-generic]

**Additional context**

**Comment by cfc4n** [comment]
Please describe your problem carefully

**Comment by cfc4n** [comment]
Low quality question, no response within 3 days, close it
