### ISSUE TITLE
performance issue: (*HTTP2Response).detect cost too much memory

### ISSUE THREAD

**Issue by chilli13** [gojue/ecapture#700]
Run ecapture -m text cost unexcepted cpu/memory resource.  After using the tool **perf**to analyze,(*HTTP2Response).detect consumed a lot of resources. After removing this function  **(*HTTP2Response).detec**t  and **(*HTTP2Request).detect* and recompiling the ecapture to run testcase, the performance was significantly improved.
Small files access https server with high concurrency, construct 50Mbps traffic, average memory 550M, maximum memory 677.66M. After optimization **(*HTTP2Response).detec**t  and **(*HTTP2Request).detect** , memory is reduced to 293.016M

# Linux Server:
Device: VM
OS: [ctyunos 2.0.1]
Arch: 4.19.90-2102.2.0.0062.ctl2.x86_64 #1 SMP Thu Mar 10 03:34:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Kernel Version: 4.19

1. modify makefile compile option to obtain symbol information
2. perf record $(pidof ecapture)
3. perf report
![image](https://github.com/user-attachments/assets/6abca062-4ad2-4b96-9526-970d75184d39)

**Comment by yuweizzz** [comment]
would you describe how you optimization this function?

**Comment by chilli13** [comment]
> would you describe how you optimization this function?

I just simply removed the https2 Register function and tested it to confirm the impact of http2 detect on performance. The ecapture  memory consumption was significantly reduced without **http2.detect**  on same testcase. As our application scenario has limited resources, we will pay more attention to the performance consumption of the introduced components.


```
diff --git a/pkg/event_processor/http2_request.go b/pkg/event_processor/http2_request.go
index ac83c60..5dba2a8 100644
--- a/pkg/event_processor/http2_request.go
+++ b/pkg/event_processor/http2_request.go
@@ -147,7 +147,8 @@ func (h2r *HTTP2Request) Display() []byte {
 func init() {
        h2r := &HTTP2Request{}
        h2r.Init()
-       Register(h2r)
+       //tmp
+       //Register(h2r)
 }
 
 func (h2r *HTTP2Request) Reset() {
diff --git a/pkg/event_processor/http2_response.go b/pkg/event_processor/http2_response.go
index 2a2d411..82763ea 100644
--- a/pkg/event_processor/http2_response.go
+++ b/pkg/event_processor/http2_response.go
@@ -142,7 +142,8 @@ func (h2r *HTTP2Response) Display() []byte {
 func init() {
        h2r := &HTTP2Response{}
        h2r.Init()
-       Register(h2r)
+       //tmp
+       //Register(h2r)
 }
 

```

**Comment by yuweizzz** [comment]
the h2 response detect is much complicated than h2 request, maybe we can find a new way to optimize it. could you try Register the h2 request and without Register h2 response?

**Comment by yuweizzz** [comment]
please assign it to me, I will try to fix it.

**Comment by chilli13** [comment]
> Register the h2 request

Register the **h2 request** has no noticeable impact on performance. As you would expect, the performance bottleneck should mainly be caused by **h2 response**

**Comment by cfc4n** [comment]
> please assign it to me, I will try to fix it.

Can you tell me your solution?
