### ISSUE TITLE
could support save plaintext to file with -m text

### ISSUE THREAD

**Issue by chilli13** [gojue/ecapture#701]
similar with  **--keylogfile**, would u consider add a paramter such as **--textlogfile** to save plaintext to file? Thks

```
  -k, --keylogfile="ecapture_openssl_key.log"	The file stores SSL/TLS keys, and eCapture captures these keys during encrypted traffic communication and saves them to the file.
```

Although using the shell's redirected output can meet this requirement, this method is not convenient to apply and will retain ecapture  log info (WRN/INF/etc.)

**Comment by cfc4n** [comment]
see `--eventaddr` flag for more detail.
